#!/bin/bash
cd $HOME/apps/pantherScore2.2
for i in {001..025}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {026..050}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {051..075}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {076..100}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {101..125}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {126..150}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {151..175}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {176..200}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {201..225}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {226..250}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {251..275}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {276..300}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {301..325}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {326..350}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {351..375}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
for i in {376..395}; do pantherScore2.2.pl -c 2 -D B -i $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split/transcripts.fasta.transdecoder.part_"$i".pep -l $HOME/apps/PANTHER18.0 -n -o $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.pantherScore/"$i".tab -T $HOME/twg/rnaseq/transdecoder/transcripts.fasta.transdecoder.pep.split.domtblout/"$i"/ & done; wait
