library(tidyverse)
library(ggvenn)
library(gridExtra)

gene.gff3 <- readRDS(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.0/gene.gff3.RDS")
#gene.gff3 <- select(gene.gff3, -start, -end) |> rename(start=prostart, end=proend) |> arrange(seqid, start)

iHS <- read_tsv(file="/Volumes/Tigrigobius/tgoby/iHS/selscan/gmap/outliers.PROP_CRIT.tab", col_types="nnnnnnnnnncnnnncnn")

iHS <- filter(iHS, RANK_PROP_CRIT>0.995)

genes.within.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==iHS$CHROM[1], start>=iHS$START[1] & end<=iHS$END[1]) |> mutate(iHS_start=iHS$START[1], iHS_end=iHS$END[1], iHS_pop=iHS$POP[1]),
    filter(gene.gff3, seqid==iHS$CHROM[2], start>=iHS$START[2] & end<=iHS$END[2]) |> mutate(iHS_start=iHS$START[2], iHS_end=iHS$END[2], iHS_pop=iHS$POP[2]),
    filter(gene.gff3, seqid==iHS$CHROM[3], start>=iHS$START[3] & end<=iHS$END[3]) |> mutate(iHS_start=iHS$START[3], iHS_end=iHS$END[3], iHS_pop=iHS$POP[3]),
    filter(gene.gff3, seqid==iHS$CHROM[4], start>=iHS$START[4] & end<=iHS$END[4]) |> mutate(iHS_start=iHS$START[4], iHS_end=iHS$END[4], iHS_pop=iHS$POP[4]),
    filter(gene.gff3, seqid==iHS$CHROM[5], start>=iHS$START[5] & end<=iHS$END[5]) |> mutate(iHS_start=iHS$START[5], iHS_end=iHS$END[5], iHS_pop=iHS$POP[5]),
    filter(gene.gff3, seqid==iHS$CHROM[6], start>=iHS$START[6] & end<=iHS$END[6]) |> mutate(iHS_start=iHS$START[6], iHS_end=iHS$END[6], iHS_pop=iHS$POP[6]),
    filter(gene.gff3, seqid==iHS$CHROM[7], start>=iHS$START[7] & end<=iHS$END[7]) |> mutate(iHS_start=iHS$START[7], iHS_end=iHS$END[7], iHS_pop=iHS$POP[7]),
    filter(gene.gff3, seqid==iHS$CHROM[8], start>=iHS$START[8] & end<=iHS$END[8]) |> mutate(iHS_start=iHS$START[8], iHS_end=iHS$END[8], iHS_pop=iHS$POP[8]),
    filter(gene.gff3, seqid==iHS$CHROM[9], start>=iHS$START[9] & end<=iHS$END[9]) |> mutate(iHS_start=iHS$START[9], iHS_end=iHS$END[9], iHS_pop=iHS$POP[9]),
    filter(gene.gff3, seqid==iHS$CHROM[10], start>=iHS$START[10] & end<=iHS$END[10]) |> mutate(iHS_start=iHS$START[10], iHS_end=iHS$END[10], iHS_pop=iHS$POP[10]),
    filter(gene.gff3, seqid==iHS$CHROM[11], start>=iHS$START[11] & end<=iHS$END[11]) |> mutate(iHS_start=iHS$START[11], iHS_end=iHS$END[11], iHS_pop=iHS$POP[11]),
    filter(gene.gff3, seqid==iHS$CHROM[12], start>=iHS$START[12] & end<=iHS$END[12]) |> mutate(iHS_start=iHS$START[12], iHS_end=iHS$END[12], iHS_pop=iHS$POP[12]),
    filter(gene.gff3, seqid==iHS$CHROM[13], start>=iHS$START[13] & end<=iHS$END[13]) |> mutate(iHS_start=iHS$START[13], iHS_end=iHS$END[13], iHS_pop=iHS$POP[13]),
    filter(gene.gff3, seqid==iHS$CHROM[14], start>=iHS$START[14] & end<=iHS$END[14]) |> mutate(iHS_start=iHS$START[14], iHS_end=iHS$END[14], iHS_pop=iHS$POP[14]),
    filter(gene.gff3, seqid==iHS$CHROM[15], start>=iHS$START[15] & end<=iHS$END[15]) |> mutate(iHS_start=iHS$START[15], iHS_end=iHS$END[15], iHS_pop=iHS$POP[15]),
    filter(gene.gff3, seqid==iHS$CHROM[16], start>=iHS$START[16] & end<=iHS$END[16]) |> mutate(iHS_start=iHS$START[16], iHS_end=iHS$END[16], iHS_pop=iHS$POP[16]),
    filter(gene.gff3, seqid==iHS$CHROM[17], start>=iHS$START[17] & end<=iHS$END[17]) |> mutate(iHS_start=iHS$START[17], iHS_end=iHS$END[17], iHS_pop=iHS$POP[17]),
    filter(gene.gff3, seqid==iHS$CHROM[18], start>=iHS$START[18] & end<=iHS$END[18]) |> mutate(iHS_start=iHS$START[18], iHS_end=iHS$END[18], iHS_pop=iHS$POP[18]),
    filter(gene.gff3, seqid==iHS$CHROM[19], start>=iHS$START[19] & end<=iHS$END[19]) |> mutate(iHS_start=iHS$START[19], iHS_end=iHS$END[19], iHS_pop=iHS$POP[19]),
    filter(gene.gff3, seqid==iHS$CHROM[20], start>=iHS$START[20] & end<=iHS$END[20]) |> mutate(iHS_start=iHS$START[20], iHS_end=iHS$END[20], iHS_pop=iHS$POP[20]),
    filter(gene.gff3, seqid==iHS$CHROM[21], start>=iHS$START[21] & end<=iHS$END[21]) |> mutate(iHS_start=iHS$START[21], iHS_end=iHS$END[21], iHS_pop=iHS$POP[21]),
    filter(gene.gff3, seqid==iHS$CHROM[22], start>=iHS$START[22] & end<=iHS$END[22]) |> mutate(iHS_start=iHS$START[22], iHS_end=iHS$END[22], iHS_pop=iHS$POP[22]),
    filter(gene.gff3, seqid==iHS$CHROM[23], start>=iHS$START[23] & end<=iHS$END[23]) |> mutate(iHS_start=iHS$START[23], iHS_end=iHS$END[23], iHS_pop=iHS$POP[23]),
    filter(gene.gff3, seqid==iHS$CHROM[24], start>=iHS$START[24] & end<=iHS$END[24]) |> mutate(iHS_start=iHS$START[24], iHS_end=iHS$END[24], iHS_pop=iHS$POP[24]),
    filter(gene.gff3, seqid==iHS$CHROM[25], start>=iHS$START[25] & end<=iHS$END[25]) |> mutate(iHS_start=iHS$START[25], iHS_end=iHS$END[25], iHS_pop=iHS$POP[25]),
    filter(gene.gff3, seqid==iHS$CHROM[26], start>=iHS$START[26] & end<=iHS$END[26]) |> mutate(iHS_start=iHS$START[26], iHS_end=iHS$END[26], iHS_pop=iHS$POP[26]),
    filter(gene.gff3, seqid==iHS$CHROM[27], start>=iHS$START[27] & end<=iHS$END[27]) |> mutate(iHS_start=iHS$START[27], iHS_end=iHS$END[27], iHS_pop=iHS$POP[27]),
    filter(gene.gff3, seqid==iHS$CHROM[28], start>=iHS$START[28] & end<=iHS$END[28]) |> mutate(iHS_start=iHS$START[28], iHS_end=iHS$END[28], iHS_pop=iHS$POP[28]),
    filter(gene.gff3, seqid==iHS$CHROM[29], start>=iHS$START[29] & end<=iHS$END[29]) |> mutate(iHS_start=iHS$START[29], iHS_end=iHS$END[29], iHS_pop=iHS$POP[29]),
    filter(gene.gff3, seqid==iHS$CHROM[30], start>=iHS$START[30] & end<=iHS$END[30]) |> mutate(iHS_start=iHS$START[30], iHS_end=iHS$END[30], iHS_pop=iHS$POP[30]),
    filter(gene.gff3, seqid==iHS$CHROM[31], start>=iHS$START[31] & end<=iHS$END[31]) |> mutate(iHS_start=iHS$START[31], iHS_end=iHS$END[31], iHS_pop=iHS$POP[31]),
    filter(gene.gff3, seqid==iHS$CHROM[32], start>=iHS$START[32] & end<=iHS$END[32]) |> mutate(iHS_start=iHS$START[32], iHS_end=iHS$END[32], iHS_pop=iHS$POP[32]),
    filter(gene.gff3, seqid==iHS$CHROM[33], start>=iHS$START[33] & end<=iHS$END[33]) |> mutate(iHS_start=iHS$START[33], iHS_end=iHS$END[33], iHS_pop=iHS$POP[33]),
    filter(gene.gff3, seqid==iHS$CHROM[34], start>=iHS$START[34] & end<=iHS$END[34]) |> mutate(iHS_start=iHS$START[34], iHS_end=iHS$END[34], iHS_pop=iHS$POP[34]),
    filter(gene.gff3, seqid==iHS$CHROM[35], start>=iHS$START[35] & end<=iHS$END[35]) |> mutate(iHS_start=iHS$START[35], iHS_end=iHS$END[35], iHS_pop=iHS$POP[35]),
    filter(gene.gff3, seqid==iHS$CHROM[36], start>=iHS$START[36] & end<=iHS$END[36]) |> mutate(iHS_start=iHS$START[36], iHS_end=iHS$END[36], iHS_pop=iHS$POP[36]),
    filter(gene.gff3, seqid==iHS$CHROM[37], start>=iHS$START[37] & end<=iHS$END[37]) |> mutate(iHS_start=iHS$START[37], iHS_end=iHS$END[37], iHS_pop=iHS$POP[37]),
    filter(gene.gff3, seqid==iHS$CHROM[38], start>=iHS$START[38] & end<=iHS$END[38]) |> mutate(iHS_start=iHS$START[38], iHS_end=iHS$END[38], iHS_pop=iHS$POP[38]),
    filter(gene.gff3, seqid==iHS$CHROM[39], start>=iHS$START[39] & end<=iHS$END[39]) |> mutate(iHS_start=iHS$START[39], iHS_end=iHS$END[39], iHS_pop=iHS$POP[39]),
    filter(gene.gff3, seqid==iHS$CHROM[40], start>=iHS$START[40] & end<=iHS$END[40]) |> mutate(iHS_start=iHS$START[40], iHS_end=iHS$END[40], iHS_pop=iHS$POP[40]),
    filter(gene.gff3, seqid==iHS$CHROM[41], start>=iHS$START[41] & end<=iHS$END[41]) |> mutate(iHS_start=iHS$START[41], iHS_end=iHS$END[41], iHS_pop=iHS$POP[41]),
    filter(gene.gff3, seqid==iHS$CHROM[42], start>=iHS$START[42] & end<=iHS$END[42]) |> mutate(iHS_start=iHS$START[42], iHS_end=iHS$END[42], iHS_pop=iHS$POP[42]),
    filter(gene.gff3, seqid==iHS$CHROM[43], start>=iHS$START[43] & end<=iHS$END[43]) |> mutate(iHS_start=iHS$START[43], iHS_end=iHS$END[43], iHS_pop=iHS$POP[43]),
    filter(gene.gff3, seqid==iHS$CHROM[44], start>=iHS$START[44] & end<=iHS$END[44]) |> mutate(iHS_start=iHS$START[44], iHS_end=iHS$END[44], iHS_pop=iHS$POP[44]),
    filter(gene.gff3, seqid==iHS$CHROM[45], start>=iHS$START[45] & end<=iHS$END[45]) |> mutate(iHS_start=iHS$START[45], iHS_end=iHS$END[45], iHS_pop=iHS$POP[45]),
    filter(gene.gff3, seqid==iHS$CHROM[46], start>=iHS$START[46] & end<=iHS$END[46]) |> mutate(iHS_start=iHS$START[46], iHS_end=iHS$END[46], iHS_pop=iHS$POP[46]),
    filter(gene.gff3, seqid==iHS$CHROM[47], start>=iHS$START[47] & end<=iHS$END[47]) |> mutate(iHS_start=iHS$START[47], iHS_end=iHS$END[47], iHS_pop=iHS$POP[47]),
    filter(gene.gff3, seqid==iHS$CHROM[48], start>=iHS$START[48] & end<=iHS$END[48]) |> mutate(iHS_start=iHS$START[48], iHS_end=iHS$END[48], iHS_pop=iHS$POP[48]),
    filter(gene.gff3, seqid==iHS$CHROM[49], start>=iHS$START[49] & end<=iHS$END[49]) |> mutate(iHS_start=iHS$START[49], iHS_end=iHS$END[49], iHS_pop=iHS$POP[49]),
    filter(gene.gff3, seqid==iHS$CHROM[50], start>=iHS$START[50] & end<=iHS$END[50]) |> mutate(iHS_start=iHS$START[50], iHS_end=iHS$END[50], iHS_pop=iHS$POP[50]),
    filter(gene.gff3, seqid==iHS$CHROM[51], start>=iHS$START[51] & end<=iHS$END[51]) |> mutate(iHS_start=iHS$START[51], iHS_end=iHS$END[51], iHS_pop=iHS$POP[51]),
    filter(gene.gff3, seqid==iHS$CHROM[52], start>=iHS$START[52] & end<=iHS$END[52]) |> mutate(iHS_start=iHS$START[52], iHS_end=iHS$END[52], iHS_pop=iHS$POP[52]),
    filter(gene.gff3, seqid==iHS$CHROM[53], start>=iHS$START[53] & end<=iHS$END[53]) |> mutate(iHS_start=iHS$START[53], iHS_end=iHS$END[53], iHS_pop=iHS$POP[53]),
    filter(gene.gff3, seqid==iHS$CHROM[54], start>=iHS$START[54] & end<=iHS$END[54]) |> mutate(iHS_start=iHS$START[54], iHS_end=iHS$END[54], iHS_pop=iHS$POP[54]),
    filter(gene.gff3, seqid==iHS$CHROM[55], start>=iHS$START[55] & end<=iHS$END[55]) |> mutate(iHS_start=iHS$START[55], iHS_end=iHS$END[55], iHS_pop=iHS$POP[55]),
    filter(gene.gff3, seqid==iHS$CHROM[56], start>=iHS$START[56] & end<=iHS$END[56]) |> mutate(iHS_start=iHS$START[56], iHS_end=iHS$END[56], iHS_pop=iHS$POP[56]),
    filter(gene.gff3, seqid==iHS$CHROM[57], start>=iHS$START[57] & end<=iHS$END[57]) |> mutate(iHS_start=iHS$START[57], iHS_end=iHS$END[57], iHS_pop=iHS$POP[57]),
    filter(gene.gff3, seqid==iHS$CHROM[58], start>=iHS$START[58] & end<=iHS$END[58]) |> mutate(iHS_start=iHS$START[58], iHS_end=iHS$END[58], iHS_pop=iHS$POP[58]),
    filter(gene.gff3, seqid==iHS$CHROM[59], start>=iHS$START[59] & end<=iHS$END[59]) |> mutate(iHS_start=iHS$START[59], iHS_end=iHS$END[59], iHS_pop=iHS$POP[59]),
    filter(gene.gff3, seqid==iHS$CHROM[60], start>=iHS$START[60] & end<=iHS$END[60]) |> mutate(iHS_start=iHS$START[60], iHS_end=iHS$END[60], iHS_pop=iHS$POP[60]),
    filter(gene.gff3, seqid==iHS$CHROM[61], start>=iHS$START[61] & end<=iHS$END[61]) |> mutate(iHS_start=iHS$START[61], iHS_end=iHS$END[61], iHS_pop=iHS$POP[61]),
    filter(gene.gff3, seqid==iHS$CHROM[62], start>=iHS$START[62] & end<=iHS$END[62]) |> mutate(iHS_start=iHS$START[62], iHS_end=iHS$END[62], iHS_pop=iHS$POP[62]),
    filter(gene.gff3, seqid==iHS$CHROM[63], start>=iHS$START[63] & end<=iHS$END[63]) |> mutate(iHS_start=iHS$START[63], iHS_end=iHS$END[63], iHS_pop=iHS$POP[63]),
    filter(gene.gff3, seqid==iHS$CHROM[64], start>=iHS$START[64] & end<=iHS$END[64]) |> mutate(iHS_start=iHS$START[64], iHS_end=iHS$END[64], iHS_pop=iHS$POP[64]),
    filter(gene.gff3, seqid==iHS$CHROM[65], start>=iHS$START[65] & end<=iHS$END[65]) |> mutate(iHS_start=iHS$START[65], iHS_end=iHS$END[65], iHS_pop=iHS$POP[65]),
    filter(gene.gff3, seqid==iHS$CHROM[66], start>=iHS$START[66] & end<=iHS$END[66]) |> mutate(iHS_start=iHS$START[66], iHS_end=iHS$END[66], iHS_pop=iHS$POP[66]),
    filter(gene.gff3, seqid==iHS$CHROM[67], start>=iHS$START[67] & end<=iHS$END[67]) |> mutate(iHS_start=iHS$START[67], iHS_end=iHS$END[67], iHS_pop=iHS$POP[67]),
    filter(gene.gff3, seqid==iHS$CHROM[68], start>=iHS$START[68] & end<=iHS$END[68]) |> mutate(iHS_start=iHS$START[68], iHS_end=iHS$END[68], iHS_pop=iHS$POP[68]),
    filter(gene.gff3, seqid==iHS$CHROM[69], start>=iHS$START[69] & end<=iHS$END[69]) |> mutate(iHS_start=iHS$START[69], iHS_end=iHS$END[69], iHS_pop=iHS$POP[69]),
    filter(gene.gff3, seqid==iHS$CHROM[70], start>=iHS$START[70] & end<=iHS$END[70]) |> mutate(iHS_start=iHS$START[70], iHS_end=iHS$END[70], iHS_pop=iHS$POP[70]),
    filter(gene.gff3, seqid==iHS$CHROM[71], start>=iHS$START[71] & end<=iHS$END[71]) |> mutate(iHS_start=iHS$START[71], iHS_end=iHS$END[71], iHS_pop=iHS$POP[71]),
    filter(gene.gff3, seqid==iHS$CHROM[72], start>=iHS$START[72] & end<=iHS$END[72]) |> mutate(iHS_start=iHS$START[72], iHS_end=iHS$END[72], iHS_pop=iHS$POP[72]),
    filter(gene.gff3, seqid==iHS$CHROM[73], start>=iHS$START[73] & end<=iHS$END[73]) |> mutate(iHS_start=iHS$START[73], iHS_end=iHS$END[73], iHS_pop=iHS$POP[73]),
    filter(gene.gff3, seqid==iHS$CHROM[74], start>=iHS$START[74] & end<=iHS$END[74]) |> mutate(iHS_start=iHS$START[74], iHS_end=iHS$END[74], iHS_pop=iHS$POP[74]),
    filter(gene.gff3, seqid==iHS$CHROM[75], start>=iHS$START[75] & end<=iHS$END[75]) |> mutate(iHS_start=iHS$START[75], iHS_end=iHS$END[75], iHS_pop=iHS$POP[75]),
    filter(gene.gff3, seqid==iHS$CHROM[76], start>=iHS$START[76] & end<=iHS$END[76]) |> mutate(iHS_start=iHS$START[76], iHS_end=iHS$END[76], iHS_pop=iHS$POP[76]),
    filter(gene.gff3, seqid==iHS$CHROM[77], start>=iHS$START[77] & end<=iHS$END[77]) |> mutate(iHS_start=iHS$START[77], iHS_end=iHS$END[77], iHS_pop=iHS$POP[77]),
    filter(gene.gff3, seqid==iHS$CHROM[78], start>=iHS$START[78] & end<=iHS$END[78]) |> mutate(iHS_start=iHS$START[78], iHS_end=iHS$END[78], iHS_pop=iHS$POP[78]),
    filter(gene.gff3, seqid==iHS$CHROM[79], start>=iHS$START[79] & end<=iHS$END[79]) |> mutate(iHS_start=iHS$START[79], iHS_end=iHS$END[79], iHS_pop=iHS$POP[79]),
    filter(gene.gff3, seqid==iHS$CHROM[80], start>=iHS$START[80] & end<=iHS$END[80]) |> mutate(iHS_start=iHS$START[80], iHS_end=iHS$END[80], iHS_pop=iHS$POP[80]),
    filter(gene.gff3, seqid==iHS$CHROM[81], start>=iHS$START[81] & end<=iHS$END[81]) |> mutate(iHS_start=iHS$START[81], iHS_end=iHS$END[81], iHS_pop=iHS$POP[81]),
    filter(gene.gff3, seqid==iHS$CHROM[82], start>=iHS$START[82] & end<=iHS$END[82]) |> mutate(iHS_start=iHS$START[82], iHS_end=iHS$END[82], iHS_pop=iHS$POP[82]),
    filter(gene.gff3, seqid==iHS$CHROM[83], start>=iHS$START[83] & end<=iHS$END[83]) |> mutate(iHS_start=iHS$START[83], iHS_end=iHS$END[83], iHS_pop=iHS$POP[83]),
    filter(gene.gff3, seqid==iHS$CHROM[84], start>=iHS$START[84] & end<=iHS$END[84]) |> mutate(iHS_start=iHS$START[84], iHS_end=iHS$END[84], iHS_pop=iHS$POP[84]),
    filter(gene.gff3, seqid==iHS$CHROM[85], start>=iHS$START[85] & end<=iHS$END[85]) |> mutate(iHS_start=iHS$START[85], iHS_end=iHS$END[85], iHS_pop=iHS$POP[85]),
    filter(gene.gff3, seqid==iHS$CHROM[86], start>=iHS$START[86] & end<=iHS$END[86]) |> mutate(iHS_start=iHS$START[86], iHS_end=iHS$END[86], iHS_pop=iHS$POP[86]),
    filter(gene.gff3, seqid==iHS$CHROM[87], start>=iHS$START[87] & end<=iHS$END[87]) |> mutate(iHS_start=iHS$START[87], iHS_end=iHS$END[87], iHS_pop=iHS$POP[87]),
    filter(gene.gff3, seqid==iHS$CHROM[88], start>=iHS$START[88] & end<=iHS$END[88]) |> mutate(iHS_start=iHS$START[88], iHS_end=iHS$END[88], iHS_pop=iHS$POP[88]),
    filter(gene.gff3, seqid==iHS$CHROM[89], start>=iHS$START[89] & end<=iHS$END[89]) |> mutate(iHS_start=iHS$START[89], iHS_end=iHS$END[89], iHS_pop=iHS$POP[89]),
    filter(gene.gff3, seqid==iHS$CHROM[90], start>=iHS$START[90] & end<=iHS$END[90]) |> mutate(iHS_start=iHS$START[90], iHS_end=iHS$END[90], iHS_pop=iHS$POP[90]),
    filter(gene.gff3, seqid==iHS$CHROM[91], start>=iHS$START[91] & end<=iHS$END[91]) |> mutate(iHS_start=iHS$START[91], iHS_end=iHS$END[91], iHS_pop=iHS$POP[91]),
    filter(gene.gff3, seqid==iHS$CHROM[92], start>=iHS$START[92] & end<=iHS$END[92]) |> mutate(iHS_start=iHS$START[92], iHS_end=iHS$END[92], iHS_pop=iHS$POP[92]),
    filter(gene.gff3, seqid==iHS$CHROM[93], start>=iHS$START[93] & end<=iHS$END[93]) |> mutate(iHS_start=iHS$START[93], iHS_end=iHS$END[93], iHS_pop=iHS$POP[93]),
    filter(gene.gff3, seqid==iHS$CHROM[94], start>=iHS$START[94] & end<=iHS$END[94]) |> mutate(iHS_start=iHS$START[94], iHS_end=iHS$END[94], iHS_pop=iHS$POP[94]),
    filter(gene.gff3, seqid==iHS$CHROM[95], start>=iHS$START[95] & end<=iHS$END[95]) |> mutate(iHS_start=iHS$START[95], iHS_end=iHS$END[95], iHS_pop=iHS$POP[95]),
    filter(gene.gff3, seqid==iHS$CHROM[96], start>=iHS$START[96] & end<=iHS$END[96]) |> mutate(iHS_start=iHS$START[96], iHS_end=iHS$END[96], iHS_pop=iHS$POP[96]),
    filter(gene.gff3, seqid==iHS$CHROM[97], start>=iHS$START[97] & end<=iHS$END[97]) |> mutate(iHS_start=iHS$START[97], iHS_end=iHS$END[97], iHS_pop=iHS$POP[97]),
    filter(gene.gff3, seqid==iHS$CHROM[98], start>=iHS$START[98] & end<=iHS$END[98]) |> mutate(iHS_start=iHS$START[98], iHS_end=iHS$END[98], iHS_pop=iHS$POP[98]),
    filter(gene.gff3, seqid==iHS$CHROM[99], start>=iHS$START[99] & end<=iHS$END[99]) |> mutate(iHS_start=iHS$START[99], iHS_end=iHS$END[99], iHS_pop=iHS$POP[99]),
    filter(gene.gff3, seqid==iHS$CHROM[100], start>=iHS$START[100] & end<=iHS$END[100]) |> mutate(iHS_start=iHS$START[100], iHS_end=iHS$END[100], iHS_pop=iHS$POP[100]),
    filter(gene.gff3, seqid==iHS$CHROM[101], start>=iHS$START[101] & end<=iHS$END[101]) |> mutate(iHS_start=iHS$START[101], iHS_end=iHS$END[101], iHS_pop=iHS$POP[101]),
    filter(gene.gff3, seqid==iHS$CHROM[102], start>=iHS$START[102] & end<=iHS$END[102]) |> mutate(iHS_start=iHS$START[102], iHS_end=iHS$END[102], iHS_pop=iHS$POP[102]),
    filter(gene.gff3, seqid==iHS$CHROM[103], start>=iHS$START[103] & end<=iHS$END[103]) |> mutate(iHS_start=iHS$START[103], iHS_end=iHS$END[103], iHS_pop=iHS$POP[103]),
    filter(gene.gff3, seqid==iHS$CHROM[104], start>=iHS$START[104] & end<=iHS$END[104]) |> mutate(iHS_start=iHS$START[104], iHS_end=iHS$END[104], iHS_pop=iHS$POP[104]),
    filter(gene.gff3, seqid==iHS$CHROM[105], start>=iHS$START[105] & end<=iHS$END[105]) |> mutate(iHS_start=iHS$START[105], iHS_end=iHS$END[105], iHS_pop=iHS$POP[105]),
    filter(gene.gff3, seqid==iHS$CHROM[106], start>=iHS$START[106] & end<=iHS$END[106]) |> mutate(iHS_start=iHS$START[106], iHS_end=iHS$END[106], iHS_pop=iHS$POP[106]),
    filter(gene.gff3, seqid==iHS$CHROM[107], start>=iHS$START[107] & end<=iHS$END[107]) |> mutate(iHS_start=iHS$START[107], iHS_end=iHS$END[107], iHS_pop=iHS$POP[107]),
    filter(gene.gff3, seqid==iHS$CHROM[108], start>=iHS$START[108] & end<=iHS$END[108]) |> mutate(iHS_start=iHS$START[108], iHS_end=iHS$END[108], iHS_pop=iHS$POP[108]),
    filter(gene.gff3, seqid==iHS$CHROM[109], start>=iHS$START[109] & end<=iHS$END[109]) |> mutate(iHS_start=iHS$START[109], iHS_end=iHS$END[109], iHS_pop=iHS$POP[109]),
    filter(gene.gff3, seqid==iHS$CHROM[110], start>=iHS$START[110] & end<=iHS$END[110]) |> mutate(iHS_start=iHS$START[110], iHS_end=iHS$END[110], iHS_pop=iHS$POP[110]),
    filter(gene.gff3, seqid==iHS$CHROM[111], start>=iHS$START[111] & end<=iHS$END[111]) |> mutate(iHS_start=iHS$START[111], iHS_end=iHS$END[111], iHS_pop=iHS$POP[111]),
    filter(gene.gff3, seqid==iHS$CHROM[112], start>=iHS$START[112] & end<=iHS$END[112]) |> mutate(iHS_start=iHS$START[112], iHS_end=iHS$END[112], iHS_pop=iHS$POP[112]),
    filter(gene.gff3, seqid==iHS$CHROM[113], start>=iHS$START[113] & end<=iHS$END[113]) |> mutate(iHS_start=iHS$START[113], iHS_end=iHS$END[113], iHS_pop=iHS$POP[113]),
    filter(gene.gff3, seqid==iHS$CHROM[114], start>=iHS$START[114] & end<=iHS$END[114]) |> mutate(iHS_start=iHS$START[114], iHS_end=iHS$END[114], iHS_pop=iHS$POP[114]),
    filter(gene.gff3, seqid==iHS$CHROM[115], start>=iHS$START[115] & end<=iHS$END[115]) |> mutate(iHS_start=iHS$START[115], iHS_end=iHS$END[115], iHS_pop=iHS$POP[115]),
    filter(gene.gff3, seqid==iHS$CHROM[116], start>=iHS$START[116] & end<=iHS$END[116]) |> mutate(iHS_start=iHS$START[116], iHS_end=iHS$END[116], iHS_pop=iHS$POP[116]),
    filter(gene.gff3, seqid==iHS$CHROM[117], start>=iHS$START[117] & end<=iHS$END[117]) |> mutate(iHS_start=iHS$START[117], iHS_end=iHS$END[117], iHS_pop=iHS$POP[117]),
    filter(gene.gff3, seqid==iHS$CHROM[118], start>=iHS$START[118] & end<=iHS$END[118]) |> mutate(iHS_start=iHS$START[118], iHS_end=iHS$END[118], iHS_pop=iHS$POP[118]),
    filter(gene.gff3, seqid==iHS$CHROM[119], start>=iHS$START[119] & end<=iHS$END[119]) |> mutate(iHS_start=iHS$START[119], iHS_end=iHS$END[119], iHS_pop=iHS$POP[119]),
    filter(gene.gff3, seqid==iHS$CHROM[120], start>=iHS$START[120] & end<=iHS$END[120]) |> mutate(iHS_start=iHS$START[120], iHS_end=iHS$END[120], iHS_pop=iHS$POP[120]),
    filter(gene.gff3, seqid==iHS$CHROM[121], start>=iHS$START[121] & end<=iHS$END[121]) |> mutate(iHS_start=iHS$START[121], iHS_end=iHS$END[121], iHS_pop=iHS$POP[121]),
    filter(gene.gff3, seqid==iHS$CHROM[122], start>=iHS$START[122] & end<=iHS$END[122]) |> mutate(iHS_start=iHS$START[122], iHS_end=iHS$END[122], iHS_pop=iHS$POP[122]),
    filter(gene.gff3, seqid==iHS$CHROM[123], start>=iHS$START[123] & end<=iHS$END[123]) |> mutate(iHS_start=iHS$START[123], iHS_end=iHS$END[123], iHS_pop=iHS$POP[123]),
    filter(gene.gff3, seqid==iHS$CHROM[124], start>=iHS$START[124] & end<=iHS$END[124]) |> mutate(iHS_start=iHS$START[124], iHS_end=iHS$END[124], iHS_pop=iHS$POP[124]),
    .id="outlier")
genes.within.regions

genes.starting.in.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==iHS$CHROM[1], between(start, left=iHS$START[1], right=iHS$END[1])) |> mutate(iHS_start=iHS$START[1], iHS_end=iHS$END[1], iHS_pop=iHS$POP[1]),
    filter(gene.gff3, seqid==iHS$CHROM[2], between(start, left=iHS$START[2], right=iHS$END[2])) |> mutate(iHS_start=iHS$START[2], iHS_end=iHS$END[2], iHS_pop=iHS$POP[2]),
    filter(gene.gff3, seqid==iHS$CHROM[3], between(start, left=iHS$START[3], right=iHS$END[3])) |> mutate(iHS_start=iHS$START[3], iHS_end=iHS$END[3], iHS_pop=iHS$POP[3]),
    filter(gene.gff3, seqid==iHS$CHROM[4], between(start, left=iHS$START[4], right=iHS$END[4])) |> mutate(iHS_start=iHS$START[4], iHS_end=iHS$END[4], iHS_pop=iHS$POP[4]),
    filter(gene.gff3, seqid==iHS$CHROM[5], between(start, left=iHS$START[5], right=iHS$END[5])) |> mutate(iHS_start=iHS$START[5], iHS_end=iHS$END[5], iHS_pop=iHS$POP[5]),
    filter(gene.gff3, seqid==iHS$CHROM[6], between(start, left=iHS$START[6], right=iHS$END[6])) |> mutate(iHS_start=iHS$START[6], iHS_end=iHS$END[6], iHS_pop=iHS$POP[6]),
    filter(gene.gff3, seqid==iHS$CHROM[7], between(start, left=iHS$START[7], right=iHS$END[7])) |> mutate(iHS_start=iHS$START[7], iHS_end=iHS$END[7], iHS_pop=iHS$POP[7]),
    filter(gene.gff3, seqid==iHS$CHROM[8], between(start, left=iHS$START[8], right=iHS$END[8])) |> mutate(iHS_start=iHS$START[8], iHS_end=iHS$END[8], iHS_pop=iHS$POP[8]),
    filter(gene.gff3, seqid==iHS$CHROM[9], between(start, left=iHS$START[9], right=iHS$END[9])) |> mutate(iHS_start=iHS$START[9], iHS_end=iHS$END[9], iHS_pop=iHS$POP[9]),
    filter(gene.gff3, seqid==iHS$CHROM[10], between(start, left=iHS$START[10], right=iHS$END[10])) |> mutate(iHS_start=iHS$START[10], iHS_end=iHS$END[10], iHS_pop=iHS$POP[10]),
    filter(gene.gff3, seqid==iHS$CHROM[11], between(start, left=iHS$START[11], right=iHS$END[11])) |> mutate(iHS_start=iHS$START[11], iHS_end=iHS$END[11], iHS_pop=iHS$POP[11]),
    filter(gene.gff3, seqid==iHS$CHROM[12], between(start, left=iHS$START[12], right=iHS$END[12])) |> mutate(iHS_start=iHS$START[12], iHS_end=iHS$END[12], iHS_pop=iHS$POP[12]),
    filter(gene.gff3, seqid==iHS$CHROM[13], between(start, left=iHS$START[13], right=iHS$END[13])) |> mutate(iHS_start=iHS$START[13], iHS_end=iHS$END[13], iHS_pop=iHS$POP[13]),
    filter(gene.gff3, seqid==iHS$CHROM[14], between(start, left=iHS$START[14], right=iHS$END[14])) |> mutate(iHS_start=iHS$START[14], iHS_end=iHS$END[14], iHS_pop=iHS$POP[14]),
    filter(gene.gff3, seqid==iHS$CHROM[15], between(start, left=iHS$START[15], right=iHS$END[15])) |> mutate(iHS_start=iHS$START[15], iHS_end=iHS$END[15], iHS_pop=iHS$POP[15]),
    filter(gene.gff3, seqid==iHS$CHROM[16], between(start, left=iHS$START[16], right=iHS$END[16])) |> mutate(iHS_start=iHS$START[16], iHS_end=iHS$END[16], iHS_pop=iHS$POP[16]),
    filter(gene.gff3, seqid==iHS$CHROM[17], between(start, left=iHS$START[17], right=iHS$END[17])) |> mutate(iHS_start=iHS$START[17], iHS_end=iHS$END[17], iHS_pop=iHS$POP[17]),
    filter(gene.gff3, seqid==iHS$CHROM[18], between(start, left=iHS$START[18], right=iHS$END[18])) |> mutate(iHS_start=iHS$START[18], iHS_end=iHS$END[18], iHS_pop=iHS$POP[18]),
    filter(gene.gff3, seqid==iHS$CHROM[19], between(start, left=iHS$START[19], right=iHS$END[19])) |> mutate(iHS_start=iHS$START[19], iHS_end=iHS$END[19], iHS_pop=iHS$POP[19]),
    filter(gene.gff3, seqid==iHS$CHROM[20], between(start, left=iHS$START[20], right=iHS$END[20])) |> mutate(iHS_start=iHS$START[20], iHS_end=iHS$END[20], iHS_pop=iHS$POP[20]),
    filter(gene.gff3, seqid==iHS$CHROM[21], between(start, left=iHS$START[21], right=iHS$END[21])) |> mutate(iHS_start=iHS$START[21], iHS_end=iHS$END[21], iHS_pop=iHS$POP[21]),
    filter(gene.gff3, seqid==iHS$CHROM[22], between(start, left=iHS$START[22], right=iHS$END[22])) |> mutate(iHS_start=iHS$START[22], iHS_end=iHS$END[22], iHS_pop=iHS$POP[22]),
    filter(gene.gff3, seqid==iHS$CHROM[23], between(start, left=iHS$START[23], right=iHS$END[23])) |> mutate(iHS_start=iHS$START[23], iHS_end=iHS$END[23], iHS_pop=iHS$POP[23]),
    filter(gene.gff3, seqid==iHS$CHROM[24], between(start, left=iHS$START[24], right=iHS$END[24])) |> mutate(iHS_start=iHS$START[24], iHS_end=iHS$END[24], iHS_pop=iHS$POP[24]),
    filter(gene.gff3, seqid==iHS$CHROM[25], between(start, left=iHS$START[25], right=iHS$END[25])) |> mutate(iHS_start=iHS$START[25], iHS_end=iHS$END[25], iHS_pop=iHS$POP[25]),
    filter(gene.gff3, seqid==iHS$CHROM[26], between(start, left=iHS$START[26], right=iHS$END[26])) |> mutate(iHS_start=iHS$START[26], iHS_end=iHS$END[26], iHS_pop=iHS$POP[26]),
    filter(gene.gff3, seqid==iHS$CHROM[27], between(start, left=iHS$START[27], right=iHS$END[27])) |> mutate(iHS_start=iHS$START[27], iHS_end=iHS$END[27], iHS_pop=iHS$POP[27]),
    filter(gene.gff3, seqid==iHS$CHROM[28], between(start, left=iHS$START[28], right=iHS$END[28])) |> mutate(iHS_start=iHS$START[28], iHS_end=iHS$END[28], iHS_pop=iHS$POP[28]),
    filter(gene.gff3, seqid==iHS$CHROM[29], between(start, left=iHS$START[29], right=iHS$END[29])) |> mutate(iHS_start=iHS$START[29], iHS_end=iHS$END[29], iHS_pop=iHS$POP[29]),
    filter(gene.gff3, seqid==iHS$CHROM[30], between(start, left=iHS$START[30], right=iHS$END[30])) |> mutate(iHS_start=iHS$START[30], iHS_end=iHS$END[30], iHS_pop=iHS$POP[30]),
    filter(gene.gff3, seqid==iHS$CHROM[31], between(start, left=iHS$START[31], right=iHS$END[31])) |> mutate(iHS_start=iHS$START[31], iHS_end=iHS$END[31], iHS_pop=iHS$POP[31]),
    filter(gene.gff3, seqid==iHS$CHROM[32], between(start, left=iHS$START[32], right=iHS$END[32])) |> mutate(iHS_start=iHS$START[32], iHS_end=iHS$END[32], iHS_pop=iHS$POP[32]),
    filter(gene.gff3, seqid==iHS$CHROM[33], between(start, left=iHS$START[33], right=iHS$END[33])) |> mutate(iHS_start=iHS$START[33], iHS_end=iHS$END[33], iHS_pop=iHS$POP[33]),
    filter(gene.gff3, seqid==iHS$CHROM[34], between(start, left=iHS$START[34], right=iHS$END[34])) |> mutate(iHS_start=iHS$START[34], iHS_end=iHS$END[34], iHS_pop=iHS$POP[34]),
    filter(gene.gff3, seqid==iHS$CHROM[35], between(start, left=iHS$START[35], right=iHS$END[35])) |> mutate(iHS_start=iHS$START[35], iHS_end=iHS$END[35], iHS_pop=iHS$POP[35]),
    filter(gene.gff3, seqid==iHS$CHROM[36], between(start, left=iHS$START[36], right=iHS$END[36])) |> mutate(iHS_start=iHS$START[36], iHS_end=iHS$END[36], iHS_pop=iHS$POP[36]),
    filter(gene.gff3, seqid==iHS$CHROM[37], between(start, left=iHS$START[37], right=iHS$END[37])) |> mutate(iHS_start=iHS$START[37], iHS_end=iHS$END[37], iHS_pop=iHS$POP[37]),
    filter(gene.gff3, seqid==iHS$CHROM[38], between(start, left=iHS$START[38], right=iHS$END[38])) |> mutate(iHS_start=iHS$START[38], iHS_end=iHS$END[38], iHS_pop=iHS$POP[38]),
    filter(gene.gff3, seqid==iHS$CHROM[39], between(start, left=iHS$START[39], right=iHS$END[39])) |> mutate(iHS_start=iHS$START[39], iHS_end=iHS$END[39], iHS_pop=iHS$POP[39]),
    filter(gene.gff3, seqid==iHS$CHROM[40], between(start, left=iHS$START[40], right=iHS$END[40])) |> mutate(iHS_start=iHS$START[40], iHS_end=iHS$END[40], iHS_pop=iHS$POP[40]),
    filter(gene.gff3, seqid==iHS$CHROM[41], between(start, left=iHS$START[41], right=iHS$END[41])) |> mutate(iHS_start=iHS$START[41], iHS_end=iHS$END[41], iHS_pop=iHS$POP[41]),
    filter(gene.gff3, seqid==iHS$CHROM[42], between(start, left=iHS$START[42], right=iHS$END[42])) |> mutate(iHS_start=iHS$START[42], iHS_end=iHS$END[42], iHS_pop=iHS$POP[42]),
    filter(gene.gff3, seqid==iHS$CHROM[43], between(start, left=iHS$START[43], right=iHS$END[43])) |> mutate(iHS_start=iHS$START[43], iHS_end=iHS$END[43], iHS_pop=iHS$POP[43]),
    filter(gene.gff3, seqid==iHS$CHROM[44], between(start, left=iHS$START[44], right=iHS$END[44])) |> mutate(iHS_start=iHS$START[44], iHS_end=iHS$END[44], iHS_pop=iHS$POP[44]),
    filter(gene.gff3, seqid==iHS$CHROM[45], between(start, left=iHS$START[45], right=iHS$END[45])) |> mutate(iHS_start=iHS$START[45], iHS_end=iHS$END[45], iHS_pop=iHS$POP[45]),
    filter(gene.gff3, seqid==iHS$CHROM[46], between(start, left=iHS$START[46], right=iHS$END[46])) |> mutate(iHS_start=iHS$START[46], iHS_end=iHS$END[46], iHS_pop=iHS$POP[46]),
    filter(gene.gff3, seqid==iHS$CHROM[47], between(start, left=iHS$START[47], right=iHS$END[47])) |> mutate(iHS_start=iHS$START[47], iHS_end=iHS$END[47], iHS_pop=iHS$POP[47]),
    filter(gene.gff3, seqid==iHS$CHROM[48], between(start, left=iHS$START[48], right=iHS$END[48])) |> mutate(iHS_start=iHS$START[48], iHS_end=iHS$END[48], iHS_pop=iHS$POP[48]),
    filter(gene.gff3, seqid==iHS$CHROM[49], between(start, left=iHS$START[49], right=iHS$END[49])) |> mutate(iHS_start=iHS$START[49], iHS_end=iHS$END[49], iHS_pop=iHS$POP[49]),
    filter(gene.gff3, seqid==iHS$CHROM[50], between(start, left=iHS$START[50], right=iHS$END[50])) |> mutate(iHS_start=iHS$START[50], iHS_end=iHS$END[50], iHS_pop=iHS$POP[50]),
    filter(gene.gff3, seqid==iHS$CHROM[51], between(start, left=iHS$START[51], right=iHS$END[51])) |> mutate(iHS_start=iHS$START[51], iHS_end=iHS$END[51], iHS_pop=iHS$POP[51]),
    filter(gene.gff3, seqid==iHS$CHROM[52], between(start, left=iHS$START[52], right=iHS$END[52])) |> mutate(iHS_start=iHS$START[52], iHS_end=iHS$END[52], iHS_pop=iHS$POP[52]),
    filter(gene.gff3, seqid==iHS$CHROM[53], between(start, left=iHS$START[53], right=iHS$END[53])) |> mutate(iHS_start=iHS$START[53], iHS_end=iHS$END[53], iHS_pop=iHS$POP[53]),
    filter(gene.gff3, seqid==iHS$CHROM[54], between(start, left=iHS$START[54], right=iHS$END[54])) |> mutate(iHS_start=iHS$START[54], iHS_end=iHS$END[54], iHS_pop=iHS$POP[54]),
    filter(gene.gff3, seqid==iHS$CHROM[55], between(start, left=iHS$START[55], right=iHS$END[55])) |> mutate(iHS_start=iHS$START[55], iHS_end=iHS$END[55], iHS_pop=iHS$POP[55]),
    filter(gene.gff3, seqid==iHS$CHROM[56], between(start, left=iHS$START[56], right=iHS$END[56])) |> mutate(iHS_start=iHS$START[56], iHS_end=iHS$END[56], iHS_pop=iHS$POP[56]),
    filter(gene.gff3, seqid==iHS$CHROM[57], between(start, left=iHS$START[57], right=iHS$END[57])) |> mutate(iHS_start=iHS$START[57], iHS_end=iHS$END[57], iHS_pop=iHS$POP[57]),
    filter(gene.gff3, seqid==iHS$CHROM[58], between(start, left=iHS$START[58], right=iHS$END[58])) |> mutate(iHS_start=iHS$START[58], iHS_end=iHS$END[58], iHS_pop=iHS$POP[58]),
    filter(gene.gff3, seqid==iHS$CHROM[59], between(start, left=iHS$START[59], right=iHS$END[59])) |> mutate(iHS_start=iHS$START[59], iHS_end=iHS$END[59], iHS_pop=iHS$POP[59]),
    filter(gene.gff3, seqid==iHS$CHROM[60], between(start, left=iHS$START[60], right=iHS$END[60])) |> mutate(iHS_start=iHS$START[60], iHS_end=iHS$END[60], iHS_pop=iHS$POP[60]),
    filter(gene.gff3, seqid==iHS$CHROM[61], between(start, left=iHS$START[61], right=iHS$END[61])) |> mutate(iHS_start=iHS$START[61], iHS_end=iHS$END[61], iHS_pop=iHS$POP[61]),
    filter(gene.gff3, seqid==iHS$CHROM[62], between(start, left=iHS$START[62], right=iHS$END[62])) |> mutate(iHS_start=iHS$START[62], iHS_end=iHS$END[62], iHS_pop=iHS$POP[62]),
    filter(gene.gff3, seqid==iHS$CHROM[63], between(start, left=iHS$START[63], right=iHS$END[63])) |> mutate(iHS_start=iHS$START[63], iHS_end=iHS$END[63], iHS_pop=iHS$POP[63]),
    filter(gene.gff3, seqid==iHS$CHROM[64], between(start, left=iHS$START[64], right=iHS$END[64])) |> mutate(iHS_start=iHS$START[64], iHS_end=iHS$END[64], iHS_pop=iHS$POP[64]),
    filter(gene.gff3, seqid==iHS$CHROM[65], between(start, left=iHS$START[65], right=iHS$END[65])) |> mutate(iHS_start=iHS$START[65], iHS_end=iHS$END[65], iHS_pop=iHS$POP[65]),
    filter(gene.gff3, seqid==iHS$CHROM[66], between(start, left=iHS$START[66], right=iHS$END[66])) |> mutate(iHS_start=iHS$START[66], iHS_end=iHS$END[66], iHS_pop=iHS$POP[66]),
    filter(gene.gff3, seqid==iHS$CHROM[67], between(start, left=iHS$START[67], right=iHS$END[67])) |> mutate(iHS_start=iHS$START[67], iHS_end=iHS$END[67], iHS_pop=iHS$POP[67]),
    filter(gene.gff3, seqid==iHS$CHROM[68], between(start, left=iHS$START[68], right=iHS$END[68])) |> mutate(iHS_start=iHS$START[68], iHS_end=iHS$END[68], iHS_pop=iHS$POP[68]),
    filter(gene.gff3, seqid==iHS$CHROM[69], between(start, left=iHS$START[69], right=iHS$END[69])) |> mutate(iHS_start=iHS$START[69], iHS_end=iHS$END[69], iHS_pop=iHS$POP[69]),
    filter(gene.gff3, seqid==iHS$CHROM[70], between(start, left=iHS$START[70], right=iHS$END[70])) |> mutate(iHS_start=iHS$START[70], iHS_end=iHS$END[70], iHS_pop=iHS$POP[70]),
    filter(gene.gff3, seqid==iHS$CHROM[71], between(start, left=iHS$START[71], right=iHS$END[71])) |> mutate(iHS_start=iHS$START[71], iHS_end=iHS$END[71], iHS_pop=iHS$POP[71]),
    filter(gene.gff3, seqid==iHS$CHROM[72], between(start, left=iHS$START[72], right=iHS$END[72])) |> mutate(iHS_start=iHS$START[72], iHS_end=iHS$END[72], iHS_pop=iHS$POP[72]),
    filter(gene.gff3, seqid==iHS$CHROM[73], between(start, left=iHS$START[73], right=iHS$END[73])) |> mutate(iHS_start=iHS$START[73], iHS_end=iHS$END[73], iHS_pop=iHS$POP[73]),
    filter(gene.gff3, seqid==iHS$CHROM[74], between(start, left=iHS$START[74], right=iHS$END[74])) |> mutate(iHS_start=iHS$START[74], iHS_end=iHS$END[74], iHS_pop=iHS$POP[74]),
    filter(gene.gff3, seqid==iHS$CHROM[75], between(start, left=iHS$START[75], right=iHS$END[75])) |> mutate(iHS_start=iHS$START[75], iHS_end=iHS$END[75], iHS_pop=iHS$POP[75]),
    filter(gene.gff3, seqid==iHS$CHROM[76], between(start, left=iHS$START[76], right=iHS$END[76])) |> mutate(iHS_start=iHS$START[76], iHS_end=iHS$END[76], iHS_pop=iHS$POP[76]),
    filter(gene.gff3, seqid==iHS$CHROM[77], between(start, left=iHS$START[77], right=iHS$END[77])) |> mutate(iHS_start=iHS$START[77], iHS_end=iHS$END[77], iHS_pop=iHS$POP[77]),
    filter(gene.gff3, seqid==iHS$CHROM[78], between(start, left=iHS$START[78], right=iHS$END[78])) |> mutate(iHS_start=iHS$START[78], iHS_end=iHS$END[78], iHS_pop=iHS$POP[78]),
    filter(gene.gff3, seqid==iHS$CHROM[79], between(start, left=iHS$START[79], right=iHS$END[79])) |> mutate(iHS_start=iHS$START[79], iHS_end=iHS$END[79], iHS_pop=iHS$POP[79]),
    filter(gene.gff3, seqid==iHS$CHROM[80], between(start, left=iHS$START[80], right=iHS$END[80])) |> mutate(iHS_start=iHS$START[80], iHS_end=iHS$END[80], iHS_pop=iHS$POP[80]),
    filter(gene.gff3, seqid==iHS$CHROM[81], between(start, left=iHS$START[81], right=iHS$END[81])) |> mutate(iHS_start=iHS$START[81], iHS_end=iHS$END[81], iHS_pop=iHS$POP[81]),
    filter(gene.gff3, seqid==iHS$CHROM[82], between(start, left=iHS$START[82], right=iHS$END[82])) |> mutate(iHS_start=iHS$START[82], iHS_end=iHS$END[82], iHS_pop=iHS$POP[82]),
    filter(gene.gff3, seqid==iHS$CHROM[83], between(start, left=iHS$START[83], right=iHS$END[83])) |> mutate(iHS_start=iHS$START[83], iHS_end=iHS$END[83], iHS_pop=iHS$POP[83]),
    filter(gene.gff3, seqid==iHS$CHROM[84], between(start, left=iHS$START[84], right=iHS$END[84])) |> mutate(iHS_start=iHS$START[84], iHS_end=iHS$END[84], iHS_pop=iHS$POP[84]),
    filter(gene.gff3, seqid==iHS$CHROM[85], between(start, left=iHS$START[85], right=iHS$END[85])) |> mutate(iHS_start=iHS$START[85], iHS_end=iHS$END[85], iHS_pop=iHS$POP[85]),
    filter(gene.gff3, seqid==iHS$CHROM[86], between(start, left=iHS$START[86], right=iHS$END[86])) |> mutate(iHS_start=iHS$START[86], iHS_end=iHS$END[86], iHS_pop=iHS$POP[86]),
    filter(gene.gff3, seqid==iHS$CHROM[87], between(start, left=iHS$START[87], right=iHS$END[87])) |> mutate(iHS_start=iHS$START[87], iHS_end=iHS$END[87], iHS_pop=iHS$POP[87]),
    filter(gene.gff3, seqid==iHS$CHROM[88], between(start, left=iHS$START[88], right=iHS$END[88])) |> mutate(iHS_start=iHS$START[88], iHS_end=iHS$END[88], iHS_pop=iHS$POP[88]),
    filter(gene.gff3, seqid==iHS$CHROM[89], between(start, left=iHS$START[89], right=iHS$END[89])) |> mutate(iHS_start=iHS$START[89], iHS_end=iHS$END[89], iHS_pop=iHS$POP[89]),
    filter(gene.gff3, seqid==iHS$CHROM[90], between(start, left=iHS$START[90], right=iHS$END[90])) |> mutate(iHS_start=iHS$START[90], iHS_end=iHS$END[90], iHS_pop=iHS$POP[90]),
    filter(gene.gff3, seqid==iHS$CHROM[91], between(start, left=iHS$START[91], right=iHS$END[91])) |> mutate(iHS_start=iHS$START[91], iHS_end=iHS$END[91], iHS_pop=iHS$POP[91]),
    filter(gene.gff3, seqid==iHS$CHROM[92], between(start, left=iHS$START[92], right=iHS$END[92])) |> mutate(iHS_start=iHS$START[92], iHS_end=iHS$END[92], iHS_pop=iHS$POP[92]),
    filter(gene.gff3, seqid==iHS$CHROM[93], between(start, left=iHS$START[93], right=iHS$END[93])) |> mutate(iHS_start=iHS$START[93], iHS_end=iHS$END[93], iHS_pop=iHS$POP[93]),
    filter(gene.gff3, seqid==iHS$CHROM[94], between(start, left=iHS$START[94], right=iHS$END[94])) |> mutate(iHS_start=iHS$START[94], iHS_end=iHS$END[94], iHS_pop=iHS$POP[94]),
    filter(gene.gff3, seqid==iHS$CHROM[95], between(start, left=iHS$START[95], right=iHS$END[95])) |> mutate(iHS_start=iHS$START[95], iHS_end=iHS$END[95], iHS_pop=iHS$POP[95]),
    filter(gene.gff3, seqid==iHS$CHROM[96], between(start, left=iHS$START[96], right=iHS$END[96])) |> mutate(iHS_start=iHS$START[96], iHS_end=iHS$END[96], iHS_pop=iHS$POP[96]),
    filter(gene.gff3, seqid==iHS$CHROM[97], between(start, left=iHS$START[97], right=iHS$END[97])) |> mutate(iHS_start=iHS$START[97], iHS_end=iHS$END[97], iHS_pop=iHS$POP[97]),
    filter(gene.gff3, seqid==iHS$CHROM[98], between(start, left=iHS$START[98], right=iHS$END[98])) |> mutate(iHS_start=iHS$START[98], iHS_end=iHS$END[98], iHS_pop=iHS$POP[98]),
    filter(gene.gff3, seqid==iHS$CHROM[99], between(start, left=iHS$START[99], right=iHS$END[99])) |> mutate(iHS_start=iHS$START[99], iHS_end=iHS$END[99], iHS_pop=iHS$POP[99]),
    filter(gene.gff3, seqid==iHS$CHROM[100], between(start, left=iHS$START[100], right=iHS$END[100])) |> mutate(iHS_start=iHS$START[100], iHS_end=iHS$END[100], iHS_pop=iHS$POP[100]),
    filter(gene.gff3, seqid==iHS$CHROM[101], between(start, left=iHS$START[101], right=iHS$END[101])) |> mutate(iHS_start=iHS$START[101], iHS_end=iHS$END[101], iHS_pop=iHS$POP[101]),
    filter(gene.gff3, seqid==iHS$CHROM[102], between(start, left=iHS$START[102], right=iHS$END[102])) |> mutate(iHS_start=iHS$START[102], iHS_end=iHS$END[102], iHS_pop=iHS$POP[102]),
    filter(gene.gff3, seqid==iHS$CHROM[103], between(start, left=iHS$START[103], right=iHS$END[103])) |> mutate(iHS_start=iHS$START[103], iHS_end=iHS$END[103], iHS_pop=iHS$POP[103]),
    filter(gene.gff3, seqid==iHS$CHROM[104], between(start, left=iHS$START[104], right=iHS$END[104])) |> mutate(iHS_start=iHS$START[104], iHS_end=iHS$END[104], iHS_pop=iHS$POP[104]),
    filter(gene.gff3, seqid==iHS$CHROM[105], between(start, left=iHS$START[105], right=iHS$END[105])) |> mutate(iHS_start=iHS$START[105], iHS_end=iHS$END[105], iHS_pop=iHS$POP[105]),
    filter(gene.gff3, seqid==iHS$CHROM[106], between(start, left=iHS$START[106], right=iHS$END[106])) |> mutate(iHS_start=iHS$START[106], iHS_end=iHS$END[106], iHS_pop=iHS$POP[106]),
    filter(gene.gff3, seqid==iHS$CHROM[107], between(start, left=iHS$START[107], right=iHS$END[107])) |> mutate(iHS_start=iHS$START[107], iHS_end=iHS$END[107], iHS_pop=iHS$POP[107]),
    filter(gene.gff3, seqid==iHS$CHROM[108], between(start, left=iHS$START[108], right=iHS$END[108])) |> mutate(iHS_start=iHS$START[108], iHS_end=iHS$END[108], iHS_pop=iHS$POP[108]),
    filter(gene.gff3, seqid==iHS$CHROM[109], between(start, left=iHS$START[109], right=iHS$END[109])) |> mutate(iHS_start=iHS$START[109], iHS_end=iHS$END[109], iHS_pop=iHS$POP[109]),
    filter(gene.gff3, seqid==iHS$CHROM[110], between(start, left=iHS$START[110], right=iHS$END[110])) |> mutate(iHS_start=iHS$START[110], iHS_end=iHS$END[110], iHS_pop=iHS$POP[110]),
    filter(gene.gff3, seqid==iHS$CHROM[111], between(start, left=iHS$START[111], right=iHS$END[111])) |> mutate(iHS_start=iHS$START[111], iHS_end=iHS$END[111], iHS_pop=iHS$POP[111]),
    filter(gene.gff3, seqid==iHS$CHROM[112], between(start, left=iHS$START[112], right=iHS$END[112])) |> mutate(iHS_start=iHS$START[112], iHS_end=iHS$END[112], iHS_pop=iHS$POP[112]),
    filter(gene.gff3, seqid==iHS$CHROM[113], between(start, left=iHS$START[113], right=iHS$END[113])) |> mutate(iHS_start=iHS$START[113], iHS_end=iHS$END[113], iHS_pop=iHS$POP[113]),
    filter(gene.gff3, seqid==iHS$CHROM[114], between(start, left=iHS$START[114], right=iHS$END[114])) |> mutate(iHS_start=iHS$START[114], iHS_end=iHS$END[114], iHS_pop=iHS$POP[114]),
    filter(gene.gff3, seqid==iHS$CHROM[115], between(start, left=iHS$START[115], right=iHS$END[115])) |> mutate(iHS_start=iHS$START[115], iHS_end=iHS$END[115], iHS_pop=iHS$POP[115]),
    filter(gene.gff3, seqid==iHS$CHROM[116], between(start, left=iHS$START[116], right=iHS$END[116])) |> mutate(iHS_start=iHS$START[116], iHS_end=iHS$END[116], iHS_pop=iHS$POP[116]),
    filter(gene.gff3, seqid==iHS$CHROM[117], between(start, left=iHS$START[117], right=iHS$END[117])) |> mutate(iHS_start=iHS$START[117], iHS_end=iHS$END[117], iHS_pop=iHS$POP[117]),
    filter(gene.gff3, seqid==iHS$CHROM[118], between(start, left=iHS$START[118], right=iHS$END[118])) |> mutate(iHS_start=iHS$START[118], iHS_end=iHS$END[118], iHS_pop=iHS$POP[118]),
    filter(gene.gff3, seqid==iHS$CHROM[119], between(start, left=iHS$START[119], right=iHS$END[119])) |> mutate(iHS_start=iHS$START[119], iHS_end=iHS$END[119], iHS_pop=iHS$POP[119]),
    filter(gene.gff3, seqid==iHS$CHROM[120], between(start, left=iHS$START[120], right=iHS$END[120])) |> mutate(iHS_start=iHS$START[120], iHS_end=iHS$END[120], iHS_pop=iHS$POP[120]),
    filter(gene.gff3, seqid==iHS$CHROM[121], between(start, left=iHS$START[121], right=iHS$END[121])) |> mutate(iHS_start=iHS$START[121], iHS_end=iHS$END[121], iHS_pop=iHS$POP[121]),
    filter(gene.gff3, seqid==iHS$CHROM[122], between(start, left=iHS$START[122], right=iHS$END[122])) |> mutate(iHS_start=iHS$START[122], iHS_end=iHS$END[122], iHS_pop=iHS$POP[122]),
    filter(gene.gff3, seqid==iHS$CHROM[123], between(start, left=iHS$START[123], right=iHS$END[123])) |> mutate(iHS_start=iHS$START[123], iHS_end=iHS$END[123], iHS_pop=iHS$POP[123]),
    filter(gene.gff3, seqid==iHS$CHROM[124], between(start, left=iHS$START[124], right=iHS$END[124])) |> mutate(iHS_start=iHS$START[124], iHS_end=iHS$END[124], iHS_pop=iHS$POP[124]),
    .id="outlier")
genes.starting.in.regions

genes.ending.in.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==iHS$CHROM[1], between(end, left=iHS$START[1], right=iHS$END[1])) |> mutate(iHS_start=iHS$START[1], iHS_end=iHS$END[1], iHS_pop=iHS$POP[1]),
    filter(gene.gff3, seqid==iHS$CHROM[2], between(end, left=iHS$START[2], right=iHS$END[2])) |> mutate(iHS_start=iHS$START[2], iHS_end=iHS$END[2], iHS_pop=iHS$POP[2]),
    filter(gene.gff3, seqid==iHS$CHROM[3], between(end, left=iHS$START[3], right=iHS$END[3])) |> mutate(iHS_start=iHS$START[3], iHS_end=iHS$END[3], iHS_pop=iHS$POP[3]),
    filter(gene.gff3, seqid==iHS$CHROM[4], between(end, left=iHS$START[4], right=iHS$END[4])) |> mutate(iHS_start=iHS$START[4], iHS_end=iHS$END[4], iHS_pop=iHS$POP[4]),
    filter(gene.gff3, seqid==iHS$CHROM[5], between(end, left=iHS$START[5], right=iHS$END[5])) |> mutate(iHS_start=iHS$START[5], iHS_end=iHS$END[5], iHS_pop=iHS$POP[5]),
    filter(gene.gff3, seqid==iHS$CHROM[6], between(end, left=iHS$START[6], right=iHS$END[6])) |> mutate(iHS_start=iHS$START[6], iHS_end=iHS$END[6], iHS_pop=iHS$POP[6]),
    filter(gene.gff3, seqid==iHS$CHROM[7], between(end, left=iHS$START[7], right=iHS$END[7])) |> mutate(iHS_start=iHS$START[7], iHS_end=iHS$END[7], iHS_pop=iHS$POP[7]),
    filter(gene.gff3, seqid==iHS$CHROM[8], between(end, left=iHS$START[8], right=iHS$END[8])) |> mutate(iHS_start=iHS$START[8], iHS_end=iHS$END[8], iHS_pop=iHS$POP[8]),
    filter(gene.gff3, seqid==iHS$CHROM[9], between(end, left=iHS$START[9], right=iHS$END[9])) |> mutate(iHS_start=iHS$START[9], iHS_end=iHS$END[9], iHS_pop=iHS$POP[9]),
    filter(gene.gff3, seqid==iHS$CHROM[10], between(end, left=iHS$START[10], right=iHS$END[10])) |> mutate(iHS_start=iHS$START[10], iHS_end=iHS$END[10], iHS_pop=iHS$POP[10]),
    filter(gene.gff3, seqid==iHS$CHROM[11], between(end, left=iHS$START[11], right=iHS$END[11])) |> mutate(iHS_start=iHS$START[11], iHS_end=iHS$END[11], iHS_pop=iHS$POP[11]),
    filter(gene.gff3, seqid==iHS$CHROM[12], between(end, left=iHS$START[12], right=iHS$END[12])) |> mutate(iHS_start=iHS$START[12], iHS_end=iHS$END[12], iHS_pop=iHS$POP[12]),
    filter(gene.gff3, seqid==iHS$CHROM[13], between(end, left=iHS$START[13], right=iHS$END[13])) |> mutate(iHS_start=iHS$START[13], iHS_end=iHS$END[13], iHS_pop=iHS$POP[13]),
    filter(gene.gff3, seqid==iHS$CHROM[14], between(end, left=iHS$START[14], right=iHS$END[14])) |> mutate(iHS_start=iHS$START[14], iHS_end=iHS$END[14], iHS_pop=iHS$POP[14]),
    filter(gene.gff3, seqid==iHS$CHROM[15], between(end, left=iHS$START[15], right=iHS$END[15])) |> mutate(iHS_start=iHS$START[15], iHS_end=iHS$END[15], iHS_pop=iHS$POP[15]),
    filter(gene.gff3, seqid==iHS$CHROM[16], between(end, left=iHS$START[16], right=iHS$END[16])) |> mutate(iHS_start=iHS$START[16], iHS_end=iHS$END[16], iHS_pop=iHS$POP[16]),
    filter(gene.gff3, seqid==iHS$CHROM[17], between(end, left=iHS$START[17], right=iHS$END[17])) |> mutate(iHS_start=iHS$START[17], iHS_end=iHS$END[17], iHS_pop=iHS$POP[17]),
    filter(gene.gff3, seqid==iHS$CHROM[18], between(end, left=iHS$START[18], right=iHS$END[18])) |> mutate(iHS_start=iHS$START[18], iHS_end=iHS$END[18], iHS_pop=iHS$POP[18]),
    filter(gene.gff3, seqid==iHS$CHROM[19], between(end, left=iHS$START[19], right=iHS$END[19])) |> mutate(iHS_start=iHS$START[19], iHS_end=iHS$END[19], iHS_pop=iHS$POP[19]),
    filter(gene.gff3, seqid==iHS$CHROM[20], between(end, left=iHS$START[20], right=iHS$END[20])) |> mutate(iHS_start=iHS$START[20], iHS_end=iHS$END[20], iHS_pop=iHS$POP[20]),
    filter(gene.gff3, seqid==iHS$CHROM[21], between(end, left=iHS$START[21], right=iHS$END[21])) |> mutate(iHS_start=iHS$START[21], iHS_end=iHS$END[21], iHS_pop=iHS$POP[21]),
    filter(gene.gff3, seqid==iHS$CHROM[22], between(end, left=iHS$START[22], right=iHS$END[22])) |> mutate(iHS_start=iHS$START[22], iHS_end=iHS$END[22], iHS_pop=iHS$POP[22]),
    filter(gene.gff3, seqid==iHS$CHROM[23], between(end, left=iHS$START[23], right=iHS$END[23])) |> mutate(iHS_start=iHS$START[23], iHS_end=iHS$END[23], iHS_pop=iHS$POP[23]),
    filter(gene.gff3, seqid==iHS$CHROM[24], between(end, left=iHS$START[24], right=iHS$END[24])) |> mutate(iHS_start=iHS$START[24], iHS_end=iHS$END[24], iHS_pop=iHS$POP[24]),
    filter(gene.gff3, seqid==iHS$CHROM[25], between(end, left=iHS$START[25], right=iHS$END[25])) |> mutate(iHS_start=iHS$START[25], iHS_end=iHS$END[25], iHS_pop=iHS$POP[25]),
    filter(gene.gff3, seqid==iHS$CHROM[26], between(end, left=iHS$START[26], right=iHS$END[26])) |> mutate(iHS_start=iHS$START[26], iHS_end=iHS$END[26], iHS_pop=iHS$POP[26]),
    filter(gene.gff3, seqid==iHS$CHROM[27], between(end, left=iHS$START[27], right=iHS$END[27])) |> mutate(iHS_start=iHS$START[27], iHS_end=iHS$END[27], iHS_pop=iHS$POP[27]),
    filter(gene.gff3, seqid==iHS$CHROM[28], between(end, left=iHS$START[28], right=iHS$END[28])) |> mutate(iHS_start=iHS$START[28], iHS_end=iHS$END[28], iHS_pop=iHS$POP[28]),
    filter(gene.gff3, seqid==iHS$CHROM[29], between(end, left=iHS$START[29], right=iHS$END[29])) |> mutate(iHS_start=iHS$START[29], iHS_end=iHS$END[29], iHS_pop=iHS$POP[29]),
    filter(gene.gff3, seqid==iHS$CHROM[30], between(end, left=iHS$START[30], right=iHS$END[30])) |> mutate(iHS_start=iHS$START[30], iHS_end=iHS$END[30], iHS_pop=iHS$POP[30]),
    filter(gene.gff3, seqid==iHS$CHROM[31], between(end, left=iHS$START[31], right=iHS$END[31])) |> mutate(iHS_start=iHS$START[31], iHS_end=iHS$END[31], iHS_pop=iHS$POP[31]),
    filter(gene.gff3, seqid==iHS$CHROM[32], between(end, left=iHS$START[32], right=iHS$END[32])) |> mutate(iHS_start=iHS$START[32], iHS_end=iHS$END[32], iHS_pop=iHS$POP[32]),
    filter(gene.gff3, seqid==iHS$CHROM[33], between(end, left=iHS$START[33], right=iHS$END[33])) |> mutate(iHS_start=iHS$START[33], iHS_end=iHS$END[33], iHS_pop=iHS$POP[33]),
    filter(gene.gff3, seqid==iHS$CHROM[34], between(end, left=iHS$START[34], right=iHS$END[34])) |> mutate(iHS_start=iHS$START[34], iHS_end=iHS$END[34], iHS_pop=iHS$POP[34]),
    filter(gene.gff3, seqid==iHS$CHROM[35], between(end, left=iHS$START[35], right=iHS$END[35])) |> mutate(iHS_start=iHS$START[35], iHS_end=iHS$END[35], iHS_pop=iHS$POP[35]),
    filter(gene.gff3, seqid==iHS$CHROM[36], between(end, left=iHS$START[36], right=iHS$END[36])) |> mutate(iHS_start=iHS$START[36], iHS_end=iHS$END[36], iHS_pop=iHS$POP[36]),
    filter(gene.gff3, seqid==iHS$CHROM[37], between(end, left=iHS$START[37], right=iHS$END[37])) |> mutate(iHS_start=iHS$START[37], iHS_end=iHS$END[37], iHS_pop=iHS$POP[37]),
    filter(gene.gff3, seqid==iHS$CHROM[38], between(end, left=iHS$START[38], right=iHS$END[38])) |> mutate(iHS_start=iHS$START[38], iHS_end=iHS$END[38], iHS_pop=iHS$POP[38]),
    filter(gene.gff3, seqid==iHS$CHROM[39], between(end, left=iHS$START[39], right=iHS$END[39])) |> mutate(iHS_start=iHS$START[39], iHS_end=iHS$END[39], iHS_pop=iHS$POP[39]),
    filter(gene.gff3, seqid==iHS$CHROM[40], between(end, left=iHS$START[40], right=iHS$END[40])) |> mutate(iHS_start=iHS$START[40], iHS_end=iHS$END[40], iHS_pop=iHS$POP[40]),
    filter(gene.gff3, seqid==iHS$CHROM[41], between(end, left=iHS$START[41], right=iHS$END[41])) |> mutate(iHS_start=iHS$START[41], iHS_end=iHS$END[41], iHS_pop=iHS$POP[41]),
    filter(gene.gff3, seqid==iHS$CHROM[42], between(end, left=iHS$START[42], right=iHS$END[42])) |> mutate(iHS_start=iHS$START[42], iHS_end=iHS$END[42], iHS_pop=iHS$POP[42]),
    filter(gene.gff3, seqid==iHS$CHROM[43], between(end, left=iHS$START[43], right=iHS$END[43])) |> mutate(iHS_start=iHS$START[43], iHS_end=iHS$END[43], iHS_pop=iHS$POP[43]),
    filter(gene.gff3, seqid==iHS$CHROM[44], between(end, left=iHS$START[44], right=iHS$END[44])) |> mutate(iHS_start=iHS$START[44], iHS_end=iHS$END[44], iHS_pop=iHS$POP[44]),
    filter(gene.gff3, seqid==iHS$CHROM[45], between(end, left=iHS$START[45], right=iHS$END[45])) |> mutate(iHS_start=iHS$START[45], iHS_end=iHS$END[45], iHS_pop=iHS$POP[45]),
    filter(gene.gff3, seqid==iHS$CHROM[46], between(end, left=iHS$START[46], right=iHS$END[46])) |> mutate(iHS_start=iHS$START[46], iHS_end=iHS$END[46], iHS_pop=iHS$POP[46]),
    filter(gene.gff3, seqid==iHS$CHROM[47], between(end, left=iHS$START[47], right=iHS$END[47])) |> mutate(iHS_start=iHS$START[47], iHS_end=iHS$END[47], iHS_pop=iHS$POP[47]),
    filter(gene.gff3, seqid==iHS$CHROM[48], between(end, left=iHS$START[48], right=iHS$END[48])) |> mutate(iHS_start=iHS$START[48], iHS_end=iHS$END[48], iHS_pop=iHS$POP[48]),
    filter(gene.gff3, seqid==iHS$CHROM[49], between(end, left=iHS$START[49], right=iHS$END[49])) |> mutate(iHS_start=iHS$START[49], iHS_end=iHS$END[49], iHS_pop=iHS$POP[49]),
    filter(gene.gff3, seqid==iHS$CHROM[50], between(end, left=iHS$START[50], right=iHS$END[50])) |> mutate(iHS_start=iHS$START[50], iHS_end=iHS$END[50], iHS_pop=iHS$POP[50]),
    filter(gene.gff3, seqid==iHS$CHROM[51], between(end, left=iHS$START[51], right=iHS$END[51])) |> mutate(iHS_start=iHS$START[51], iHS_end=iHS$END[51], iHS_pop=iHS$POP[51]),
    filter(gene.gff3, seqid==iHS$CHROM[52], between(end, left=iHS$START[52], right=iHS$END[52])) |> mutate(iHS_start=iHS$START[52], iHS_end=iHS$END[52], iHS_pop=iHS$POP[52]),
    filter(gene.gff3, seqid==iHS$CHROM[53], between(end, left=iHS$START[53], right=iHS$END[53])) |> mutate(iHS_start=iHS$START[53], iHS_end=iHS$END[53], iHS_pop=iHS$POP[53]),
    filter(gene.gff3, seqid==iHS$CHROM[54], between(end, left=iHS$START[54], right=iHS$END[54])) |> mutate(iHS_start=iHS$START[54], iHS_end=iHS$END[54], iHS_pop=iHS$POP[54]),
    filter(gene.gff3, seqid==iHS$CHROM[55], between(end, left=iHS$START[55], right=iHS$END[55])) |> mutate(iHS_start=iHS$START[55], iHS_end=iHS$END[55], iHS_pop=iHS$POP[55]),
    filter(gene.gff3, seqid==iHS$CHROM[56], between(end, left=iHS$START[56], right=iHS$END[56])) |> mutate(iHS_start=iHS$START[56], iHS_end=iHS$END[56], iHS_pop=iHS$POP[56]),
    filter(gene.gff3, seqid==iHS$CHROM[57], between(end, left=iHS$START[57], right=iHS$END[57])) |> mutate(iHS_start=iHS$START[57], iHS_end=iHS$END[57], iHS_pop=iHS$POP[57]),
    filter(gene.gff3, seqid==iHS$CHROM[58], between(end, left=iHS$START[58], right=iHS$END[58])) |> mutate(iHS_start=iHS$START[58], iHS_end=iHS$END[58], iHS_pop=iHS$POP[58]),
    filter(gene.gff3, seqid==iHS$CHROM[59], between(end, left=iHS$START[59], right=iHS$END[59])) |> mutate(iHS_start=iHS$START[59], iHS_end=iHS$END[59], iHS_pop=iHS$POP[59]),
    filter(gene.gff3, seqid==iHS$CHROM[60], between(end, left=iHS$START[60], right=iHS$END[60])) |> mutate(iHS_start=iHS$START[60], iHS_end=iHS$END[60], iHS_pop=iHS$POP[60]),
    filter(gene.gff3, seqid==iHS$CHROM[61], between(end, left=iHS$START[61], right=iHS$END[61])) |> mutate(iHS_start=iHS$START[61], iHS_end=iHS$END[61], iHS_pop=iHS$POP[61]),
    filter(gene.gff3, seqid==iHS$CHROM[62], between(end, left=iHS$START[62], right=iHS$END[62])) |> mutate(iHS_start=iHS$START[62], iHS_end=iHS$END[62], iHS_pop=iHS$POP[62]),
    filter(gene.gff3, seqid==iHS$CHROM[63], between(end, left=iHS$START[63], right=iHS$END[63])) |> mutate(iHS_start=iHS$START[63], iHS_end=iHS$END[63], iHS_pop=iHS$POP[63]),
    filter(gene.gff3, seqid==iHS$CHROM[64], between(end, left=iHS$START[64], right=iHS$END[64])) |> mutate(iHS_start=iHS$START[64], iHS_end=iHS$END[64], iHS_pop=iHS$POP[64]),
    filter(gene.gff3, seqid==iHS$CHROM[65], between(end, left=iHS$START[65], right=iHS$END[65])) |> mutate(iHS_start=iHS$START[65], iHS_end=iHS$END[65], iHS_pop=iHS$POP[65]),
    filter(gene.gff3, seqid==iHS$CHROM[66], between(end, left=iHS$START[66], right=iHS$END[66])) |> mutate(iHS_start=iHS$START[66], iHS_end=iHS$END[66], iHS_pop=iHS$POP[66]),
    filter(gene.gff3, seqid==iHS$CHROM[67], between(end, left=iHS$START[67], right=iHS$END[67])) |> mutate(iHS_start=iHS$START[67], iHS_end=iHS$END[67], iHS_pop=iHS$POP[67]),
    filter(gene.gff3, seqid==iHS$CHROM[68], between(end, left=iHS$START[68], right=iHS$END[68])) |> mutate(iHS_start=iHS$START[68], iHS_end=iHS$END[68], iHS_pop=iHS$POP[68]),
    filter(gene.gff3, seqid==iHS$CHROM[69], between(end, left=iHS$START[69], right=iHS$END[69])) |> mutate(iHS_start=iHS$START[69], iHS_end=iHS$END[69], iHS_pop=iHS$POP[69]),
    filter(gene.gff3, seqid==iHS$CHROM[70], between(end, left=iHS$START[70], right=iHS$END[70])) |> mutate(iHS_start=iHS$START[70], iHS_end=iHS$END[70], iHS_pop=iHS$POP[70]),
    filter(gene.gff3, seqid==iHS$CHROM[71], between(end, left=iHS$START[71], right=iHS$END[71])) |> mutate(iHS_start=iHS$START[71], iHS_end=iHS$END[71], iHS_pop=iHS$POP[71]),
    filter(gene.gff3, seqid==iHS$CHROM[72], between(end, left=iHS$START[72], right=iHS$END[72])) |> mutate(iHS_start=iHS$START[72], iHS_end=iHS$END[72], iHS_pop=iHS$POP[72]),
    filter(gene.gff3, seqid==iHS$CHROM[73], between(end, left=iHS$START[73], right=iHS$END[73])) |> mutate(iHS_start=iHS$START[73], iHS_end=iHS$END[73], iHS_pop=iHS$POP[73]),
    filter(gene.gff3, seqid==iHS$CHROM[74], between(end, left=iHS$START[74], right=iHS$END[74])) |> mutate(iHS_start=iHS$START[74], iHS_end=iHS$END[74], iHS_pop=iHS$POP[74]),
    filter(gene.gff3, seqid==iHS$CHROM[75], between(end, left=iHS$START[75], right=iHS$END[75])) |> mutate(iHS_start=iHS$START[75], iHS_end=iHS$END[75], iHS_pop=iHS$POP[75]),
    filter(gene.gff3, seqid==iHS$CHROM[76], between(end, left=iHS$START[76], right=iHS$END[76])) |> mutate(iHS_start=iHS$START[76], iHS_end=iHS$END[76], iHS_pop=iHS$POP[76]),
    filter(gene.gff3, seqid==iHS$CHROM[77], between(end, left=iHS$START[77], right=iHS$END[77])) |> mutate(iHS_start=iHS$START[77], iHS_end=iHS$END[77], iHS_pop=iHS$POP[77]),
    filter(gene.gff3, seqid==iHS$CHROM[78], between(end, left=iHS$START[78], right=iHS$END[78])) |> mutate(iHS_start=iHS$START[78], iHS_end=iHS$END[78], iHS_pop=iHS$POP[78]),
    filter(gene.gff3, seqid==iHS$CHROM[79], between(end, left=iHS$START[79], right=iHS$END[79])) |> mutate(iHS_start=iHS$START[79], iHS_end=iHS$END[79], iHS_pop=iHS$POP[79]),
    filter(gene.gff3, seqid==iHS$CHROM[80], between(end, left=iHS$START[80], right=iHS$END[80])) |> mutate(iHS_start=iHS$START[80], iHS_end=iHS$END[80], iHS_pop=iHS$POP[80]),
    filter(gene.gff3, seqid==iHS$CHROM[81], between(end, left=iHS$START[81], right=iHS$END[81])) |> mutate(iHS_start=iHS$START[81], iHS_end=iHS$END[81], iHS_pop=iHS$POP[81]),
    filter(gene.gff3, seqid==iHS$CHROM[82], between(end, left=iHS$START[82], right=iHS$END[82])) |> mutate(iHS_start=iHS$START[82], iHS_end=iHS$END[82], iHS_pop=iHS$POP[82]),
    filter(gene.gff3, seqid==iHS$CHROM[83], between(end, left=iHS$START[83], right=iHS$END[83])) |> mutate(iHS_start=iHS$START[83], iHS_end=iHS$END[83], iHS_pop=iHS$POP[83]),
    filter(gene.gff3, seqid==iHS$CHROM[84], between(end, left=iHS$START[84], right=iHS$END[84])) |> mutate(iHS_start=iHS$START[84], iHS_end=iHS$END[84], iHS_pop=iHS$POP[84]),
    filter(gene.gff3, seqid==iHS$CHROM[85], between(end, left=iHS$START[85], right=iHS$END[85])) |> mutate(iHS_start=iHS$START[85], iHS_end=iHS$END[85], iHS_pop=iHS$POP[85]),
    filter(gene.gff3, seqid==iHS$CHROM[86], between(end, left=iHS$START[86], right=iHS$END[86])) |> mutate(iHS_start=iHS$START[86], iHS_end=iHS$END[86], iHS_pop=iHS$POP[86]),
    filter(gene.gff3, seqid==iHS$CHROM[87], between(end, left=iHS$START[87], right=iHS$END[87])) |> mutate(iHS_start=iHS$START[87], iHS_end=iHS$END[87], iHS_pop=iHS$POP[87]),
    filter(gene.gff3, seqid==iHS$CHROM[88], between(end, left=iHS$START[88], right=iHS$END[88])) |> mutate(iHS_start=iHS$START[88], iHS_end=iHS$END[88], iHS_pop=iHS$POP[88]),
    filter(gene.gff3, seqid==iHS$CHROM[89], between(end, left=iHS$START[89], right=iHS$END[89])) |> mutate(iHS_start=iHS$START[89], iHS_end=iHS$END[89], iHS_pop=iHS$POP[89]),
    filter(gene.gff3, seqid==iHS$CHROM[90], between(end, left=iHS$START[90], right=iHS$END[90])) |> mutate(iHS_start=iHS$START[90], iHS_end=iHS$END[90], iHS_pop=iHS$POP[90]),
    filter(gene.gff3, seqid==iHS$CHROM[91], between(end, left=iHS$START[91], right=iHS$END[91])) |> mutate(iHS_start=iHS$START[91], iHS_end=iHS$END[91], iHS_pop=iHS$POP[91]),
    filter(gene.gff3, seqid==iHS$CHROM[92], between(end, left=iHS$START[92], right=iHS$END[92])) |> mutate(iHS_start=iHS$START[92], iHS_end=iHS$END[92], iHS_pop=iHS$POP[92]),
    filter(gene.gff3, seqid==iHS$CHROM[93], between(end, left=iHS$START[93], right=iHS$END[93])) |> mutate(iHS_start=iHS$START[93], iHS_end=iHS$END[93], iHS_pop=iHS$POP[93]),
    filter(gene.gff3, seqid==iHS$CHROM[94], between(end, left=iHS$START[94], right=iHS$END[94])) |> mutate(iHS_start=iHS$START[94], iHS_end=iHS$END[94], iHS_pop=iHS$POP[94]),
    filter(gene.gff3, seqid==iHS$CHROM[95], between(end, left=iHS$START[95], right=iHS$END[95])) |> mutate(iHS_start=iHS$START[95], iHS_end=iHS$END[95], iHS_pop=iHS$POP[95]),
    filter(gene.gff3, seqid==iHS$CHROM[96], between(end, left=iHS$START[96], right=iHS$END[96])) |> mutate(iHS_start=iHS$START[96], iHS_end=iHS$END[96], iHS_pop=iHS$POP[96]),
    filter(gene.gff3, seqid==iHS$CHROM[97], between(end, left=iHS$START[97], right=iHS$END[97])) |> mutate(iHS_start=iHS$START[97], iHS_end=iHS$END[97], iHS_pop=iHS$POP[97]),
    filter(gene.gff3, seqid==iHS$CHROM[98], between(end, left=iHS$START[98], right=iHS$END[98])) |> mutate(iHS_start=iHS$START[98], iHS_end=iHS$END[98], iHS_pop=iHS$POP[98]),
    filter(gene.gff3, seqid==iHS$CHROM[99], between(end, left=iHS$START[99], right=iHS$END[99])) |> mutate(iHS_start=iHS$START[99], iHS_end=iHS$END[99], iHS_pop=iHS$POP[99]),
    filter(gene.gff3, seqid==iHS$CHROM[100], between(end, left=iHS$START[100], right=iHS$END[100])) |> mutate(iHS_start=iHS$START[100], iHS_end=iHS$END[100], iHS_pop=iHS$POP[100]),
    filter(gene.gff3, seqid==iHS$CHROM[101], between(end, left=iHS$START[101], right=iHS$END[101])) |> mutate(iHS_start=iHS$START[101], iHS_end=iHS$END[101], iHS_pop=iHS$POP[101]),
    filter(gene.gff3, seqid==iHS$CHROM[102], between(end, left=iHS$START[102], right=iHS$END[102])) |> mutate(iHS_start=iHS$START[102], iHS_end=iHS$END[102], iHS_pop=iHS$POP[102]),
    filter(gene.gff3, seqid==iHS$CHROM[103], between(end, left=iHS$START[103], right=iHS$END[103])) |> mutate(iHS_start=iHS$START[103], iHS_end=iHS$END[103], iHS_pop=iHS$POP[103]),
    filter(gene.gff3, seqid==iHS$CHROM[104], between(end, left=iHS$START[104], right=iHS$END[104])) |> mutate(iHS_start=iHS$START[104], iHS_end=iHS$END[104], iHS_pop=iHS$POP[104]),
    filter(gene.gff3, seqid==iHS$CHROM[105], between(end, left=iHS$START[105], right=iHS$END[105])) |> mutate(iHS_start=iHS$START[105], iHS_end=iHS$END[105], iHS_pop=iHS$POP[105]),
    filter(gene.gff3, seqid==iHS$CHROM[106], between(end, left=iHS$START[106], right=iHS$END[106])) |> mutate(iHS_start=iHS$START[106], iHS_end=iHS$END[106], iHS_pop=iHS$POP[106]),
    filter(gene.gff3, seqid==iHS$CHROM[107], between(end, left=iHS$START[107], right=iHS$END[107])) |> mutate(iHS_start=iHS$START[107], iHS_end=iHS$END[107], iHS_pop=iHS$POP[107]),
    filter(gene.gff3, seqid==iHS$CHROM[108], between(end, left=iHS$START[108], right=iHS$END[108])) |> mutate(iHS_start=iHS$START[108], iHS_end=iHS$END[108], iHS_pop=iHS$POP[108]),
    filter(gene.gff3, seqid==iHS$CHROM[109], between(end, left=iHS$START[109], right=iHS$END[109])) |> mutate(iHS_start=iHS$START[109], iHS_end=iHS$END[109], iHS_pop=iHS$POP[109]),
    filter(gene.gff3, seqid==iHS$CHROM[110], between(end, left=iHS$START[110], right=iHS$END[110])) |> mutate(iHS_start=iHS$START[110], iHS_end=iHS$END[110], iHS_pop=iHS$POP[110]),
    filter(gene.gff3, seqid==iHS$CHROM[111], between(end, left=iHS$START[111], right=iHS$END[111])) |> mutate(iHS_start=iHS$START[111], iHS_end=iHS$END[111], iHS_pop=iHS$POP[111]),
    filter(gene.gff3, seqid==iHS$CHROM[112], between(end, left=iHS$START[112], right=iHS$END[112])) |> mutate(iHS_start=iHS$START[112], iHS_end=iHS$END[112], iHS_pop=iHS$POP[112]),
    filter(gene.gff3, seqid==iHS$CHROM[113], between(end, left=iHS$START[113], right=iHS$END[113])) |> mutate(iHS_start=iHS$START[113], iHS_end=iHS$END[113], iHS_pop=iHS$POP[113]),
    filter(gene.gff3, seqid==iHS$CHROM[114], between(end, left=iHS$START[114], right=iHS$END[114])) |> mutate(iHS_start=iHS$START[114], iHS_end=iHS$END[114], iHS_pop=iHS$POP[114]),
    filter(gene.gff3, seqid==iHS$CHROM[115], between(end, left=iHS$START[115], right=iHS$END[115])) |> mutate(iHS_start=iHS$START[115], iHS_end=iHS$END[115], iHS_pop=iHS$POP[115]),
    filter(gene.gff3, seqid==iHS$CHROM[116], between(end, left=iHS$START[116], right=iHS$END[116])) |> mutate(iHS_start=iHS$START[116], iHS_end=iHS$END[116], iHS_pop=iHS$POP[116]),
    filter(gene.gff3, seqid==iHS$CHROM[117], between(end, left=iHS$START[117], right=iHS$END[117])) |> mutate(iHS_start=iHS$START[117], iHS_end=iHS$END[117], iHS_pop=iHS$POP[117]),
    filter(gene.gff3, seqid==iHS$CHROM[118], between(end, left=iHS$START[118], right=iHS$END[118])) |> mutate(iHS_start=iHS$START[118], iHS_end=iHS$END[118], iHS_pop=iHS$POP[118]),
    filter(gene.gff3, seqid==iHS$CHROM[119], between(end, left=iHS$START[119], right=iHS$END[119])) |> mutate(iHS_start=iHS$START[119], iHS_end=iHS$END[119], iHS_pop=iHS$POP[119]),
    filter(gene.gff3, seqid==iHS$CHROM[120], between(end, left=iHS$START[120], right=iHS$END[120])) |> mutate(iHS_start=iHS$START[120], iHS_end=iHS$END[120], iHS_pop=iHS$POP[120]),
    filter(gene.gff3, seqid==iHS$CHROM[121], between(end, left=iHS$START[121], right=iHS$END[121])) |> mutate(iHS_start=iHS$START[121], iHS_end=iHS$END[121], iHS_pop=iHS$POP[121]),
    filter(gene.gff3, seqid==iHS$CHROM[122], between(end, left=iHS$START[122], right=iHS$END[122])) |> mutate(iHS_start=iHS$START[122], iHS_end=iHS$END[122], iHS_pop=iHS$POP[122]),
    filter(gene.gff3, seqid==iHS$CHROM[123], between(end, left=iHS$START[123], right=iHS$END[123])) |> mutate(iHS_start=iHS$START[123], iHS_end=iHS$END[123], iHS_pop=iHS$POP[123]),
    filter(gene.gff3, seqid==iHS$CHROM[124], between(end, left=iHS$START[124], right=iHS$END[124])) |> mutate(iHS_start=iHS$START[124], iHS_end=iHS$END[124], iHS_pop=iHS$POP[124]),
    .id="outlier")
genes.ending.in.regions

genes.across.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==iHS$CHROM[1], start<=iHS$START[1] & end>=iHS$END[1]) |> mutate(iHS_start=iHS$START[1], iHS_end=iHS$END[1], iHS_pop=iHS$POP[1]),
    filter(gene.gff3, seqid==iHS$CHROM[2], start<=iHS$START[2] & end>=iHS$END[2]) |> mutate(iHS_start=iHS$START[2], iHS_end=iHS$END[2], iHS_pop=iHS$POP[2]),
    filter(gene.gff3, seqid==iHS$CHROM[3], start<=iHS$START[3] & end>=iHS$END[3]) |> mutate(iHS_start=iHS$START[3], iHS_end=iHS$END[3], iHS_pop=iHS$POP[3]),
    filter(gene.gff3, seqid==iHS$CHROM[4], start<=iHS$START[4] & end>=iHS$END[4]) |> mutate(iHS_start=iHS$START[4], iHS_end=iHS$END[4], iHS_pop=iHS$POP[4]),
    filter(gene.gff3, seqid==iHS$CHROM[5], start<=iHS$START[5] & end>=iHS$END[5]) |> mutate(iHS_start=iHS$START[5], iHS_end=iHS$END[5], iHS_pop=iHS$POP[5]),
    filter(gene.gff3, seqid==iHS$CHROM[6], start<=iHS$START[6] & end>=iHS$END[6]) |> mutate(iHS_start=iHS$START[6], iHS_end=iHS$END[6], iHS_pop=iHS$POP[6]),
    filter(gene.gff3, seqid==iHS$CHROM[7], start<=iHS$START[7] & end>=iHS$END[7]) |> mutate(iHS_start=iHS$START[7], iHS_end=iHS$END[7], iHS_pop=iHS$POP[7]),
    filter(gene.gff3, seqid==iHS$CHROM[8], start<=iHS$START[8] & end>=iHS$END[8]) |> mutate(iHS_start=iHS$START[8], iHS_end=iHS$END[8], iHS_pop=iHS$POP[8]),
    filter(gene.gff3, seqid==iHS$CHROM[9], start<=iHS$START[9] & end>=iHS$END[9]) |> mutate(iHS_start=iHS$START[9], iHS_end=iHS$END[9], iHS_pop=iHS$POP[9]),
    filter(gene.gff3, seqid==iHS$CHROM[10], start<=iHS$START[10] & end>=iHS$END[10]) |> mutate(iHS_start=iHS$START[10], iHS_end=iHS$END[10], iHS_pop=iHS$POP[10]),
    filter(gene.gff3, seqid==iHS$CHROM[11], start<=iHS$START[11] & end>=iHS$END[11]) |> mutate(iHS_start=iHS$START[11], iHS_end=iHS$END[11], iHS_pop=iHS$POP[11]),
    filter(gene.gff3, seqid==iHS$CHROM[12], start<=iHS$START[12] & end>=iHS$END[12]) |> mutate(iHS_start=iHS$START[12], iHS_end=iHS$END[12], iHS_pop=iHS$POP[12]),
    filter(gene.gff3, seqid==iHS$CHROM[13], start<=iHS$START[13] & end>=iHS$END[13]) |> mutate(iHS_start=iHS$START[13], iHS_end=iHS$END[13], iHS_pop=iHS$POP[13]),
    filter(gene.gff3, seqid==iHS$CHROM[14], start<=iHS$START[14] & end>=iHS$END[14]) |> mutate(iHS_start=iHS$START[14], iHS_end=iHS$END[14], iHS_pop=iHS$POP[14]),
    filter(gene.gff3, seqid==iHS$CHROM[15], start<=iHS$START[15] & end>=iHS$END[15]) |> mutate(iHS_start=iHS$START[15], iHS_end=iHS$END[15], iHS_pop=iHS$POP[15]),
    filter(gene.gff3, seqid==iHS$CHROM[16], start<=iHS$START[16] & end>=iHS$END[16]) |> mutate(iHS_start=iHS$START[16], iHS_end=iHS$END[16], iHS_pop=iHS$POP[16]),
    filter(gene.gff3, seqid==iHS$CHROM[17], start<=iHS$START[17] & end>=iHS$END[17]) |> mutate(iHS_start=iHS$START[17], iHS_end=iHS$END[17], iHS_pop=iHS$POP[17]),
    filter(gene.gff3, seqid==iHS$CHROM[18], start<=iHS$START[18] & end>=iHS$END[18]) |> mutate(iHS_start=iHS$START[18], iHS_end=iHS$END[18], iHS_pop=iHS$POP[18]),
    filter(gene.gff3, seqid==iHS$CHROM[19], start<=iHS$START[19] & end>=iHS$END[19]) |> mutate(iHS_start=iHS$START[19], iHS_end=iHS$END[19], iHS_pop=iHS$POP[19]),
    filter(gene.gff3, seqid==iHS$CHROM[20], start<=iHS$START[20] & end>=iHS$END[20]) |> mutate(iHS_start=iHS$START[20], iHS_end=iHS$END[20], iHS_pop=iHS$POP[20]),
    filter(gene.gff3, seqid==iHS$CHROM[21], start<=iHS$START[21] & end>=iHS$END[21]) |> mutate(iHS_start=iHS$START[21], iHS_end=iHS$END[21], iHS_pop=iHS$POP[21]),
    filter(gene.gff3, seqid==iHS$CHROM[22], start<=iHS$START[22] & end>=iHS$END[22]) |> mutate(iHS_start=iHS$START[22], iHS_end=iHS$END[22], iHS_pop=iHS$POP[22]),
    filter(gene.gff3, seqid==iHS$CHROM[23], start<=iHS$START[23] & end>=iHS$END[23]) |> mutate(iHS_start=iHS$START[23], iHS_end=iHS$END[23], iHS_pop=iHS$POP[23]),
    filter(gene.gff3, seqid==iHS$CHROM[24], start<=iHS$START[24] & end>=iHS$END[24]) |> mutate(iHS_start=iHS$START[24], iHS_end=iHS$END[24], iHS_pop=iHS$POP[24]),
    filter(gene.gff3, seqid==iHS$CHROM[25], start<=iHS$START[25] & end>=iHS$END[25]) |> mutate(iHS_start=iHS$START[25], iHS_end=iHS$END[25], iHS_pop=iHS$POP[25]),
    filter(gene.gff3, seqid==iHS$CHROM[26], start<=iHS$START[26] & end>=iHS$END[26]) |> mutate(iHS_start=iHS$START[26], iHS_end=iHS$END[26], iHS_pop=iHS$POP[26]),
    filter(gene.gff3, seqid==iHS$CHROM[27], start<=iHS$START[27] & end>=iHS$END[27]) |> mutate(iHS_start=iHS$START[27], iHS_end=iHS$END[27], iHS_pop=iHS$POP[27]),
    filter(gene.gff3, seqid==iHS$CHROM[28], start<=iHS$START[28] & end>=iHS$END[28]) |> mutate(iHS_start=iHS$START[28], iHS_end=iHS$END[28], iHS_pop=iHS$POP[28]),
    filter(gene.gff3, seqid==iHS$CHROM[29], start<=iHS$START[29] & end>=iHS$END[29]) |> mutate(iHS_start=iHS$START[29], iHS_end=iHS$END[29], iHS_pop=iHS$POP[29]),
    filter(gene.gff3, seqid==iHS$CHROM[30], start<=iHS$START[30] & end>=iHS$END[30]) |> mutate(iHS_start=iHS$START[30], iHS_end=iHS$END[30], iHS_pop=iHS$POP[30]),
    filter(gene.gff3, seqid==iHS$CHROM[31], start<=iHS$START[31] & end>=iHS$END[31]) |> mutate(iHS_start=iHS$START[31], iHS_end=iHS$END[31], iHS_pop=iHS$POP[31]),
    filter(gene.gff3, seqid==iHS$CHROM[32], start<=iHS$START[32] & end>=iHS$END[32]) |> mutate(iHS_start=iHS$START[32], iHS_end=iHS$END[32], iHS_pop=iHS$POP[32]),
    filter(gene.gff3, seqid==iHS$CHROM[33], start<=iHS$START[33] & end>=iHS$END[33]) |> mutate(iHS_start=iHS$START[33], iHS_end=iHS$END[33], iHS_pop=iHS$POP[33]),
    filter(gene.gff3, seqid==iHS$CHROM[34], start<=iHS$START[34] & end>=iHS$END[34]) |> mutate(iHS_start=iHS$START[34], iHS_end=iHS$END[34], iHS_pop=iHS$POP[34]),
    filter(gene.gff3, seqid==iHS$CHROM[35], start<=iHS$START[35] & end>=iHS$END[35]) |> mutate(iHS_start=iHS$START[35], iHS_end=iHS$END[35], iHS_pop=iHS$POP[35]),
    filter(gene.gff3, seqid==iHS$CHROM[36], start<=iHS$START[36] & end>=iHS$END[36]) |> mutate(iHS_start=iHS$START[36], iHS_end=iHS$END[36], iHS_pop=iHS$POP[36]),
    filter(gene.gff3, seqid==iHS$CHROM[37], start<=iHS$START[37] & end>=iHS$END[37]) |> mutate(iHS_start=iHS$START[37], iHS_end=iHS$END[37], iHS_pop=iHS$POP[37]),
    filter(gene.gff3, seqid==iHS$CHROM[38], start<=iHS$START[38] & end>=iHS$END[38]) |> mutate(iHS_start=iHS$START[38], iHS_end=iHS$END[38], iHS_pop=iHS$POP[38]),
    filter(gene.gff3, seqid==iHS$CHROM[39], start<=iHS$START[39] & end>=iHS$END[39]) |> mutate(iHS_start=iHS$START[39], iHS_end=iHS$END[39], iHS_pop=iHS$POP[39]),
    filter(gene.gff3, seqid==iHS$CHROM[40], start<=iHS$START[40] & end>=iHS$END[40]) |> mutate(iHS_start=iHS$START[40], iHS_end=iHS$END[40], iHS_pop=iHS$POP[40]),
    filter(gene.gff3, seqid==iHS$CHROM[41], start<=iHS$START[41] & end>=iHS$END[41]) |> mutate(iHS_start=iHS$START[41], iHS_end=iHS$END[41], iHS_pop=iHS$POP[41]),
    filter(gene.gff3, seqid==iHS$CHROM[42], start<=iHS$START[42] & end>=iHS$END[42]) |> mutate(iHS_start=iHS$START[42], iHS_end=iHS$END[42], iHS_pop=iHS$POP[42]),
    filter(gene.gff3, seqid==iHS$CHROM[43], start<=iHS$START[43] & end>=iHS$END[43]) |> mutate(iHS_start=iHS$START[43], iHS_end=iHS$END[43], iHS_pop=iHS$POP[43]),
    filter(gene.gff3, seqid==iHS$CHROM[44], start<=iHS$START[44] & end>=iHS$END[44]) |> mutate(iHS_start=iHS$START[44], iHS_end=iHS$END[44], iHS_pop=iHS$POP[44]),
    filter(gene.gff3, seqid==iHS$CHROM[45], start<=iHS$START[45] & end>=iHS$END[45]) |> mutate(iHS_start=iHS$START[45], iHS_end=iHS$END[45], iHS_pop=iHS$POP[45]),
    filter(gene.gff3, seqid==iHS$CHROM[46], start<=iHS$START[46] & end>=iHS$END[46]) |> mutate(iHS_start=iHS$START[46], iHS_end=iHS$END[46], iHS_pop=iHS$POP[46]),
    filter(gene.gff3, seqid==iHS$CHROM[47], start<=iHS$START[47] & end>=iHS$END[47]) |> mutate(iHS_start=iHS$START[47], iHS_end=iHS$END[47], iHS_pop=iHS$POP[47]),
    filter(gene.gff3, seqid==iHS$CHROM[48], start<=iHS$START[48] & end>=iHS$END[48]) |> mutate(iHS_start=iHS$START[48], iHS_end=iHS$END[48], iHS_pop=iHS$POP[48]),
    filter(gene.gff3, seqid==iHS$CHROM[49], start<=iHS$START[49] & end>=iHS$END[49]) |> mutate(iHS_start=iHS$START[49], iHS_end=iHS$END[49], iHS_pop=iHS$POP[49]),
    filter(gene.gff3, seqid==iHS$CHROM[50], start<=iHS$START[50] & end>=iHS$END[50]) |> mutate(iHS_start=iHS$START[50], iHS_end=iHS$END[50], iHS_pop=iHS$POP[50]),
    filter(gene.gff3, seqid==iHS$CHROM[51], start<=iHS$START[51] & end>=iHS$END[51]) |> mutate(iHS_start=iHS$START[51], iHS_end=iHS$END[51], iHS_pop=iHS$POP[51]),
    filter(gene.gff3, seqid==iHS$CHROM[52], start<=iHS$START[52] & end>=iHS$END[52]) |> mutate(iHS_start=iHS$START[52], iHS_end=iHS$END[52], iHS_pop=iHS$POP[52]),
    filter(gene.gff3, seqid==iHS$CHROM[53], start<=iHS$START[53] & end>=iHS$END[53]) |> mutate(iHS_start=iHS$START[53], iHS_end=iHS$END[53], iHS_pop=iHS$POP[53]),
    filter(gene.gff3, seqid==iHS$CHROM[54], start<=iHS$START[54] & end>=iHS$END[54]) |> mutate(iHS_start=iHS$START[54], iHS_end=iHS$END[54], iHS_pop=iHS$POP[54]),
    filter(gene.gff3, seqid==iHS$CHROM[55], start<=iHS$START[55] & end>=iHS$END[55]) |> mutate(iHS_start=iHS$START[55], iHS_end=iHS$END[55], iHS_pop=iHS$POP[55]),
    filter(gene.gff3, seqid==iHS$CHROM[56], start<=iHS$START[56] & end>=iHS$END[56]) |> mutate(iHS_start=iHS$START[56], iHS_end=iHS$END[56], iHS_pop=iHS$POP[56]),
    filter(gene.gff3, seqid==iHS$CHROM[57], start<=iHS$START[57] & end>=iHS$END[57]) |> mutate(iHS_start=iHS$START[57], iHS_end=iHS$END[57], iHS_pop=iHS$POP[57]),
    filter(gene.gff3, seqid==iHS$CHROM[58], start<=iHS$START[58] & end>=iHS$END[58]) |> mutate(iHS_start=iHS$START[58], iHS_end=iHS$END[58], iHS_pop=iHS$POP[58]),
    filter(gene.gff3, seqid==iHS$CHROM[59], start<=iHS$START[59] & end>=iHS$END[59]) |> mutate(iHS_start=iHS$START[59], iHS_end=iHS$END[59], iHS_pop=iHS$POP[59]),
    filter(gene.gff3, seqid==iHS$CHROM[60], start<=iHS$START[60] & end>=iHS$END[60]) |> mutate(iHS_start=iHS$START[60], iHS_end=iHS$END[60], iHS_pop=iHS$POP[60]),
    filter(gene.gff3, seqid==iHS$CHROM[61], start<=iHS$START[61] & end>=iHS$END[61]) |> mutate(iHS_start=iHS$START[61], iHS_end=iHS$END[61], iHS_pop=iHS$POP[61]),
    filter(gene.gff3, seqid==iHS$CHROM[62], start<=iHS$START[62] & end>=iHS$END[62]) |> mutate(iHS_start=iHS$START[62], iHS_end=iHS$END[62], iHS_pop=iHS$POP[62]),
    filter(gene.gff3, seqid==iHS$CHROM[63], start<=iHS$START[63] & end>=iHS$END[63]) |> mutate(iHS_start=iHS$START[63], iHS_end=iHS$END[63], iHS_pop=iHS$POP[63]),
    filter(gene.gff3, seqid==iHS$CHROM[64], start<=iHS$START[64] & end>=iHS$END[64]) |> mutate(iHS_start=iHS$START[64], iHS_end=iHS$END[64], iHS_pop=iHS$POP[64]),
    filter(gene.gff3, seqid==iHS$CHROM[65], start<=iHS$START[65] & end>=iHS$END[65]) |> mutate(iHS_start=iHS$START[65], iHS_end=iHS$END[65], iHS_pop=iHS$POP[65]),
    filter(gene.gff3, seqid==iHS$CHROM[66], start<=iHS$START[66] & end>=iHS$END[66]) |> mutate(iHS_start=iHS$START[66], iHS_end=iHS$END[66], iHS_pop=iHS$POP[66]),
    filter(gene.gff3, seqid==iHS$CHROM[67], start<=iHS$START[67] & end>=iHS$END[67]) |> mutate(iHS_start=iHS$START[67], iHS_end=iHS$END[67], iHS_pop=iHS$POP[67]),
    filter(gene.gff3, seqid==iHS$CHROM[68], start<=iHS$START[68] & end>=iHS$END[68]) |> mutate(iHS_start=iHS$START[68], iHS_end=iHS$END[68], iHS_pop=iHS$POP[68]),
    filter(gene.gff3, seqid==iHS$CHROM[69], start<=iHS$START[69] & end>=iHS$END[69]) |> mutate(iHS_start=iHS$START[69], iHS_end=iHS$END[69], iHS_pop=iHS$POP[69]),
    filter(gene.gff3, seqid==iHS$CHROM[70], start<=iHS$START[70] & end>=iHS$END[70]) |> mutate(iHS_start=iHS$START[70], iHS_end=iHS$END[70], iHS_pop=iHS$POP[70]),
    filter(gene.gff3, seqid==iHS$CHROM[71], start<=iHS$START[71] & end>=iHS$END[71]) |> mutate(iHS_start=iHS$START[71], iHS_end=iHS$END[71], iHS_pop=iHS$POP[71]),
    filter(gene.gff3, seqid==iHS$CHROM[72], start<=iHS$START[72] & end>=iHS$END[72]) |> mutate(iHS_start=iHS$START[72], iHS_end=iHS$END[72], iHS_pop=iHS$POP[72]),
    filter(gene.gff3, seqid==iHS$CHROM[73], start<=iHS$START[73] & end>=iHS$END[73]) |> mutate(iHS_start=iHS$START[73], iHS_end=iHS$END[73], iHS_pop=iHS$POP[73]),
    filter(gene.gff3, seqid==iHS$CHROM[74], start<=iHS$START[74] & end>=iHS$END[74]) |> mutate(iHS_start=iHS$START[74], iHS_end=iHS$END[74], iHS_pop=iHS$POP[74]),
    filter(gene.gff3, seqid==iHS$CHROM[75], start<=iHS$START[75] & end>=iHS$END[75]) |> mutate(iHS_start=iHS$START[75], iHS_end=iHS$END[75], iHS_pop=iHS$POP[75]),
    filter(gene.gff3, seqid==iHS$CHROM[76], start<=iHS$START[76] & end>=iHS$END[76]) |> mutate(iHS_start=iHS$START[76], iHS_end=iHS$END[76], iHS_pop=iHS$POP[76]),
    filter(gene.gff3, seqid==iHS$CHROM[77], start<=iHS$START[77] & end>=iHS$END[77]) |> mutate(iHS_start=iHS$START[77], iHS_end=iHS$END[77], iHS_pop=iHS$POP[77]),
    filter(gene.gff3, seqid==iHS$CHROM[78], start<=iHS$START[78] & end>=iHS$END[78]) |> mutate(iHS_start=iHS$START[78], iHS_end=iHS$END[78], iHS_pop=iHS$POP[78]),
    filter(gene.gff3, seqid==iHS$CHROM[79], start<=iHS$START[79] & end>=iHS$END[79]) |> mutate(iHS_start=iHS$START[79], iHS_end=iHS$END[79], iHS_pop=iHS$POP[79]),
    filter(gene.gff3, seqid==iHS$CHROM[80], start<=iHS$START[80] & end>=iHS$END[80]) |> mutate(iHS_start=iHS$START[80], iHS_end=iHS$END[80], iHS_pop=iHS$POP[80]),
    filter(gene.gff3, seqid==iHS$CHROM[81], start<=iHS$START[81] & end>=iHS$END[81]) |> mutate(iHS_start=iHS$START[81], iHS_end=iHS$END[81], iHS_pop=iHS$POP[81]),
    filter(gene.gff3, seqid==iHS$CHROM[82], start<=iHS$START[82] & end>=iHS$END[82]) |> mutate(iHS_start=iHS$START[82], iHS_end=iHS$END[82], iHS_pop=iHS$POP[82]),
    filter(gene.gff3, seqid==iHS$CHROM[83], start<=iHS$START[83] & end>=iHS$END[83]) |> mutate(iHS_start=iHS$START[83], iHS_end=iHS$END[83], iHS_pop=iHS$POP[83]),
    filter(gene.gff3, seqid==iHS$CHROM[84], start<=iHS$START[84] & end>=iHS$END[84]) |> mutate(iHS_start=iHS$START[84], iHS_end=iHS$END[84], iHS_pop=iHS$POP[84]),
    filter(gene.gff3, seqid==iHS$CHROM[85], start<=iHS$START[85] & end>=iHS$END[85]) |> mutate(iHS_start=iHS$START[85], iHS_end=iHS$END[85], iHS_pop=iHS$POP[85]),
    filter(gene.gff3, seqid==iHS$CHROM[86], start<=iHS$START[86] & end>=iHS$END[86]) |> mutate(iHS_start=iHS$START[86], iHS_end=iHS$END[86], iHS_pop=iHS$POP[86]),
    filter(gene.gff3, seqid==iHS$CHROM[87], start<=iHS$START[87] & end>=iHS$END[87]) |> mutate(iHS_start=iHS$START[87], iHS_end=iHS$END[87], iHS_pop=iHS$POP[87]),
    filter(gene.gff3, seqid==iHS$CHROM[88], start<=iHS$START[88] & end>=iHS$END[88]) |> mutate(iHS_start=iHS$START[88], iHS_end=iHS$END[88], iHS_pop=iHS$POP[88]),
    filter(gene.gff3, seqid==iHS$CHROM[89], start<=iHS$START[89] & end>=iHS$END[89]) |> mutate(iHS_start=iHS$START[89], iHS_end=iHS$END[89], iHS_pop=iHS$POP[89]),
    filter(gene.gff3, seqid==iHS$CHROM[90], start<=iHS$START[90] & end>=iHS$END[90]) |> mutate(iHS_start=iHS$START[90], iHS_end=iHS$END[90], iHS_pop=iHS$POP[90]),
    filter(gene.gff3, seqid==iHS$CHROM[91], start<=iHS$START[91] & end>=iHS$END[91]) |> mutate(iHS_start=iHS$START[91], iHS_end=iHS$END[91], iHS_pop=iHS$POP[91]),
    filter(gene.gff3, seqid==iHS$CHROM[92], start<=iHS$START[92] & end>=iHS$END[92]) |> mutate(iHS_start=iHS$START[92], iHS_end=iHS$END[92], iHS_pop=iHS$POP[92]),
    filter(gene.gff3, seqid==iHS$CHROM[93], start<=iHS$START[93] & end>=iHS$END[93]) |> mutate(iHS_start=iHS$START[93], iHS_end=iHS$END[93], iHS_pop=iHS$POP[93]),
    filter(gene.gff3, seqid==iHS$CHROM[94], start<=iHS$START[94] & end>=iHS$END[94]) |> mutate(iHS_start=iHS$START[94], iHS_end=iHS$END[94], iHS_pop=iHS$POP[94]),
    filter(gene.gff3, seqid==iHS$CHROM[95], start<=iHS$START[95] & end>=iHS$END[95]) |> mutate(iHS_start=iHS$START[95], iHS_end=iHS$END[95], iHS_pop=iHS$POP[95]),
    filter(gene.gff3, seqid==iHS$CHROM[96], start<=iHS$START[96] & end>=iHS$END[96]) |> mutate(iHS_start=iHS$START[96], iHS_end=iHS$END[96], iHS_pop=iHS$POP[96]),
    filter(gene.gff3, seqid==iHS$CHROM[97], start<=iHS$START[97] & end>=iHS$END[97]) |> mutate(iHS_start=iHS$START[97], iHS_end=iHS$END[97], iHS_pop=iHS$POP[97]),
    filter(gene.gff3, seqid==iHS$CHROM[98], start<=iHS$START[98] & end>=iHS$END[98]) |> mutate(iHS_start=iHS$START[98], iHS_end=iHS$END[98], iHS_pop=iHS$POP[98]),
    filter(gene.gff3, seqid==iHS$CHROM[99], start<=iHS$START[99] & end>=iHS$END[99]) |> mutate(iHS_start=iHS$START[99], iHS_end=iHS$END[99], iHS_pop=iHS$POP[99]),
    filter(gene.gff3, seqid==iHS$CHROM[100], start<=iHS$START[100] & end>=iHS$END[100]) |> mutate(iHS_start=iHS$START[100], iHS_end=iHS$END[100], iHS_pop=iHS$POP[100]),
    filter(gene.gff3, seqid==iHS$CHROM[101], start<=iHS$START[101] & end>=iHS$END[101]) |> mutate(iHS_start=iHS$START[101], iHS_end=iHS$END[101], iHS_pop=iHS$POP[101]),
    filter(gene.gff3, seqid==iHS$CHROM[102], start<=iHS$START[102] & end>=iHS$END[102]) |> mutate(iHS_start=iHS$START[102], iHS_end=iHS$END[102], iHS_pop=iHS$POP[102]),
    filter(gene.gff3, seqid==iHS$CHROM[103], start<=iHS$START[103] & end>=iHS$END[103]) |> mutate(iHS_start=iHS$START[103], iHS_end=iHS$END[103], iHS_pop=iHS$POP[103]),
    filter(gene.gff3, seqid==iHS$CHROM[104], start<=iHS$START[104] & end>=iHS$END[104]) |> mutate(iHS_start=iHS$START[104], iHS_end=iHS$END[104], iHS_pop=iHS$POP[104]),
    filter(gene.gff3, seqid==iHS$CHROM[105], start<=iHS$START[105] & end>=iHS$END[105]) |> mutate(iHS_start=iHS$START[105], iHS_end=iHS$END[105], iHS_pop=iHS$POP[105]),
    filter(gene.gff3, seqid==iHS$CHROM[106], start<=iHS$START[106] & end>=iHS$END[106]) |> mutate(iHS_start=iHS$START[106], iHS_end=iHS$END[106], iHS_pop=iHS$POP[106]),
    filter(gene.gff3, seqid==iHS$CHROM[107], start<=iHS$START[107] & end>=iHS$END[107]) |> mutate(iHS_start=iHS$START[107], iHS_end=iHS$END[107], iHS_pop=iHS$POP[107]),
    filter(gene.gff3, seqid==iHS$CHROM[108], start<=iHS$START[108] & end>=iHS$END[108]) |> mutate(iHS_start=iHS$START[108], iHS_end=iHS$END[108], iHS_pop=iHS$POP[108]),
    filter(gene.gff3, seqid==iHS$CHROM[109], start<=iHS$START[109] & end>=iHS$END[109]) |> mutate(iHS_start=iHS$START[109], iHS_end=iHS$END[109], iHS_pop=iHS$POP[109]),
    filter(gene.gff3, seqid==iHS$CHROM[110], start<=iHS$START[110] & end>=iHS$END[110]) |> mutate(iHS_start=iHS$START[110], iHS_end=iHS$END[110], iHS_pop=iHS$POP[110]),
    filter(gene.gff3, seqid==iHS$CHROM[111], start<=iHS$START[111] & end>=iHS$END[111]) |> mutate(iHS_start=iHS$START[111], iHS_end=iHS$END[111], iHS_pop=iHS$POP[111]),
    filter(gene.gff3, seqid==iHS$CHROM[112], start<=iHS$START[112] & end>=iHS$END[112]) |> mutate(iHS_start=iHS$START[112], iHS_end=iHS$END[112], iHS_pop=iHS$POP[112]),
    filter(gene.gff3, seqid==iHS$CHROM[113], start<=iHS$START[113] & end>=iHS$END[113]) |> mutate(iHS_start=iHS$START[113], iHS_end=iHS$END[113], iHS_pop=iHS$POP[113]),
    filter(gene.gff3, seqid==iHS$CHROM[114], start<=iHS$START[114] & end>=iHS$END[114]) |> mutate(iHS_start=iHS$START[114], iHS_end=iHS$END[114], iHS_pop=iHS$POP[114]),
    filter(gene.gff3, seqid==iHS$CHROM[115], start<=iHS$START[115] & end>=iHS$END[115]) |> mutate(iHS_start=iHS$START[115], iHS_end=iHS$END[115], iHS_pop=iHS$POP[115]),
    filter(gene.gff3, seqid==iHS$CHROM[116], start<=iHS$START[116] & end>=iHS$END[116]) |> mutate(iHS_start=iHS$START[116], iHS_end=iHS$END[116], iHS_pop=iHS$POP[116]),
    filter(gene.gff3, seqid==iHS$CHROM[117], start<=iHS$START[117] & end>=iHS$END[117]) |> mutate(iHS_start=iHS$START[117], iHS_end=iHS$END[117], iHS_pop=iHS$POP[117]),
    filter(gene.gff3, seqid==iHS$CHROM[118], start<=iHS$START[118] & end>=iHS$END[118]) |> mutate(iHS_start=iHS$START[118], iHS_end=iHS$END[118], iHS_pop=iHS$POP[118]),
    filter(gene.gff3, seqid==iHS$CHROM[119], start<=iHS$START[119] & end>=iHS$END[119]) |> mutate(iHS_start=iHS$START[119], iHS_end=iHS$END[119], iHS_pop=iHS$POP[119]),
    filter(gene.gff3, seqid==iHS$CHROM[120], start<=iHS$START[120] & end>=iHS$END[120]) |> mutate(iHS_start=iHS$START[120], iHS_end=iHS$END[120], iHS_pop=iHS$POP[120]),
    filter(gene.gff3, seqid==iHS$CHROM[121], start<=iHS$START[121] & end>=iHS$END[121]) |> mutate(iHS_start=iHS$START[121], iHS_end=iHS$END[121], iHS_pop=iHS$POP[121]),
    filter(gene.gff3, seqid==iHS$CHROM[122], start<=iHS$START[122] & end>=iHS$END[122]) |> mutate(iHS_start=iHS$START[122], iHS_end=iHS$END[122], iHS_pop=iHS$POP[122]),
    filter(gene.gff3, seqid==iHS$CHROM[123], start<=iHS$START[123] & end>=iHS$END[123]) |> mutate(iHS_start=iHS$START[123], iHS_end=iHS$END[123], iHS_pop=iHS$POP[123]),
    filter(gene.gff3, seqid==iHS$CHROM[124], start<=iHS$START[124] & end>=iHS$END[124]) |> mutate(iHS_start=iHS$START[124], iHS_end=iHS$END[124], iHS_pop=iHS$POP[124]),
    .id="outlier")
genes.across.regions

gene.hits.regions <- 
  bind_rows(genes.within.regions, genes.starting.in.regions, genes.ending.in.regions, genes.across.regions) |> 
  distinct(id, PANTHER_accession, iHS_pop, .keep_all=TRUE)

gene.hits.regions <- 
  rename(gene.hits.regions, region=outlier, chrom=seqid) |>
  arrange(chrom, start, iHS_pop)
  
gene.hits.regions <- mutate(gene.hits.regions, loc=paste0(chrom, ":", start, "–", end))
  
write_tsv(x=gene.hits.regions, file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.2/iHS.gmap_PROP_CRIT.gene.hits.regions.tab")

saveRDS(object=gene.hits.regions, file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.2/iHS.gmap_PROP_CRIT.gene.hits.regions.RDS")

#
## filter(gene.hits.regions, iHS_pop=="Del Norte-Humboldt") |> 
##   select(id, PANTHER_accession) |> 
##   distinct() |>
##   write_tsv(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.6/ihs2_NorteHumboldt", col_names=FALSE)

## filter(gene.hits.regions, iHS_pop=="Mendocino") |> 
##   select(id, PANTHER_accession) |> 
##   distinct() |>
##   write_tsv(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.6/ihs2_Mendocino", col_names=FALSE)

## filter(gene.hits.regions, iHS_pop=="Santa Barbara") |> 
##   select(id, PANTHER_accession) |> 
##   distinct() |>
##   write_tsv(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.6/ihs2_SantaBarbara", col_names=FALSE)


