library(tidyverse)
library(ggvenn)
library(gridExtra)

gene.gff3 <- readRDS(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.0/gene.gff3.RDS")
#gene.gff3 <- select(gene.gff3, -start, -end) |> rename(start=prostart, end=proend) |> arrange(seqid, start)

nSL <- read_tsv(file="/Volumes/Tigrigobius/tgoby/nsl/selscan/outliers.PROP_CRIT.tsv")

nSL <- filter(nSL, RANK_PROP_CRIT>0.995)

genes.within.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==nSL$CHROM[1], start>=nSL$START[1] & end<=nSL$END[1]) |> mutate(nSL_start=nSL$START[1], nSL_end=nSL$END[1], nSL_pop=nSL$POP[1]),
    filter(gene.gff3, seqid==nSL$CHROM[2], start>=nSL$START[2] & end<=nSL$END[2]) |> mutate(nSL_start=nSL$START[2], nSL_end=nSL$END[2], nSL_pop=nSL$POP[2]),
    filter(gene.gff3, seqid==nSL$CHROM[3], start>=nSL$START[3] & end<=nSL$END[3]) |> mutate(nSL_start=nSL$START[3], nSL_end=nSL$END[3], nSL_pop=nSL$POP[3]),
    filter(gene.gff3, seqid==nSL$CHROM[4], start>=nSL$START[4] & end<=nSL$END[4]) |> mutate(nSL_start=nSL$START[4], nSL_end=nSL$END[4], nSL_pop=nSL$POP[4]),
    filter(gene.gff3, seqid==nSL$CHROM[5], start>=nSL$START[5] & end<=nSL$END[5]) |> mutate(nSL_start=nSL$START[5], nSL_end=nSL$END[5], nSL_pop=nSL$POP[5]),
    filter(gene.gff3, seqid==nSL$CHROM[6], start>=nSL$START[6] & end<=nSL$END[6]) |> mutate(nSL_start=nSL$START[6], nSL_end=nSL$END[6], nSL_pop=nSL$POP[6]),
    filter(gene.gff3, seqid==nSL$CHROM[7], start>=nSL$START[7] & end<=nSL$END[7]) |> mutate(nSL_start=nSL$START[7], nSL_end=nSL$END[7], nSL_pop=nSL$POP[7]),
    filter(gene.gff3, seqid==nSL$CHROM[8], start>=nSL$START[8] & end<=nSL$END[8]) |> mutate(nSL_start=nSL$START[8], nSL_end=nSL$END[8], nSL_pop=nSL$POP[8]),
    filter(gene.gff3, seqid==nSL$CHROM[9], start>=nSL$START[9] & end<=nSL$END[9]) |> mutate(nSL_start=nSL$START[9], nSL_end=nSL$END[9], nSL_pop=nSL$POP[9]),
    filter(gene.gff3, seqid==nSL$CHROM[10], start>=nSL$START[10] & end<=nSL$END[10]) |> mutate(nSL_start=nSL$START[10], nSL_end=nSL$END[10], nSL_pop=nSL$POP[10]),
    filter(gene.gff3, seqid==nSL$CHROM[11], start>=nSL$START[11] & end<=nSL$END[11]) |> mutate(nSL_start=nSL$START[11], nSL_end=nSL$END[11], nSL_pop=nSL$POP[11]),
    filter(gene.gff3, seqid==nSL$CHROM[12], start>=nSL$START[12] & end<=nSL$END[12]) |> mutate(nSL_start=nSL$START[12], nSL_end=nSL$END[12], nSL_pop=nSL$POP[12]),
    filter(gene.gff3, seqid==nSL$CHROM[13], start>=nSL$START[13] & end<=nSL$END[13]) |> mutate(nSL_start=nSL$START[13], nSL_end=nSL$END[13], nSL_pop=nSL$POP[13]),
    filter(gene.gff3, seqid==nSL$CHROM[14], start>=nSL$START[14] & end<=nSL$END[14]) |> mutate(nSL_start=nSL$START[14], nSL_end=nSL$END[14], nSL_pop=nSL$POP[14]),
    filter(gene.gff3, seqid==nSL$CHROM[15], start>=nSL$START[15] & end<=nSL$END[15]) |> mutate(nSL_start=nSL$START[15], nSL_end=nSL$END[15], nSL_pop=nSL$POP[15]),
    filter(gene.gff3, seqid==nSL$CHROM[16], start>=nSL$START[16] & end<=nSL$END[16]) |> mutate(nSL_start=nSL$START[16], nSL_end=nSL$END[16], nSL_pop=nSL$POP[16]),
    filter(gene.gff3, seqid==nSL$CHROM[17], start>=nSL$START[17] & end<=nSL$END[17]) |> mutate(nSL_start=nSL$START[17], nSL_end=nSL$END[17], nSL_pop=nSL$POP[17]),
    filter(gene.gff3, seqid==nSL$CHROM[18], start>=nSL$START[18] & end<=nSL$END[18]) |> mutate(nSL_start=nSL$START[18], nSL_end=nSL$END[18], nSL_pop=nSL$POP[18]),
    filter(gene.gff3, seqid==nSL$CHROM[19], start>=nSL$START[19] & end<=nSL$END[19]) |> mutate(nSL_start=nSL$START[19], nSL_end=nSL$END[19], nSL_pop=nSL$POP[19]),
    filter(gene.gff3, seqid==nSL$CHROM[20], start>=nSL$START[20] & end<=nSL$END[20]) |> mutate(nSL_start=nSL$START[20], nSL_end=nSL$END[20], nSL_pop=nSL$POP[20]),
    filter(gene.gff3, seqid==nSL$CHROM[21], start>=nSL$START[21] & end<=nSL$END[21]) |> mutate(nSL_start=nSL$START[21], nSL_end=nSL$END[21], nSL_pop=nSL$POP[21]),
    filter(gene.gff3, seqid==nSL$CHROM[22], start>=nSL$START[22] & end<=nSL$END[22]) |> mutate(nSL_start=nSL$START[22], nSL_end=nSL$END[22], nSL_pop=nSL$POP[22]),
    filter(gene.gff3, seqid==nSL$CHROM[23], start>=nSL$START[23] & end<=nSL$END[23]) |> mutate(nSL_start=nSL$START[23], nSL_end=nSL$END[23], nSL_pop=nSL$POP[23]),
    filter(gene.gff3, seqid==nSL$CHROM[24], start>=nSL$START[24] & end<=nSL$END[24]) |> mutate(nSL_start=nSL$START[24], nSL_end=nSL$END[24], nSL_pop=nSL$POP[24]),
    filter(gene.gff3, seqid==nSL$CHROM[25], start>=nSL$START[25] & end<=nSL$END[25]) |> mutate(nSL_start=nSL$START[25], nSL_end=nSL$END[25], nSL_pop=nSL$POP[25]),
    filter(gene.gff3, seqid==nSL$CHROM[26], start>=nSL$START[26] & end<=nSL$END[26]) |> mutate(nSL_start=nSL$START[26], nSL_end=nSL$END[26], nSL_pop=nSL$POP[26]),
    filter(gene.gff3, seqid==nSL$CHROM[27], start>=nSL$START[27] & end<=nSL$END[27]) |> mutate(nSL_start=nSL$START[27], nSL_end=nSL$END[27], nSL_pop=nSL$POP[27]),
    filter(gene.gff3, seqid==nSL$CHROM[28], start>=nSL$START[28] & end<=nSL$END[28]) |> mutate(nSL_start=nSL$START[28], nSL_end=nSL$END[28], nSL_pop=nSL$POP[28]),
    filter(gene.gff3, seqid==nSL$CHROM[29], start>=nSL$START[29] & end<=nSL$END[29]) |> mutate(nSL_start=nSL$START[29], nSL_end=nSL$END[29], nSL_pop=nSL$POP[29]),
    filter(gene.gff3, seqid==nSL$CHROM[30], start>=nSL$START[30] & end<=nSL$END[30]) |> mutate(nSL_start=nSL$START[30], nSL_end=nSL$END[30], nSL_pop=nSL$POP[30]),
    filter(gene.gff3, seqid==nSL$CHROM[31], start>=nSL$START[31] & end<=nSL$END[31]) |> mutate(nSL_start=nSL$START[31], nSL_end=nSL$END[31], nSL_pop=nSL$POP[31]),
    filter(gene.gff3, seqid==nSL$CHROM[32], start>=nSL$START[32] & end<=nSL$END[32]) |> mutate(nSL_start=nSL$START[32], nSL_end=nSL$END[32], nSL_pop=nSL$POP[32]),
    filter(gene.gff3, seqid==nSL$CHROM[33], start>=nSL$START[33] & end<=nSL$END[33]) |> mutate(nSL_start=nSL$START[33], nSL_end=nSL$END[33], nSL_pop=nSL$POP[33]),
    filter(gene.gff3, seqid==nSL$CHROM[34], start>=nSL$START[34] & end<=nSL$END[34]) |> mutate(nSL_start=nSL$START[34], nSL_end=nSL$END[34], nSL_pop=nSL$POP[34]),
    filter(gene.gff3, seqid==nSL$CHROM[35], start>=nSL$START[35] & end<=nSL$END[35]) |> mutate(nSL_start=nSL$START[35], nSL_end=nSL$END[35], nSL_pop=nSL$POP[35]),
    filter(gene.gff3, seqid==nSL$CHROM[36], start>=nSL$START[36] & end<=nSL$END[36]) |> mutate(nSL_start=nSL$START[36], nSL_end=nSL$END[36], nSL_pop=nSL$POP[36]),
    filter(gene.gff3, seqid==nSL$CHROM[37], start>=nSL$START[37] & end<=nSL$END[37]) |> mutate(nSL_start=nSL$START[37], nSL_end=nSL$END[37], nSL_pop=nSL$POP[37]),
    filter(gene.gff3, seqid==nSL$CHROM[38], start>=nSL$START[38] & end<=nSL$END[38]) |> mutate(nSL_start=nSL$START[38], nSL_end=nSL$END[38], nSL_pop=nSL$POP[38]),
    filter(gene.gff3, seqid==nSL$CHROM[39], start>=nSL$START[39] & end<=nSL$END[39]) |> mutate(nSL_start=nSL$START[39], nSL_end=nSL$END[39], nSL_pop=nSL$POP[39]),
    filter(gene.gff3, seqid==nSL$CHROM[40], start>=nSL$START[40] & end<=nSL$END[40]) |> mutate(nSL_start=nSL$START[40], nSL_end=nSL$END[40], nSL_pop=nSL$POP[40]),
    filter(gene.gff3, seqid==nSL$CHROM[41], start>=nSL$START[41] & end<=nSL$END[41]) |> mutate(nSL_start=nSL$START[41], nSL_end=nSL$END[41], nSL_pop=nSL$POP[41]),
    filter(gene.gff3, seqid==nSL$CHROM[42], start>=nSL$START[42] & end<=nSL$END[42]) |> mutate(nSL_start=nSL$START[42], nSL_end=nSL$END[42], nSL_pop=nSL$POP[42]),
    filter(gene.gff3, seqid==nSL$CHROM[43], start>=nSL$START[43] & end<=nSL$END[43]) |> mutate(nSL_start=nSL$START[43], nSL_end=nSL$END[43], nSL_pop=nSL$POP[43]),
    filter(gene.gff3, seqid==nSL$CHROM[44], start>=nSL$START[44] & end<=nSL$END[44]) |> mutate(nSL_start=nSL$START[44], nSL_end=nSL$END[44], nSL_pop=nSL$POP[44]),
    filter(gene.gff3, seqid==nSL$CHROM[45], start>=nSL$START[45] & end<=nSL$END[45]) |> mutate(nSL_start=nSL$START[45], nSL_end=nSL$END[45], nSL_pop=nSL$POP[45]),
    filter(gene.gff3, seqid==nSL$CHROM[46], start>=nSL$START[46] & end<=nSL$END[46]) |> mutate(nSL_start=nSL$START[46], nSL_end=nSL$END[46], nSL_pop=nSL$POP[46]),
    filter(gene.gff3, seqid==nSL$CHROM[47], start>=nSL$START[47] & end<=nSL$END[47]) |> mutate(nSL_start=nSL$START[47], nSL_end=nSL$END[47], nSL_pop=nSL$POP[47]),
    filter(gene.gff3, seqid==nSL$CHROM[48], start>=nSL$START[48] & end<=nSL$END[48]) |> mutate(nSL_start=nSL$START[48], nSL_end=nSL$END[48], nSL_pop=nSL$POP[48]),
    filter(gene.gff3, seqid==nSL$CHROM[49], start>=nSL$START[49] & end<=nSL$END[49]) |> mutate(nSL_start=nSL$START[49], nSL_end=nSL$END[49], nSL_pop=nSL$POP[49]),
    filter(gene.gff3, seqid==nSL$CHROM[50], start>=nSL$START[50] & end<=nSL$END[50]) |> mutate(nSL_start=nSL$START[50], nSL_end=nSL$END[50], nSL_pop=nSL$POP[50]),
    filter(gene.gff3, seqid==nSL$CHROM[51], start>=nSL$START[51] & end<=nSL$END[51]) |> mutate(nSL_start=nSL$START[51], nSL_end=nSL$END[51], nSL_pop=nSL$POP[51]),
    filter(gene.gff3, seqid==nSL$CHROM[52], start>=nSL$START[52] & end<=nSL$END[52]) |> mutate(nSL_start=nSL$START[52], nSL_end=nSL$END[52], nSL_pop=nSL$POP[52]),
    filter(gene.gff3, seqid==nSL$CHROM[53], start>=nSL$START[53] & end<=nSL$END[53]) |> mutate(nSL_start=nSL$START[53], nSL_end=nSL$END[53], nSL_pop=nSL$POP[53]),
    filter(gene.gff3, seqid==nSL$CHROM[54], start>=nSL$START[54] & end<=nSL$END[54]) |> mutate(nSL_start=nSL$START[54], nSL_end=nSL$END[54], nSL_pop=nSL$POP[54]),
    filter(gene.gff3, seqid==nSL$CHROM[55], start>=nSL$START[55] & end<=nSL$END[55]) |> mutate(nSL_start=nSL$START[55], nSL_end=nSL$END[55], nSL_pop=nSL$POP[55]),
    filter(gene.gff3, seqid==nSL$CHROM[56], start>=nSL$START[56] & end<=nSL$END[56]) |> mutate(nSL_start=nSL$START[56], nSL_end=nSL$END[56], nSL_pop=nSL$POP[56]),
    filter(gene.gff3, seqid==nSL$CHROM[57], start>=nSL$START[57] & end<=nSL$END[57]) |> mutate(nSL_start=nSL$START[57], nSL_end=nSL$END[57], nSL_pop=nSL$POP[57]),
    filter(gene.gff3, seqid==nSL$CHROM[58], start>=nSL$START[58] & end<=nSL$END[58]) |> mutate(nSL_start=nSL$START[58], nSL_end=nSL$END[58], nSL_pop=nSL$POP[58]),
    filter(gene.gff3, seqid==nSL$CHROM[59], start>=nSL$START[59] & end<=nSL$END[59]) |> mutate(nSL_start=nSL$START[59], nSL_end=nSL$END[59], nSL_pop=nSL$POP[59]),
    filter(gene.gff3, seqid==nSL$CHROM[60], start>=nSL$START[60] & end<=nSL$END[60]) |> mutate(nSL_start=nSL$START[60], nSL_end=nSL$END[60], nSL_pop=nSL$POP[60]),
    filter(gene.gff3, seqid==nSL$CHROM[61], start>=nSL$START[61] & end<=nSL$END[61]) |> mutate(nSL_start=nSL$START[61], nSL_end=nSL$END[61], nSL_pop=nSL$POP[61]),
    filter(gene.gff3, seqid==nSL$CHROM[62], start>=nSL$START[62] & end<=nSL$END[62]) |> mutate(nSL_start=nSL$START[62], nSL_end=nSL$END[62], nSL_pop=nSL$POP[62]),
    filter(gene.gff3, seqid==nSL$CHROM[63], start>=nSL$START[63] & end<=nSL$END[63]) |> mutate(nSL_start=nSL$START[63], nSL_end=nSL$END[63], nSL_pop=nSL$POP[63]),
    filter(gene.gff3, seqid==nSL$CHROM[64], start>=nSL$START[64] & end<=nSL$END[64]) |> mutate(nSL_start=nSL$START[64], nSL_end=nSL$END[64], nSL_pop=nSL$POP[64]),
    filter(gene.gff3, seqid==nSL$CHROM[65], start>=nSL$START[65] & end<=nSL$END[65]) |> mutate(nSL_start=nSL$START[65], nSL_end=nSL$END[65], nSL_pop=nSL$POP[65]),
    filter(gene.gff3, seqid==nSL$CHROM[66], start>=nSL$START[66] & end<=nSL$END[66]) |> mutate(nSL_start=nSL$START[66], nSL_end=nSL$END[66], nSL_pop=nSL$POP[66]),
    filter(gene.gff3, seqid==nSL$CHROM[67], start>=nSL$START[67] & end<=nSL$END[67]) |> mutate(nSL_start=nSL$START[67], nSL_end=nSL$END[67], nSL_pop=nSL$POP[67]),
    filter(gene.gff3, seqid==nSL$CHROM[68], start>=nSL$START[68] & end<=nSL$END[68]) |> mutate(nSL_start=nSL$START[68], nSL_end=nSL$END[68], nSL_pop=nSL$POP[68]),
    filter(gene.gff3, seqid==nSL$CHROM[69], start>=nSL$START[69] & end<=nSL$END[69]) |> mutate(nSL_start=nSL$START[69], nSL_end=nSL$END[69], nSL_pop=nSL$POP[69]),
    filter(gene.gff3, seqid==nSL$CHROM[70], start>=nSL$START[70] & end<=nSL$END[70]) |> mutate(nSL_start=nSL$START[70], nSL_end=nSL$END[70], nSL_pop=nSL$POP[70]),
    filter(gene.gff3, seqid==nSL$CHROM[71], start>=nSL$START[71] & end<=nSL$END[71]) |> mutate(nSL_start=nSL$START[71], nSL_end=nSL$END[71], nSL_pop=nSL$POP[71]),
    filter(gene.gff3, seqid==nSL$CHROM[72], start>=nSL$START[72] & end<=nSL$END[72]) |> mutate(nSL_start=nSL$START[72], nSL_end=nSL$END[72], nSL_pop=nSL$POP[72]),
    filter(gene.gff3, seqid==nSL$CHROM[73], start>=nSL$START[73] & end<=nSL$END[73]) |> mutate(nSL_start=nSL$START[73], nSL_end=nSL$END[73], nSL_pop=nSL$POP[73]),
    filter(gene.gff3, seqid==nSL$CHROM[74], start>=nSL$START[74] & end<=nSL$END[74]) |> mutate(nSL_start=nSL$START[74], nSL_end=nSL$END[74], nSL_pop=nSL$POP[74]),
    filter(gene.gff3, seqid==nSL$CHROM[75], start>=nSL$START[75] & end<=nSL$END[75]) |> mutate(nSL_start=nSL$START[75], nSL_end=nSL$END[75], nSL_pop=nSL$POP[75]),
    filter(gene.gff3, seqid==nSL$CHROM[76], start>=nSL$START[76] & end<=nSL$END[76]) |> mutate(nSL_start=nSL$START[76], nSL_end=nSL$END[76], nSL_pop=nSL$POP[76]),
    filter(gene.gff3, seqid==nSL$CHROM[77], start>=nSL$START[77] & end<=nSL$END[77]) |> mutate(nSL_start=nSL$START[77], nSL_end=nSL$END[77], nSL_pop=nSL$POP[77]),
    filter(gene.gff3, seqid==nSL$CHROM[78], start>=nSL$START[78] & end<=nSL$END[78]) |> mutate(nSL_start=nSL$START[78], nSL_end=nSL$END[78], nSL_pop=nSL$POP[78]),
    filter(gene.gff3, seqid==nSL$CHROM[79], start>=nSL$START[79] & end<=nSL$END[79]) |> mutate(nSL_start=nSL$START[79], nSL_end=nSL$END[79], nSL_pop=nSL$POP[79]),
    filter(gene.gff3, seqid==nSL$CHROM[80], start>=nSL$START[80] & end<=nSL$END[80]) |> mutate(nSL_start=nSL$START[80], nSL_end=nSL$END[80], nSL_pop=nSL$POP[80]),
    filter(gene.gff3, seqid==nSL$CHROM[81], start>=nSL$START[81] & end<=nSL$END[81]) |> mutate(nSL_start=nSL$START[81], nSL_end=nSL$END[81], nSL_pop=nSL$POP[81]),
    filter(gene.gff3, seqid==nSL$CHROM[82], start>=nSL$START[82] & end<=nSL$END[82]) |> mutate(nSL_start=nSL$START[82], nSL_end=nSL$END[82], nSL_pop=nSL$POP[82]),
    filter(gene.gff3, seqid==nSL$CHROM[83], start>=nSL$START[83] & end<=nSL$END[83]) |> mutate(nSL_start=nSL$START[83], nSL_end=nSL$END[83], nSL_pop=nSL$POP[83]),
    filter(gene.gff3, seqid==nSL$CHROM[84], start>=nSL$START[84] & end<=nSL$END[84]) |> mutate(nSL_start=nSL$START[84], nSL_end=nSL$END[84], nSL_pop=nSL$POP[84]),
    filter(gene.gff3, seqid==nSL$CHROM[85], start>=nSL$START[85] & end<=nSL$END[85]) |> mutate(nSL_start=nSL$START[85], nSL_end=nSL$END[85], nSL_pop=nSL$POP[85]),
    filter(gene.gff3, seqid==nSL$CHROM[86], start>=nSL$START[86] & end<=nSL$END[86]) |> mutate(nSL_start=nSL$START[86], nSL_end=nSL$END[86], nSL_pop=nSL$POP[86]),
    filter(gene.gff3, seqid==nSL$CHROM[87], start>=nSL$START[87] & end<=nSL$END[87]) |> mutate(nSL_start=nSL$START[87], nSL_end=nSL$END[87], nSL_pop=nSL$POP[87]),
    filter(gene.gff3, seqid==nSL$CHROM[88], start>=nSL$START[88] & end<=nSL$END[88]) |> mutate(nSL_start=nSL$START[88], nSL_end=nSL$END[88], nSL_pop=nSL$POP[88]),
    filter(gene.gff3, seqid==nSL$CHROM[89], start>=nSL$START[89] & end<=nSL$END[89]) |> mutate(nSL_start=nSL$START[89], nSL_end=nSL$END[89], nSL_pop=nSL$POP[89]),
    filter(gene.gff3, seqid==nSL$CHROM[90], start>=nSL$START[90] & end<=nSL$END[90]) |> mutate(nSL_start=nSL$START[90], nSL_end=nSL$END[90], nSL_pop=nSL$POP[90]),
    filter(gene.gff3, seqid==nSL$CHROM[91], start>=nSL$START[91] & end<=nSL$END[91]) |> mutate(nSL_start=nSL$START[91], nSL_end=nSL$END[91], nSL_pop=nSL$POP[91]),
    filter(gene.gff3, seqid==nSL$CHROM[92], start>=nSL$START[92] & end<=nSL$END[92]) |> mutate(nSL_start=nSL$START[92], nSL_end=nSL$END[92], nSL_pop=nSL$POP[92]),
    filter(gene.gff3, seqid==nSL$CHROM[93], start>=nSL$START[93] & end<=nSL$END[93]) |> mutate(nSL_start=nSL$START[93], nSL_end=nSL$END[93], nSL_pop=nSL$POP[93]),
    filter(gene.gff3, seqid==nSL$CHROM[94], start>=nSL$START[94] & end<=nSL$END[94]) |> mutate(nSL_start=nSL$START[94], nSL_end=nSL$END[94], nSL_pop=nSL$POP[94]),
    filter(gene.gff3, seqid==nSL$CHROM[95], start>=nSL$START[95] & end<=nSL$END[95]) |> mutate(nSL_start=nSL$START[95], nSL_end=nSL$END[95], nSL_pop=nSL$POP[95]),
    filter(gene.gff3, seqid==nSL$CHROM[96], start>=nSL$START[96] & end<=nSL$END[96]) |> mutate(nSL_start=nSL$START[96], nSL_end=nSL$END[96], nSL_pop=nSL$POP[96]),
    filter(gene.gff3, seqid==nSL$CHROM[97], start>=nSL$START[97] & end<=nSL$END[97]) |> mutate(nSL_start=nSL$START[97], nSL_end=nSL$END[97], nSL_pop=nSL$POP[97]),
    filter(gene.gff3, seqid==nSL$CHROM[98], start>=nSL$START[98] & end<=nSL$END[98]) |> mutate(nSL_start=nSL$START[98], nSL_end=nSL$END[98], nSL_pop=nSL$POP[98]),
    filter(gene.gff3, seqid==nSL$CHROM[99], start>=nSL$START[99] & end<=nSL$END[99]) |> mutate(nSL_start=nSL$START[99], nSL_end=nSL$END[99], nSL_pop=nSL$POP[99]),
    filter(gene.gff3, seqid==nSL$CHROM[100], start>=nSL$START[100] & end<=nSL$END[100]) |> mutate(nSL_start=nSL$START[100], nSL_end=nSL$END[100], nSL_pop=nSL$POP[100]),
    filter(gene.gff3, seqid==nSL$CHROM[101], start>=nSL$START[101] & end<=nSL$END[101]) |> mutate(nSL_start=nSL$START[101], nSL_end=nSL$END[101], nSL_pop=nSL$POP[101]),
    filter(gene.gff3, seqid==nSL$CHROM[102], start>=nSL$START[102] & end<=nSL$END[102]) |> mutate(nSL_start=nSL$START[102], nSL_end=nSL$END[102], nSL_pop=nSL$POP[102]),
    filter(gene.gff3, seqid==nSL$CHROM[103], start>=nSL$START[103] & end<=nSL$END[103]) |> mutate(nSL_start=nSL$START[103], nSL_end=nSL$END[103], nSL_pop=nSL$POP[103]),
    filter(gene.gff3, seqid==nSL$CHROM[104], start>=nSL$START[104] & end<=nSL$END[104]) |> mutate(nSL_start=nSL$START[104], nSL_end=nSL$END[104], nSL_pop=nSL$POP[104]),
    filter(gene.gff3, seqid==nSL$CHROM[105], start>=nSL$START[105] & end<=nSL$END[105]) |> mutate(nSL_start=nSL$START[105], nSL_end=nSL$END[105], nSL_pop=nSL$POP[105]),
    filter(gene.gff3, seqid==nSL$CHROM[106], start>=nSL$START[106] & end<=nSL$END[106]) |> mutate(nSL_start=nSL$START[106], nSL_end=nSL$END[106], nSL_pop=nSL$POP[106]),
    filter(gene.gff3, seqid==nSL$CHROM[107], start>=nSL$START[107] & end<=nSL$END[107]) |> mutate(nSL_start=nSL$START[107], nSL_end=nSL$END[107], nSL_pop=nSL$POP[107]),
    filter(gene.gff3, seqid==nSL$CHROM[108], start>=nSL$START[108] & end<=nSL$END[108]) |> mutate(nSL_start=nSL$START[108], nSL_end=nSL$END[108], nSL_pop=nSL$POP[108]),
    filter(gene.gff3, seqid==nSL$CHROM[109], start>=nSL$START[109] & end<=nSL$END[109]) |> mutate(nSL_start=nSL$START[109], nSL_end=nSL$END[109], nSL_pop=nSL$POP[109]),
    filter(gene.gff3, seqid==nSL$CHROM[110], start>=nSL$START[110] & end<=nSL$END[110]) |> mutate(nSL_start=nSL$START[110], nSL_end=nSL$END[110], nSL_pop=nSL$POP[110]),
    filter(gene.gff3, seqid==nSL$CHROM[111], start>=nSL$START[111] & end<=nSL$END[111]) |> mutate(nSL_start=nSL$START[111], nSL_end=nSL$END[111], nSL_pop=nSL$POP[111]),
    filter(gene.gff3, seqid==nSL$CHROM[112], start>=nSL$START[112] & end<=nSL$END[112]) |> mutate(nSL_start=nSL$START[112], nSL_end=nSL$END[112], nSL_pop=nSL$POP[112]),
    filter(gene.gff3, seqid==nSL$CHROM[113], start>=nSL$START[113] & end<=nSL$END[113]) |> mutate(nSL_start=nSL$START[113], nSL_end=nSL$END[113], nSL_pop=nSL$POP[113]),
    filter(gene.gff3, seqid==nSL$CHROM[114], start>=nSL$START[114] & end<=nSL$END[114]) |> mutate(nSL_start=nSL$START[114], nSL_end=nSL$END[114], nSL_pop=nSL$POP[114]),
    filter(gene.gff3, seqid==nSL$CHROM[115], start>=nSL$START[115] & end<=nSL$END[115]) |> mutate(nSL_start=nSL$START[115], nSL_end=nSL$END[115], nSL_pop=nSL$POP[115]),
    filter(gene.gff3, seqid==nSL$CHROM[116], start>=nSL$START[116] & end<=nSL$END[116]) |> mutate(nSL_start=nSL$START[116], nSL_end=nSL$END[116], nSL_pop=nSL$POP[116]),
    filter(gene.gff3, seqid==nSL$CHROM[117], start>=nSL$START[117] & end<=nSL$END[117]) |> mutate(nSL_start=nSL$START[117], nSL_end=nSL$END[117], nSL_pop=nSL$POP[117]),
    filter(gene.gff3, seqid==nSL$CHROM[118], start>=nSL$START[118] & end<=nSL$END[118]) |> mutate(nSL_start=nSL$START[118], nSL_end=nSL$END[118], nSL_pop=nSL$POP[118]),
    .id="outlier")
genes.within.regions


genes.starting.in.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==nSL$CHROM[1], between(start, left=nSL$START[1], right=nSL$END[1])) |> mutate(nSL_start=nSL$START[1], nSL_end=nSL$END[1], nSL_pop=nSL$POP[1]),
    filter(gene.gff3, seqid==nSL$CHROM[2], between(start, left=nSL$START[2], right=nSL$END[2])) |> mutate(nSL_start=nSL$START[2], nSL_end=nSL$END[2], nSL_pop=nSL$POP[2]),
    filter(gene.gff3, seqid==nSL$CHROM[3], between(start, left=nSL$START[3], right=nSL$END[3])) |> mutate(nSL_start=nSL$START[3], nSL_end=nSL$END[3], nSL_pop=nSL$POP[3]),
    filter(gene.gff3, seqid==nSL$CHROM[4], between(start, left=nSL$START[4], right=nSL$END[4])) |> mutate(nSL_start=nSL$START[4], nSL_end=nSL$END[4], nSL_pop=nSL$POP[4]),
    filter(gene.gff3, seqid==nSL$CHROM[5], between(start, left=nSL$START[5], right=nSL$END[5])) |> mutate(nSL_start=nSL$START[5], nSL_end=nSL$END[5], nSL_pop=nSL$POP[5]),
    filter(gene.gff3, seqid==nSL$CHROM[6], between(start, left=nSL$START[6], right=nSL$END[6])) |> mutate(nSL_start=nSL$START[6], nSL_end=nSL$END[6], nSL_pop=nSL$POP[6]),
    filter(gene.gff3, seqid==nSL$CHROM[7], between(start, left=nSL$START[7], right=nSL$END[7])) |> mutate(nSL_start=nSL$START[7], nSL_end=nSL$END[7], nSL_pop=nSL$POP[7]),
    filter(gene.gff3, seqid==nSL$CHROM[8], between(start, left=nSL$START[8], right=nSL$END[8])) |> mutate(nSL_start=nSL$START[8], nSL_end=nSL$END[8], nSL_pop=nSL$POP[8]),
    filter(gene.gff3, seqid==nSL$CHROM[9], between(start, left=nSL$START[9], right=nSL$END[9])) |> mutate(nSL_start=nSL$START[9], nSL_end=nSL$END[9], nSL_pop=nSL$POP[9]),
    filter(gene.gff3, seqid==nSL$CHROM[10], between(start, left=nSL$START[10], right=nSL$END[10])) |> mutate(nSL_start=nSL$START[10], nSL_end=nSL$END[10], nSL_pop=nSL$POP[10]),
    filter(gene.gff3, seqid==nSL$CHROM[11], between(start, left=nSL$START[11], right=nSL$END[11])) |> mutate(nSL_start=nSL$START[11], nSL_end=nSL$END[11], nSL_pop=nSL$POP[11]),
    filter(gene.gff3, seqid==nSL$CHROM[12], between(start, left=nSL$START[12], right=nSL$END[12])) |> mutate(nSL_start=nSL$START[12], nSL_end=nSL$END[12], nSL_pop=nSL$POP[12]),
    filter(gene.gff3, seqid==nSL$CHROM[13], between(start, left=nSL$START[13], right=nSL$END[13])) |> mutate(nSL_start=nSL$START[13], nSL_end=nSL$END[13], nSL_pop=nSL$POP[13]),
    filter(gene.gff3, seqid==nSL$CHROM[14], between(start, left=nSL$START[14], right=nSL$END[14])) |> mutate(nSL_start=nSL$START[14], nSL_end=nSL$END[14], nSL_pop=nSL$POP[14]),
    filter(gene.gff3, seqid==nSL$CHROM[15], between(start, left=nSL$START[15], right=nSL$END[15])) |> mutate(nSL_start=nSL$START[15], nSL_end=nSL$END[15], nSL_pop=nSL$POP[15]),
    filter(gene.gff3, seqid==nSL$CHROM[16], between(start, left=nSL$START[16], right=nSL$END[16])) |> mutate(nSL_start=nSL$START[16], nSL_end=nSL$END[16], nSL_pop=nSL$POP[16]),
    filter(gene.gff3, seqid==nSL$CHROM[17], between(start, left=nSL$START[17], right=nSL$END[17])) |> mutate(nSL_start=nSL$START[17], nSL_end=nSL$END[17], nSL_pop=nSL$POP[17]),
    filter(gene.gff3, seqid==nSL$CHROM[18], between(start, left=nSL$START[18], right=nSL$END[18])) |> mutate(nSL_start=nSL$START[18], nSL_end=nSL$END[18], nSL_pop=nSL$POP[18]),
    filter(gene.gff3, seqid==nSL$CHROM[19], between(start, left=nSL$START[19], right=nSL$END[19])) |> mutate(nSL_start=nSL$START[19], nSL_end=nSL$END[19], nSL_pop=nSL$POP[19]),
    filter(gene.gff3, seqid==nSL$CHROM[20], between(start, left=nSL$START[20], right=nSL$END[20])) |> mutate(nSL_start=nSL$START[20], nSL_end=nSL$END[20], nSL_pop=nSL$POP[20]),
    filter(gene.gff3, seqid==nSL$CHROM[21], between(start, left=nSL$START[21], right=nSL$END[21])) |> mutate(nSL_start=nSL$START[21], nSL_end=nSL$END[21], nSL_pop=nSL$POP[21]),
    filter(gene.gff3, seqid==nSL$CHROM[22], between(start, left=nSL$START[22], right=nSL$END[22])) |> mutate(nSL_start=nSL$START[22], nSL_end=nSL$END[22], nSL_pop=nSL$POP[22]),
    filter(gene.gff3, seqid==nSL$CHROM[23], between(start, left=nSL$START[23], right=nSL$END[23])) |> mutate(nSL_start=nSL$START[23], nSL_end=nSL$END[23], nSL_pop=nSL$POP[23]),
    filter(gene.gff3, seqid==nSL$CHROM[24], between(start, left=nSL$START[24], right=nSL$END[24])) |> mutate(nSL_start=nSL$START[24], nSL_end=nSL$END[24], nSL_pop=nSL$POP[24]),
    filter(gene.gff3, seqid==nSL$CHROM[25], between(start, left=nSL$START[25], right=nSL$END[25])) |> mutate(nSL_start=nSL$START[25], nSL_end=nSL$END[25], nSL_pop=nSL$POP[25]),
    filter(gene.gff3, seqid==nSL$CHROM[26], between(start, left=nSL$START[26], right=nSL$END[26])) |> mutate(nSL_start=nSL$START[26], nSL_end=nSL$END[26], nSL_pop=nSL$POP[26]),
    filter(gene.gff3, seqid==nSL$CHROM[27], between(start, left=nSL$START[27], right=nSL$END[27])) |> mutate(nSL_start=nSL$START[27], nSL_end=nSL$END[27], nSL_pop=nSL$POP[27]),
    filter(gene.gff3, seqid==nSL$CHROM[28], between(start, left=nSL$START[28], right=nSL$END[28])) |> mutate(nSL_start=nSL$START[28], nSL_end=nSL$END[28], nSL_pop=nSL$POP[28]),
    filter(gene.gff3, seqid==nSL$CHROM[29], between(start, left=nSL$START[29], right=nSL$END[29])) |> mutate(nSL_start=nSL$START[29], nSL_end=nSL$END[29], nSL_pop=nSL$POP[29]),
    filter(gene.gff3, seqid==nSL$CHROM[30], between(start, left=nSL$START[30], right=nSL$END[30])) |> mutate(nSL_start=nSL$START[30], nSL_end=nSL$END[30], nSL_pop=nSL$POP[30]),
    filter(gene.gff3, seqid==nSL$CHROM[31], between(start, left=nSL$START[31], right=nSL$END[31])) |> mutate(nSL_start=nSL$START[31], nSL_end=nSL$END[31], nSL_pop=nSL$POP[31]),
    filter(gene.gff3, seqid==nSL$CHROM[32], between(start, left=nSL$START[32], right=nSL$END[32])) |> mutate(nSL_start=nSL$START[32], nSL_end=nSL$END[32], nSL_pop=nSL$POP[32]),
    filter(gene.gff3, seqid==nSL$CHROM[33], between(start, left=nSL$START[33], right=nSL$END[33])) |> mutate(nSL_start=nSL$START[33], nSL_end=nSL$END[33], nSL_pop=nSL$POP[33]),
    filter(gene.gff3, seqid==nSL$CHROM[34], between(start, left=nSL$START[34], right=nSL$END[34])) |> mutate(nSL_start=nSL$START[34], nSL_end=nSL$END[34], nSL_pop=nSL$POP[34]),
    filter(gene.gff3, seqid==nSL$CHROM[35], between(start, left=nSL$START[35], right=nSL$END[35])) |> mutate(nSL_start=nSL$START[35], nSL_end=nSL$END[35], nSL_pop=nSL$POP[35]),
    filter(gene.gff3, seqid==nSL$CHROM[36], between(start, left=nSL$START[36], right=nSL$END[36])) |> mutate(nSL_start=nSL$START[36], nSL_end=nSL$END[36], nSL_pop=nSL$POP[36]),
    filter(gene.gff3, seqid==nSL$CHROM[37], between(start, left=nSL$START[37], right=nSL$END[37])) |> mutate(nSL_start=nSL$START[37], nSL_end=nSL$END[37], nSL_pop=nSL$POP[37]),
    filter(gene.gff3, seqid==nSL$CHROM[38], between(start, left=nSL$START[38], right=nSL$END[38])) |> mutate(nSL_start=nSL$START[38], nSL_end=nSL$END[38], nSL_pop=nSL$POP[38]),
    filter(gene.gff3, seqid==nSL$CHROM[39], between(start, left=nSL$START[39], right=nSL$END[39])) |> mutate(nSL_start=nSL$START[39], nSL_end=nSL$END[39], nSL_pop=nSL$POP[39]),
    filter(gene.gff3, seqid==nSL$CHROM[40], between(start, left=nSL$START[40], right=nSL$END[40])) |> mutate(nSL_start=nSL$START[40], nSL_end=nSL$END[40], nSL_pop=nSL$POP[40]),
    filter(gene.gff3, seqid==nSL$CHROM[41], between(start, left=nSL$START[41], right=nSL$END[41])) |> mutate(nSL_start=nSL$START[41], nSL_end=nSL$END[41], nSL_pop=nSL$POP[41]),
    filter(gene.gff3, seqid==nSL$CHROM[42], between(start, left=nSL$START[42], right=nSL$END[42])) |> mutate(nSL_start=nSL$START[42], nSL_end=nSL$END[42], nSL_pop=nSL$POP[42]),
    filter(gene.gff3, seqid==nSL$CHROM[43], between(start, left=nSL$START[43], right=nSL$END[43])) |> mutate(nSL_start=nSL$START[43], nSL_end=nSL$END[43], nSL_pop=nSL$POP[43]),
    filter(gene.gff3, seqid==nSL$CHROM[44], between(start, left=nSL$START[44], right=nSL$END[44])) |> mutate(nSL_start=nSL$START[44], nSL_end=nSL$END[44], nSL_pop=nSL$POP[44]),
    filter(gene.gff3, seqid==nSL$CHROM[45], between(start, left=nSL$START[45], right=nSL$END[45])) |> mutate(nSL_start=nSL$START[45], nSL_end=nSL$END[45], nSL_pop=nSL$POP[45]),
    filter(gene.gff3, seqid==nSL$CHROM[46], between(start, left=nSL$START[46], right=nSL$END[46])) |> mutate(nSL_start=nSL$START[46], nSL_end=nSL$END[46], nSL_pop=nSL$POP[46]),
    filter(gene.gff3, seqid==nSL$CHROM[47], between(start, left=nSL$START[47], right=nSL$END[47])) |> mutate(nSL_start=nSL$START[47], nSL_end=nSL$END[47], nSL_pop=nSL$POP[47]),
    filter(gene.gff3, seqid==nSL$CHROM[48], between(start, left=nSL$START[48], right=nSL$END[48])) |> mutate(nSL_start=nSL$START[48], nSL_end=nSL$END[48], nSL_pop=nSL$POP[48]),
    filter(gene.gff3, seqid==nSL$CHROM[49], between(start, left=nSL$START[49], right=nSL$END[49])) |> mutate(nSL_start=nSL$START[49], nSL_end=nSL$END[49], nSL_pop=nSL$POP[49]),
    filter(gene.gff3, seqid==nSL$CHROM[50], between(start, left=nSL$START[50], right=nSL$END[50])) |> mutate(nSL_start=nSL$START[50], nSL_end=nSL$END[50], nSL_pop=nSL$POP[50]),
    filter(gene.gff3, seqid==nSL$CHROM[51], between(start, left=nSL$START[51], right=nSL$END[51])) |> mutate(nSL_start=nSL$START[51], nSL_end=nSL$END[51], nSL_pop=nSL$POP[51]),
    filter(gene.gff3, seqid==nSL$CHROM[52], between(start, left=nSL$START[52], right=nSL$END[52])) |> mutate(nSL_start=nSL$START[52], nSL_end=nSL$END[52], nSL_pop=nSL$POP[52]),
    filter(gene.gff3, seqid==nSL$CHROM[53], between(start, left=nSL$START[53], right=nSL$END[53])) |> mutate(nSL_start=nSL$START[53], nSL_end=nSL$END[53], nSL_pop=nSL$POP[53]),
    filter(gene.gff3, seqid==nSL$CHROM[54], between(start, left=nSL$START[54], right=nSL$END[54])) |> mutate(nSL_start=nSL$START[54], nSL_end=nSL$END[54], nSL_pop=nSL$POP[54]),
    filter(gene.gff3, seqid==nSL$CHROM[55], between(start, left=nSL$START[55], right=nSL$END[55])) |> mutate(nSL_start=nSL$START[55], nSL_end=nSL$END[55], nSL_pop=nSL$POP[55]),
    filter(gene.gff3, seqid==nSL$CHROM[56], between(start, left=nSL$START[56], right=nSL$END[56])) |> mutate(nSL_start=nSL$START[56], nSL_end=nSL$END[56], nSL_pop=nSL$POP[56]),
    filter(gene.gff3, seqid==nSL$CHROM[57], between(start, left=nSL$START[57], right=nSL$END[57])) |> mutate(nSL_start=nSL$START[57], nSL_end=nSL$END[57], nSL_pop=nSL$POP[57]),
    filter(gene.gff3, seqid==nSL$CHROM[58], between(start, left=nSL$START[58], right=nSL$END[58])) |> mutate(nSL_start=nSL$START[58], nSL_end=nSL$END[58], nSL_pop=nSL$POP[58]),
    filter(gene.gff3, seqid==nSL$CHROM[59], between(start, left=nSL$START[59], right=nSL$END[59])) |> mutate(nSL_start=nSL$START[59], nSL_end=nSL$END[59], nSL_pop=nSL$POP[59]),
    filter(gene.gff3, seqid==nSL$CHROM[60], between(start, left=nSL$START[60], right=nSL$END[60])) |> mutate(nSL_start=nSL$START[60], nSL_end=nSL$END[60], nSL_pop=nSL$POP[60]),
    filter(gene.gff3, seqid==nSL$CHROM[61], between(start, left=nSL$START[61], right=nSL$END[61])) |> mutate(nSL_start=nSL$START[61], nSL_end=nSL$END[61], nSL_pop=nSL$POP[61]),
    filter(gene.gff3, seqid==nSL$CHROM[62], between(start, left=nSL$START[62], right=nSL$END[62])) |> mutate(nSL_start=nSL$START[62], nSL_end=nSL$END[62], nSL_pop=nSL$POP[62]),
    filter(gene.gff3, seqid==nSL$CHROM[63], between(start, left=nSL$START[63], right=nSL$END[63])) |> mutate(nSL_start=nSL$START[63], nSL_end=nSL$END[63], nSL_pop=nSL$POP[63]),
    filter(gene.gff3, seqid==nSL$CHROM[64], between(start, left=nSL$START[64], right=nSL$END[64])) |> mutate(nSL_start=nSL$START[64], nSL_end=nSL$END[64], nSL_pop=nSL$POP[64]),
    filter(gene.gff3, seqid==nSL$CHROM[65], between(start, left=nSL$START[65], right=nSL$END[65])) |> mutate(nSL_start=nSL$START[65], nSL_end=nSL$END[65], nSL_pop=nSL$POP[65]),
    filter(gene.gff3, seqid==nSL$CHROM[66], between(start, left=nSL$START[66], right=nSL$END[66])) |> mutate(nSL_start=nSL$START[66], nSL_end=nSL$END[66], nSL_pop=nSL$POP[66]),
    filter(gene.gff3, seqid==nSL$CHROM[67], between(start, left=nSL$START[67], right=nSL$END[67])) |> mutate(nSL_start=nSL$START[67], nSL_end=nSL$END[67], nSL_pop=nSL$POP[67]),
    filter(gene.gff3, seqid==nSL$CHROM[68], between(start, left=nSL$START[68], right=nSL$END[68])) |> mutate(nSL_start=nSL$START[68], nSL_end=nSL$END[68], nSL_pop=nSL$POP[68]),
    filter(gene.gff3, seqid==nSL$CHROM[69], between(start, left=nSL$START[69], right=nSL$END[69])) |> mutate(nSL_start=nSL$START[69], nSL_end=nSL$END[69], nSL_pop=nSL$POP[69]),
    filter(gene.gff3, seqid==nSL$CHROM[70], between(start, left=nSL$START[70], right=nSL$END[70])) |> mutate(nSL_start=nSL$START[70], nSL_end=nSL$END[70], nSL_pop=nSL$POP[70]),
    filter(gene.gff3, seqid==nSL$CHROM[71], between(start, left=nSL$START[71], right=nSL$END[71])) |> mutate(nSL_start=nSL$START[71], nSL_end=nSL$END[71], nSL_pop=nSL$POP[71]),
    filter(gene.gff3, seqid==nSL$CHROM[72], between(start, left=nSL$START[72], right=nSL$END[72])) |> mutate(nSL_start=nSL$START[72], nSL_end=nSL$END[72], nSL_pop=nSL$POP[72]),
    filter(gene.gff3, seqid==nSL$CHROM[73], between(start, left=nSL$START[73], right=nSL$END[73])) |> mutate(nSL_start=nSL$START[73], nSL_end=nSL$END[73], nSL_pop=nSL$POP[73]),
    filter(gene.gff3, seqid==nSL$CHROM[74], between(start, left=nSL$START[74], right=nSL$END[74])) |> mutate(nSL_start=nSL$START[74], nSL_end=nSL$END[74], nSL_pop=nSL$POP[74]),
    filter(gene.gff3, seqid==nSL$CHROM[75], between(start, left=nSL$START[75], right=nSL$END[75])) |> mutate(nSL_start=nSL$START[75], nSL_end=nSL$END[75], nSL_pop=nSL$POP[75]),
    filter(gene.gff3, seqid==nSL$CHROM[76], between(start, left=nSL$START[76], right=nSL$END[76])) |> mutate(nSL_start=nSL$START[76], nSL_end=nSL$END[76], nSL_pop=nSL$POP[76]),
    filter(gene.gff3, seqid==nSL$CHROM[77], between(start, left=nSL$START[77], right=nSL$END[77])) |> mutate(nSL_start=nSL$START[77], nSL_end=nSL$END[77], nSL_pop=nSL$POP[77]),
    filter(gene.gff3, seqid==nSL$CHROM[78], between(start, left=nSL$START[78], right=nSL$END[78])) |> mutate(nSL_start=nSL$START[78], nSL_end=nSL$END[78], nSL_pop=nSL$POP[78]),
    filter(gene.gff3, seqid==nSL$CHROM[79], between(start, left=nSL$START[79], right=nSL$END[79])) |> mutate(nSL_start=nSL$START[79], nSL_end=nSL$END[79], nSL_pop=nSL$POP[79]),
    filter(gene.gff3, seqid==nSL$CHROM[80], between(start, left=nSL$START[80], right=nSL$END[80])) |> mutate(nSL_start=nSL$START[80], nSL_end=nSL$END[80], nSL_pop=nSL$POP[80]),
    filter(gene.gff3, seqid==nSL$CHROM[81], between(start, left=nSL$START[81], right=nSL$END[81])) |> mutate(nSL_start=nSL$START[81], nSL_end=nSL$END[81], nSL_pop=nSL$POP[81]),
    filter(gene.gff3, seqid==nSL$CHROM[82], between(start, left=nSL$START[82], right=nSL$END[82])) |> mutate(nSL_start=nSL$START[82], nSL_end=nSL$END[82], nSL_pop=nSL$POP[82]),
    filter(gene.gff3, seqid==nSL$CHROM[83], between(start, left=nSL$START[83], right=nSL$END[83])) |> mutate(nSL_start=nSL$START[83], nSL_end=nSL$END[83], nSL_pop=nSL$POP[83]),
    filter(gene.gff3, seqid==nSL$CHROM[84], between(start, left=nSL$START[84], right=nSL$END[84])) |> mutate(nSL_start=nSL$START[84], nSL_end=nSL$END[84], nSL_pop=nSL$POP[84]),
    filter(gene.gff3, seqid==nSL$CHROM[85], between(start, left=nSL$START[85], right=nSL$END[85])) |> mutate(nSL_start=nSL$START[85], nSL_end=nSL$END[85], nSL_pop=nSL$POP[85]),
    filter(gene.gff3, seqid==nSL$CHROM[86], between(start, left=nSL$START[86], right=nSL$END[86])) |> mutate(nSL_start=nSL$START[86], nSL_end=nSL$END[86], nSL_pop=nSL$POP[86]),
    filter(gene.gff3, seqid==nSL$CHROM[87], between(start, left=nSL$START[87], right=nSL$END[87])) |> mutate(nSL_start=nSL$START[87], nSL_end=nSL$END[87], nSL_pop=nSL$POP[87]),
    filter(gene.gff3, seqid==nSL$CHROM[88], between(start, left=nSL$START[88], right=nSL$END[88])) |> mutate(nSL_start=nSL$START[88], nSL_end=nSL$END[88], nSL_pop=nSL$POP[88]),
    filter(gene.gff3, seqid==nSL$CHROM[89], between(start, left=nSL$START[89], right=nSL$END[89])) |> mutate(nSL_start=nSL$START[89], nSL_end=nSL$END[89], nSL_pop=nSL$POP[89]),
    filter(gene.gff3, seqid==nSL$CHROM[90], between(start, left=nSL$START[90], right=nSL$END[90])) |> mutate(nSL_start=nSL$START[90], nSL_end=nSL$END[90], nSL_pop=nSL$POP[90]),
    filter(gene.gff3, seqid==nSL$CHROM[91], between(start, left=nSL$START[91], right=nSL$END[91])) |> mutate(nSL_start=nSL$START[91], nSL_end=nSL$END[91], nSL_pop=nSL$POP[91]),
    filter(gene.gff3, seqid==nSL$CHROM[92], between(start, left=nSL$START[92], right=nSL$END[92])) |> mutate(nSL_start=nSL$START[92], nSL_end=nSL$END[92], nSL_pop=nSL$POP[92]),
    filter(gene.gff3, seqid==nSL$CHROM[93], between(start, left=nSL$START[93], right=nSL$END[93])) |> mutate(nSL_start=nSL$START[93], nSL_end=nSL$END[93], nSL_pop=nSL$POP[93]),
    filter(gene.gff3, seqid==nSL$CHROM[94], between(start, left=nSL$START[94], right=nSL$END[94])) |> mutate(nSL_start=nSL$START[94], nSL_end=nSL$END[94], nSL_pop=nSL$POP[94]),
    filter(gene.gff3, seqid==nSL$CHROM[95], between(start, left=nSL$START[95], right=nSL$END[95])) |> mutate(nSL_start=nSL$START[95], nSL_end=nSL$END[95], nSL_pop=nSL$POP[95]),
    filter(gene.gff3, seqid==nSL$CHROM[96], between(start, left=nSL$START[96], right=nSL$END[96])) |> mutate(nSL_start=nSL$START[96], nSL_end=nSL$END[96], nSL_pop=nSL$POP[96]),
    filter(gene.gff3, seqid==nSL$CHROM[97], between(start, left=nSL$START[97], right=nSL$END[97])) |> mutate(nSL_start=nSL$START[97], nSL_end=nSL$END[97], nSL_pop=nSL$POP[97]),
    filter(gene.gff3, seqid==nSL$CHROM[98], between(start, left=nSL$START[98], right=nSL$END[98])) |> mutate(nSL_start=nSL$START[98], nSL_end=nSL$END[98], nSL_pop=nSL$POP[98]),
    filter(gene.gff3, seqid==nSL$CHROM[99], between(start, left=nSL$START[99], right=nSL$END[99])) |> mutate(nSL_start=nSL$START[99], nSL_end=nSL$END[99], nSL_pop=nSL$POP[99]),
    filter(gene.gff3, seqid==nSL$CHROM[100], between(start, left=nSL$START[100], right=nSL$END[100])) |> mutate(nSL_start=nSL$START[100], nSL_end=nSL$END[100], nSL_pop=nSL$POP[100]),
    filter(gene.gff3, seqid==nSL$CHROM[101], between(start, left=nSL$START[101], right=nSL$END[101])) |> mutate(nSL_start=nSL$START[101], nSL_end=nSL$END[101], nSL_pop=nSL$POP[101]),
    filter(gene.gff3, seqid==nSL$CHROM[102], between(start, left=nSL$START[102], right=nSL$END[102])) |> mutate(nSL_start=nSL$START[102], nSL_end=nSL$END[102], nSL_pop=nSL$POP[102]),
    filter(gene.gff3, seqid==nSL$CHROM[103], between(start, left=nSL$START[103], right=nSL$END[103])) |> mutate(nSL_start=nSL$START[103], nSL_end=nSL$END[103], nSL_pop=nSL$POP[103]),
    filter(gene.gff3, seqid==nSL$CHROM[104], between(start, left=nSL$START[104], right=nSL$END[104])) |> mutate(nSL_start=nSL$START[104], nSL_end=nSL$END[104], nSL_pop=nSL$POP[104]),
    filter(gene.gff3, seqid==nSL$CHROM[105], between(start, left=nSL$START[105], right=nSL$END[105])) |> mutate(nSL_start=nSL$START[105], nSL_end=nSL$END[105], nSL_pop=nSL$POP[105]),
    filter(gene.gff3, seqid==nSL$CHROM[106], between(start, left=nSL$START[106], right=nSL$END[106])) |> mutate(nSL_start=nSL$START[106], nSL_end=nSL$END[106], nSL_pop=nSL$POP[106]),
    filter(gene.gff3, seqid==nSL$CHROM[107], between(start, left=nSL$START[107], right=nSL$END[107])) |> mutate(nSL_start=nSL$START[107], nSL_end=nSL$END[107], nSL_pop=nSL$POP[107]),
    filter(gene.gff3, seqid==nSL$CHROM[108], between(start, left=nSL$START[108], right=nSL$END[108])) |> mutate(nSL_start=nSL$START[108], nSL_end=nSL$END[108], nSL_pop=nSL$POP[108]),
    filter(gene.gff3, seqid==nSL$CHROM[109], between(start, left=nSL$START[109], right=nSL$END[109])) |> mutate(nSL_start=nSL$START[109], nSL_end=nSL$END[109], nSL_pop=nSL$POP[109]),
    filter(gene.gff3, seqid==nSL$CHROM[110], between(start, left=nSL$START[110], right=nSL$END[110])) |> mutate(nSL_start=nSL$START[110], nSL_end=nSL$END[110], nSL_pop=nSL$POP[110]),
    filter(gene.gff3, seqid==nSL$CHROM[111], between(start, left=nSL$START[111], right=nSL$END[111])) |> mutate(nSL_start=nSL$START[111], nSL_end=nSL$END[111], nSL_pop=nSL$POP[111]),
    filter(gene.gff3, seqid==nSL$CHROM[112], between(start, left=nSL$START[112], right=nSL$END[112])) |> mutate(nSL_start=nSL$START[112], nSL_end=nSL$END[112], nSL_pop=nSL$POP[112]),
    filter(gene.gff3, seqid==nSL$CHROM[113], between(start, left=nSL$START[113], right=nSL$END[113])) |> mutate(nSL_start=nSL$START[113], nSL_end=nSL$END[113], nSL_pop=nSL$POP[113]),
    filter(gene.gff3, seqid==nSL$CHROM[114], between(start, left=nSL$START[114], right=nSL$END[114])) |> mutate(nSL_start=nSL$START[114], nSL_end=nSL$END[114], nSL_pop=nSL$POP[114]),
    filter(gene.gff3, seqid==nSL$CHROM[115], between(start, left=nSL$START[115], right=nSL$END[115])) |> mutate(nSL_start=nSL$START[115], nSL_end=nSL$END[115], nSL_pop=nSL$POP[115]),
    filter(gene.gff3, seqid==nSL$CHROM[116], between(start, left=nSL$START[116], right=nSL$END[116])) |> mutate(nSL_start=nSL$START[116], nSL_end=nSL$END[116], nSL_pop=nSL$POP[116]),
    filter(gene.gff3, seqid==nSL$CHROM[117], between(start, left=nSL$START[117], right=nSL$END[117])) |> mutate(nSL_start=nSL$START[117], nSL_end=nSL$END[117], nSL_pop=nSL$POP[117]),
    filter(gene.gff3, seqid==nSL$CHROM[118], between(start, left=nSL$START[118], right=nSL$END[118])) |> mutate(nSL_start=nSL$START[118], nSL_end=nSL$END[118], nSL_pop=nSL$POP[118]),
    .id="outlier")
genes.starting.in.regions

genes.ending.in.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==nSL$CHROM[1], between(end, left=nSL$START[1], right=nSL$END[1])) |> mutate(nSL_start=nSL$START[1], nSL_end=nSL$END[1], nSL_pop=nSL$POP[1]),
    filter(gene.gff3, seqid==nSL$CHROM[2], between(end, left=nSL$START[2], right=nSL$END[2])) |> mutate(nSL_start=nSL$START[2], nSL_end=nSL$END[2], nSL_pop=nSL$POP[2]),
    filter(gene.gff3, seqid==nSL$CHROM[3], between(end, left=nSL$START[3], right=nSL$END[3])) |> mutate(nSL_start=nSL$START[3], nSL_end=nSL$END[3], nSL_pop=nSL$POP[3]),
    filter(gene.gff3, seqid==nSL$CHROM[4], between(end, left=nSL$START[4], right=nSL$END[4])) |> mutate(nSL_start=nSL$START[4], nSL_end=nSL$END[4], nSL_pop=nSL$POP[4]),
    filter(gene.gff3, seqid==nSL$CHROM[5], between(end, left=nSL$START[5], right=nSL$END[5])) |> mutate(nSL_start=nSL$START[5], nSL_end=nSL$END[5], nSL_pop=nSL$POP[5]),
    filter(gene.gff3, seqid==nSL$CHROM[6], between(end, left=nSL$START[6], right=nSL$END[6])) |> mutate(nSL_start=nSL$START[6], nSL_end=nSL$END[6], nSL_pop=nSL$POP[6]),
    filter(gene.gff3, seqid==nSL$CHROM[7], between(end, left=nSL$START[7], right=nSL$END[7])) |> mutate(nSL_start=nSL$START[7], nSL_end=nSL$END[7], nSL_pop=nSL$POP[7]),
    filter(gene.gff3, seqid==nSL$CHROM[8], between(end, left=nSL$START[8], right=nSL$END[8])) |> mutate(nSL_start=nSL$START[8], nSL_end=nSL$END[8], nSL_pop=nSL$POP[8]),
    filter(gene.gff3, seqid==nSL$CHROM[9], between(end, left=nSL$START[9], right=nSL$END[9])) |> mutate(nSL_start=nSL$START[9], nSL_end=nSL$END[9], nSL_pop=nSL$POP[9]),
    filter(gene.gff3, seqid==nSL$CHROM[10], between(end, left=nSL$START[10], right=nSL$END[10])) |> mutate(nSL_start=nSL$START[10], nSL_end=nSL$END[10], nSL_pop=nSL$POP[10]),
    filter(gene.gff3, seqid==nSL$CHROM[11], between(end, left=nSL$START[11], right=nSL$END[11])) |> mutate(nSL_start=nSL$START[11], nSL_end=nSL$END[11], nSL_pop=nSL$POP[11]),
    filter(gene.gff3, seqid==nSL$CHROM[12], between(end, left=nSL$START[12], right=nSL$END[12])) |> mutate(nSL_start=nSL$START[12], nSL_end=nSL$END[12], nSL_pop=nSL$POP[12]),
    filter(gene.gff3, seqid==nSL$CHROM[13], between(end, left=nSL$START[13], right=nSL$END[13])) |> mutate(nSL_start=nSL$START[13], nSL_end=nSL$END[13], nSL_pop=nSL$POP[13]),
    filter(gene.gff3, seqid==nSL$CHROM[14], between(end, left=nSL$START[14], right=nSL$END[14])) |> mutate(nSL_start=nSL$START[14], nSL_end=nSL$END[14], nSL_pop=nSL$POP[14]),
    filter(gene.gff3, seqid==nSL$CHROM[15], between(end, left=nSL$START[15], right=nSL$END[15])) |> mutate(nSL_start=nSL$START[15], nSL_end=nSL$END[15], nSL_pop=nSL$POP[15]),
    filter(gene.gff3, seqid==nSL$CHROM[16], between(end, left=nSL$START[16], right=nSL$END[16])) |> mutate(nSL_start=nSL$START[16], nSL_end=nSL$END[16], nSL_pop=nSL$POP[16]),
    filter(gene.gff3, seqid==nSL$CHROM[17], between(end, left=nSL$START[17], right=nSL$END[17])) |> mutate(nSL_start=nSL$START[17], nSL_end=nSL$END[17], nSL_pop=nSL$POP[17]),
    filter(gene.gff3, seqid==nSL$CHROM[18], between(end, left=nSL$START[18], right=nSL$END[18])) |> mutate(nSL_start=nSL$START[18], nSL_end=nSL$END[18], nSL_pop=nSL$POP[18]),
    filter(gene.gff3, seqid==nSL$CHROM[19], between(end, left=nSL$START[19], right=nSL$END[19])) |> mutate(nSL_start=nSL$START[19], nSL_end=nSL$END[19], nSL_pop=nSL$POP[19]),
    filter(gene.gff3, seqid==nSL$CHROM[20], between(end, left=nSL$START[20], right=nSL$END[20])) |> mutate(nSL_start=nSL$START[20], nSL_end=nSL$END[20], nSL_pop=nSL$POP[20]),
    filter(gene.gff3, seqid==nSL$CHROM[21], between(end, left=nSL$START[21], right=nSL$END[21])) |> mutate(nSL_start=nSL$START[21], nSL_end=nSL$END[21], nSL_pop=nSL$POP[21]),
    filter(gene.gff3, seqid==nSL$CHROM[22], between(end, left=nSL$START[22], right=nSL$END[22])) |> mutate(nSL_start=nSL$START[22], nSL_end=nSL$END[22], nSL_pop=nSL$POP[22]),
    filter(gene.gff3, seqid==nSL$CHROM[23], between(end, left=nSL$START[23], right=nSL$END[23])) |> mutate(nSL_start=nSL$START[23], nSL_end=nSL$END[23], nSL_pop=nSL$POP[23]),
    filter(gene.gff3, seqid==nSL$CHROM[24], between(end, left=nSL$START[24], right=nSL$END[24])) |> mutate(nSL_start=nSL$START[24], nSL_end=nSL$END[24], nSL_pop=nSL$POP[24]),
    filter(gene.gff3, seqid==nSL$CHROM[25], between(end, left=nSL$START[25], right=nSL$END[25])) |> mutate(nSL_start=nSL$START[25], nSL_end=nSL$END[25], nSL_pop=nSL$POP[25]),
    filter(gene.gff3, seqid==nSL$CHROM[26], between(end, left=nSL$START[26], right=nSL$END[26])) |> mutate(nSL_start=nSL$START[26], nSL_end=nSL$END[26], nSL_pop=nSL$POP[26]),
    filter(gene.gff3, seqid==nSL$CHROM[27], between(end, left=nSL$START[27], right=nSL$END[27])) |> mutate(nSL_start=nSL$START[27], nSL_end=nSL$END[27], nSL_pop=nSL$POP[27]),
    filter(gene.gff3, seqid==nSL$CHROM[28], between(end, left=nSL$START[28], right=nSL$END[28])) |> mutate(nSL_start=nSL$START[28], nSL_end=nSL$END[28], nSL_pop=nSL$POP[28]),
    filter(gene.gff3, seqid==nSL$CHROM[29], between(end, left=nSL$START[29], right=nSL$END[29])) |> mutate(nSL_start=nSL$START[29], nSL_end=nSL$END[29], nSL_pop=nSL$POP[29]),
    filter(gene.gff3, seqid==nSL$CHROM[30], between(end, left=nSL$START[30], right=nSL$END[30])) |> mutate(nSL_start=nSL$START[30], nSL_end=nSL$END[30], nSL_pop=nSL$POP[30]),
    filter(gene.gff3, seqid==nSL$CHROM[31], between(end, left=nSL$START[31], right=nSL$END[31])) |> mutate(nSL_start=nSL$START[31], nSL_end=nSL$END[31], nSL_pop=nSL$POP[31]),
    filter(gene.gff3, seqid==nSL$CHROM[32], between(end, left=nSL$START[32], right=nSL$END[32])) |> mutate(nSL_start=nSL$START[32], nSL_end=nSL$END[32], nSL_pop=nSL$POP[32]),
    filter(gene.gff3, seqid==nSL$CHROM[33], between(end, left=nSL$START[33], right=nSL$END[33])) |> mutate(nSL_start=nSL$START[33], nSL_end=nSL$END[33], nSL_pop=nSL$POP[33]),
    filter(gene.gff3, seqid==nSL$CHROM[34], between(end, left=nSL$START[34], right=nSL$END[34])) |> mutate(nSL_start=nSL$START[34], nSL_end=nSL$END[34], nSL_pop=nSL$POP[34]),
    filter(gene.gff3, seqid==nSL$CHROM[35], between(end, left=nSL$START[35], right=nSL$END[35])) |> mutate(nSL_start=nSL$START[35], nSL_end=nSL$END[35], nSL_pop=nSL$POP[35]),
    filter(gene.gff3, seqid==nSL$CHROM[36], between(end, left=nSL$START[36], right=nSL$END[36])) |> mutate(nSL_start=nSL$START[36], nSL_end=nSL$END[36], nSL_pop=nSL$POP[36]),
    filter(gene.gff3, seqid==nSL$CHROM[37], between(end, left=nSL$START[37], right=nSL$END[37])) |> mutate(nSL_start=nSL$START[37], nSL_end=nSL$END[37], nSL_pop=nSL$POP[37]),
    filter(gene.gff3, seqid==nSL$CHROM[38], between(end, left=nSL$START[38], right=nSL$END[38])) |> mutate(nSL_start=nSL$START[38], nSL_end=nSL$END[38], nSL_pop=nSL$POP[38]),
    filter(gene.gff3, seqid==nSL$CHROM[39], between(end, left=nSL$START[39], right=nSL$END[39])) |> mutate(nSL_start=nSL$START[39], nSL_end=nSL$END[39], nSL_pop=nSL$POP[39]),
    filter(gene.gff3, seqid==nSL$CHROM[40], between(end, left=nSL$START[40], right=nSL$END[40])) |> mutate(nSL_start=nSL$START[40], nSL_end=nSL$END[40], nSL_pop=nSL$POP[40]),
    filter(gene.gff3, seqid==nSL$CHROM[41], between(end, left=nSL$START[41], right=nSL$END[41])) |> mutate(nSL_start=nSL$START[41], nSL_end=nSL$END[41], nSL_pop=nSL$POP[41]),
    filter(gene.gff3, seqid==nSL$CHROM[42], between(end, left=nSL$START[42], right=nSL$END[42])) |> mutate(nSL_start=nSL$START[42], nSL_end=nSL$END[42], nSL_pop=nSL$POP[42]),
    filter(gene.gff3, seqid==nSL$CHROM[43], between(end, left=nSL$START[43], right=nSL$END[43])) |> mutate(nSL_start=nSL$START[43], nSL_end=nSL$END[43], nSL_pop=nSL$POP[43]),
    filter(gene.gff3, seqid==nSL$CHROM[44], between(end, left=nSL$START[44], right=nSL$END[44])) |> mutate(nSL_start=nSL$START[44], nSL_end=nSL$END[44], nSL_pop=nSL$POP[44]),
    filter(gene.gff3, seqid==nSL$CHROM[45], between(end, left=nSL$START[45], right=nSL$END[45])) |> mutate(nSL_start=nSL$START[45], nSL_end=nSL$END[45], nSL_pop=nSL$POP[45]),
    filter(gene.gff3, seqid==nSL$CHROM[46], between(end, left=nSL$START[46], right=nSL$END[46])) |> mutate(nSL_start=nSL$START[46], nSL_end=nSL$END[46], nSL_pop=nSL$POP[46]),
    filter(gene.gff3, seqid==nSL$CHROM[47], between(end, left=nSL$START[47], right=nSL$END[47])) |> mutate(nSL_start=nSL$START[47], nSL_end=nSL$END[47], nSL_pop=nSL$POP[47]),
    filter(gene.gff3, seqid==nSL$CHROM[48], between(end, left=nSL$START[48], right=nSL$END[48])) |> mutate(nSL_start=nSL$START[48], nSL_end=nSL$END[48], nSL_pop=nSL$POP[48]),
    filter(gene.gff3, seqid==nSL$CHROM[49], between(end, left=nSL$START[49], right=nSL$END[49])) |> mutate(nSL_start=nSL$START[49], nSL_end=nSL$END[49], nSL_pop=nSL$POP[49]),
    filter(gene.gff3, seqid==nSL$CHROM[50], between(end, left=nSL$START[50], right=nSL$END[50])) |> mutate(nSL_start=nSL$START[50], nSL_end=nSL$END[50], nSL_pop=nSL$POP[50]),
    filter(gene.gff3, seqid==nSL$CHROM[51], between(end, left=nSL$START[51], right=nSL$END[51])) |> mutate(nSL_start=nSL$START[51], nSL_end=nSL$END[51], nSL_pop=nSL$POP[51]),
    filter(gene.gff3, seqid==nSL$CHROM[52], between(end, left=nSL$START[52], right=nSL$END[52])) |> mutate(nSL_start=nSL$START[52], nSL_end=nSL$END[52], nSL_pop=nSL$POP[52]),
    filter(gene.gff3, seqid==nSL$CHROM[53], between(end, left=nSL$START[53], right=nSL$END[53])) |> mutate(nSL_start=nSL$START[53], nSL_end=nSL$END[53], nSL_pop=nSL$POP[53]),
    filter(gene.gff3, seqid==nSL$CHROM[54], between(end, left=nSL$START[54], right=nSL$END[54])) |> mutate(nSL_start=nSL$START[54], nSL_end=nSL$END[54], nSL_pop=nSL$POP[54]),
    filter(gene.gff3, seqid==nSL$CHROM[55], between(end, left=nSL$START[55], right=nSL$END[55])) |> mutate(nSL_start=nSL$START[55], nSL_end=nSL$END[55], nSL_pop=nSL$POP[55]),
    filter(gene.gff3, seqid==nSL$CHROM[56], between(end, left=nSL$START[56], right=nSL$END[56])) |> mutate(nSL_start=nSL$START[56], nSL_end=nSL$END[56], nSL_pop=nSL$POP[56]),
    filter(gene.gff3, seqid==nSL$CHROM[57], between(end, left=nSL$START[57], right=nSL$END[57])) |> mutate(nSL_start=nSL$START[57], nSL_end=nSL$END[57], nSL_pop=nSL$POP[57]),
    filter(gene.gff3, seqid==nSL$CHROM[58], between(end, left=nSL$START[58], right=nSL$END[58])) |> mutate(nSL_start=nSL$START[58], nSL_end=nSL$END[58], nSL_pop=nSL$POP[58]),
    filter(gene.gff3, seqid==nSL$CHROM[59], between(end, left=nSL$START[59], right=nSL$END[59])) |> mutate(nSL_start=nSL$START[59], nSL_end=nSL$END[59], nSL_pop=nSL$POP[59]),
    filter(gene.gff3, seqid==nSL$CHROM[60], between(end, left=nSL$START[60], right=nSL$END[60])) |> mutate(nSL_start=nSL$START[60], nSL_end=nSL$END[60], nSL_pop=nSL$POP[60]),
    filter(gene.gff3, seqid==nSL$CHROM[61], between(end, left=nSL$START[61], right=nSL$END[61])) |> mutate(nSL_start=nSL$START[61], nSL_end=nSL$END[61], nSL_pop=nSL$POP[61]),
    filter(gene.gff3, seqid==nSL$CHROM[62], between(end, left=nSL$START[62], right=nSL$END[62])) |> mutate(nSL_start=nSL$START[62], nSL_end=nSL$END[62], nSL_pop=nSL$POP[62]),
    filter(gene.gff3, seqid==nSL$CHROM[63], between(end, left=nSL$START[63], right=nSL$END[63])) |> mutate(nSL_start=nSL$START[63], nSL_end=nSL$END[63], nSL_pop=nSL$POP[63]),
    filter(gene.gff3, seqid==nSL$CHROM[64], between(end, left=nSL$START[64], right=nSL$END[64])) |> mutate(nSL_start=nSL$START[64], nSL_end=nSL$END[64], nSL_pop=nSL$POP[64]),
    filter(gene.gff3, seqid==nSL$CHROM[65], between(end, left=nSL$START[65], right=nSL$END[65])) |> mutate(nSL_start=nSL$START[65], nSL_end=nSL$END[65], nSL_pop=nSL$POP[65]),
    filter(gene.gff3, seqid==nSL$CHROM[66], between(end, left=nSL$START[66], right=nSL$END[66])) |> mutate(nSL_start=nSL$START[66], nSL_end=nSL$END[66], nSL_pop=nSL$POP[66]),
    filter(gene.gff3, seqid==nSL$CHROM[67], between(end, left=nSL$START[67], right=nSL$END[67])) |> mutate(nSL_start=nSL$START[67], nSL_end=nSL$END[67], nSL_pop=nSL$POP[67]),
    filter(gene.gff3, seqid==nSL$CHROM[68], between(end, left=nSL$START[68], right=nSL$END[68])) |> mutate(nSL_start=nSL$START[68], nSL_end=nSL$END[68], nSL_pop=nSL$POP[68]),
    filter(gene.gff3, seqid==nSL$CHROM[69], between(end, left=nSL$START[69], right=nSL$END[69])) |> mutate(nSL_start=nSL$START[69], nSL_end=nSL$END[69], nSL_pop=nSL$POP[69]),
    filter(gene.gff3, seqid==nSL$CHROM[70], between(end, left=nSL$START[70], right=nSL$END[70])) |> mutate(nSL_start=nSL$START[70], nSL_end=nSL$END[70], nSL_pop=nSL$POP[70]),
    filter(gene.gff3, seqid==nSL$CHROM[71], between(end, left=nSL$START[71], right=nSL$END[71])) |> mutate(nSL_start=nSL$START[71], nSL_end=nSL$END[71], nSL_pop=nSL$POP[71]),
    filter(gene.gff3, seqid==nSL$CHROM[72], between(end, left=nSL$START[72], right=nSL$END[72])) |> mutate(nSL_start=nSL$START[72], nSL_end=nSL$END[72], nSL_pop=nSL$POP[72]),
    filter(gene.gff3, seqid==nSL$CHROM[73], between(end, left=nSL$START[73], right=nSL$END[73])) |> mutate(nSL_start=nSL$START[73], nSL_end=nSL$END[73], nSL_pop=nSL$POP[73]),
    filter(gene.gff3, seqid==nSL$CHROM[74], between(end, left=nSL$START[74], right=nSL$END[74])) |> mutate(nSL_start=nSL$START[74], nSL_end=nSL$END[74], nSL_pop=nSL$POP[74]),
    filter(gene.gff3, seqid==nSL$CHROM[75], between(end, left=nSL$START[75], right=nSL$END[75])) |> mutate(nSL_start=nSL$START[75], nSL_end=nSL$END[75], nSL_pop=nSL$POP[75]),
    filter(gene.gff3, seqid==nSL$CHROM[76], between(end, left=nSL$START[76], right=nSL$END[76])) |> mutate(nSL_start=nSL$START[76], nSL_end=nSL$END[76], nSL_pop=nSL$POP[76]),
    filter(gene.gff3, seqid==nSL$CHROM[77], between(end, left=nSL$START[77], right=nSL$END[77])) |> mutate(nSL_start=nSL$START[77], nSL_end=nSL$END[77], nSL_pop=nSL$POP[77]),
    filter(gene.gff3, seqid==nSL$CHROM[78], between(end, left=nSL$START[78], right=nSL$END[78])) |> mutate(nSL_start=nSL$START[78], nSL_end=nSL$END[78], nSL_pop=nSL$POP[78]),
    filter(gene.gff3, seqid==nSL$CHROM[79], between(end, left=nSL$START[79], right=nSL$END[79])) |> mutate(nSL_start=nSL$START[79], nSL_end=nSL$END[79], nSL_pop=nSL$POP[79]),
    filter(gene.gff3, seqid==nSL$CHROM[80], between(end, left=nSL$START[80], right=nSL$END[80])) |> mutate(nSL_start=nSL$START[80], nSL_end=nSL$END[80], nSL_pop=nSL$POP[80]),
    filter(gene.gff3, seqid==nSL$CHROM[81], between(end, left=nSL$START[81], right=nSL$END[81])) |> mutate(nSL_start=nSL$START[81], nSL_end=nSL$END[81], nSL_pop=nSL$POP[81]),
    filter(gene.gff3, seqid==nSL$CHROM[82], between(end, left=nSL$START[82], right=nSL$END[82])) |> mutate(nSL_start=nSL$START[82], nSL_end=nSL$END[82], nSL_pop=nSL$POP[82]),
    filter(gene.gff3, seqid==nSL$CHROM[83], between(end, left=nSL$START[83], right=nSL$END[83])) |> mutate(nSL_start=nSL$START[83], nSL_end=nSL$END[83], nSL_pop=nSL$POP[83]),
    filter(gene.gff3, seqid==nSL$CHROM[84], between(end, left=nSL$START[84], right=nSL$END[84])) |> mutate(nSL_start=nSL$START[84], nSL_end=nSL$END[84], nSL_pop=nSL$POP[84]),
    filter(gene.gff3, seqid==nSL$CHROM[85], between(end, left=nSL$START[85], right=nSL$END[85])) |> mutate(nSL_start=nSL$START[85], nSL_end=nSL$END[85], nSL_pop=nSL$POP[85]),
    filter(gene.gff3, seqid==nSL$CHROM[86], between(end, left=nSL$START[86], right=nSL$END[86])) |> mutate(nSL_start=nSL$START[86], nSL_end=nSL$END[86], nSL_pop=nSL$POP[86]),
    filter(gene.gff3, seqid==nSL$CHROM[87], between(end, left=nSL$START[87], right=nSL$END[87])) |> mutate(nSL_start=nSL$START[87], nSL_end=nSL$END[87], nSL_pop=nSL$POP[87]),
    filter(gene.gff3, seqid==nSL$CHROM[88], between(end, left=nSL$START[88], right=nSL$END[88])) |> mutate(nSL_start=nSL$START[88], nSL_end=nSL$END[88], nSL_pop=nSL$POP[88]),
    filter(gene.gff3, seqid==nSL$CHROM[89], between(end, left=nSL$START[89], right=nSL$END[89])) |> mutate(nSL_start=nSL$START[89], nSL_end=nSL$END[89], nSL_pop=nSL$POP[89]),
    filter(gene.gff3, seqid==nSL$CHROM[90], between(end, left=nSL$START[90], right=nSL$END[90])) |> mutate(nSL_start=nSL$START[90], nSL_end=nSL$END[90], nSL_pop=nSL$POP[90]),
    filter(gene.gff3, seqid==nSL$CHROM[91], between(end, left=nSL$START[91], right=nSL$END[91])) |> mutate(nSL_start=nSL$START[91], nSL_end=nSL$END[91], nSL_pop=nSL$POP[91]),
    filter(gene.gff3, seqid==nSL$CHROM[92], between(end, left=nSL$START[92], right=nSL$END[92])) |> mutate(nSL_start=nSL$START[92], nSL_end=nSL$END[92], nSL_pop=nSL$POP[92]),
    filter(gene.gff3, seqid==nSL$CHROM[93], between(end, left=nSL$START[93], right=nSL$END[93])) |> mutate(nSL_start=nSL$START[93], nSL_end=nSL$END[93], nSL_pop=nSL$POP[93]),
    filter(gene.gff3, seqid==nSL$CHROM[94], between(end, left=nSL$START[94], right=nSL$END[94])) |> mutate(nSL_start=nSL$START[94], nSL_end=nSL$END[94], nSL_pop=nSL$POP[94]),
    filter(gene.gff3, seqid==nSL$CHROM[95], between(end, left=nSL$START[95], right=nSL$END[95])) |> mutate(nSL_start=nSL$START[95], nSL_end=nSL$END[95], nSL_pop=nSL$POP[95]),
    filter(gene.gff3, seqid==nSL$CHROM[96], between(end, left=nSL$START[96], right=nSL$END[96])) |> mutate(nSL_start=nSL$START[96], nSL_end=nSL$END[96], nSL_pop=nSL$POP[96]),
    filter(gene.gff3, seqid==nSL$CHROM[97], between(end, left=nSL$START[97], right=nSL$END[97])) |> mutate(nSL_start=nSL$START[97], nSL_end=nSL$END[97], nSL_pop=nSL$POP[97]),
    filter(gene.gff3, seqid==nSL$CHROM[98], between(end, left=nSL$START[98], right=nSL$END[98])) |> mutate(nSL_start=nSL$START[98], nSL_end=nSL$END[98], nSL_pop=nSL$POP[98]),
    filter(gene.gff3, seqid==nSL$CHROM[99], between(end, left=nSL$START[99], right=nSL$END[99])) |> mutate(nSL_start=nSL$START[99], nSL_end=nSL$END[99], nSL_pop=nSL$POP[99]),
    filter(gene.gff3, seqid==nSL$CHROM[100], between(end, left=nSL$START[100], right=nSL$END[100])) |> mutate(nSL_start=nSL$START[100], nSL_end=nSL$END[100], nSL_pop=nSL$POP[100]),
    filter(gene.gff3, seqid==nSL$CHROM[101], between(end, left=nSL$START[101], right=nSL$END[101])) |> mutate(nSL_start=nSL$START[101], nSL_end=nSL$END[101], nSL_pop=nSL$POP[101]),
    filter(gene.gff3, seqid==nSL$CHROM[102], between(end, left=nSL$START[102], right=nSL$END[102])) |> mutate(nSL_start=nSL$START[102], nSL_end=nSL$END[102], nSL_pop=nSL$POP[102]),
    filter(gene.gff3, seqid==nSL$CHROM[103], between(end, left=nSL$START[103], right=nSL$END[103])) |> mutate(nSL_start=nSL$START[103], nSL_end=nSL$END[103], nSL_pop=nSL$POP[103]),
    filter(gene.gff3, seqid==nSL$CHROM[104], between(end, left=nSL$START[104], right=nSL$END[104])) |> mutate(nSL_start=nSL$START[104], nSL_end=nSL$END[104], nSL_pop=nSL$POP[104]),
    filter(gene.gff3, seqid==nSL$CHROM[105], between(end, left=nSL$START[105], right=nSL$END[105])) |> mutate(nSL_start=nSL$START[105], nSL_end=nSL$END[105], nSL_pop=nSL$POP[105]),
    filter(gene.gff3, seqid==nSL$CHROM[106], between(end, left=nSL$START[106], right=nSL$END[106])) |> mutate(nSL_start=nSL$START[106], nSL_end=nSL$END[106], nSL_pop=nSL$POP[106]),
    filter(gene.gff3, seqid==nSL$CHROM[107], between(end, left=nSL$START[107], right=nSL$END[107])) |> mutate(nSL_start=nSL$START[107], nSL_end=nSL$END[107], nSL_pop=nSL$POP[107]),
    filter(gene.gff3, seqid==nSL$CHROM[108], between(end, left=nSL$START[108], right=nSL$END[108])) |> mutate(nSL_start=nSL$START[108], nSL_end=nSL$END[108], nSL_pop=nSL$POP[108]),
    filter(gene.gff3, seqid==nSL$CHROM[109], between(end, left=nSL$START[109], right=nSL$END[109])) |> mutate(nSL_start=nSL$START[109], nSL_end=nSL$END[109], nSL_pop=nSL$POP[109]),
    filter(gene.gff3, seqid==nSL$CHROM[110], between(end, left=nSL$START[110], right=nSL$END[110])) |> mutate(nSL_start=nSL$START[110], nSL_end=nSL$END[110], nSL_pop=nSL$POP[110]),
    filter(gene.gff3, seqid==nSL$CHROM[111], between(end, left=nSL$START[111], right=nSL$END[111])) |> mutate(nSL_start=nSL$START[111], nSL_end=nSL$END[111], nSL_pop=nSL$POP[111]),
    filter(gene.gff3, seqid==nSL$CHROM[112], between(end, left=nSL$START[112], right=nSL$END[112])) |> mutate(nSL_start=nSL$START[112], nSL_end=nSL$END[112], nSL_pop=nSL$POP[112]),
    filter(gene.gff3, seqid==nSL$CHROM[113], between(end, left=nSL$START[113], right=nSL$END[113])) |> mutate(nSL_start=nSL$START[113], nSL_end=nSL$END[113], nSL_pop=nSL$POP[113]),
    filter(gene.gff3, seqid==nSL$CHROM[114], between(end, left=nSL$START[114], right=nSL$END[114])) |> mutate(nSL_start=nSL$START[114], nSL_end=nSL$END[114], nSL_pop=nSL$POP[114]),
    filter(gene.gff3, seqid==nSL$CHROM[115], between(end, left=nSL$START[115], right=nSL$END[115])) |> mutate(nSL_start=nSL$START[115], nSL_end=nSL$END[115], nSL_pop=nSL$POP[115]),
    filter(gene.gff3, seqid==nSL$CHROM[116], between(end, left=nSL$START[116], right=nSL$END[116])) |> mutate(nSL_start=nSL$START[116], nSL_end=nSL$END[116], nSL_pop=nSL$POP[116]),
    filter(gene.gff3, seqid==nSL$CHROM[117], between(end, left=nSL$START[117], right=nSL$END[117])) |> mutate(nSL_start=nSL$START[117], nSL_end=nSL$END[117], nSL_pop=nSL$POP[117]),
    filter(gene.gff3, seqid==nSL$CHROM[118], between(end, left=nSL$START[118], right=nSL$END[118])) |> mutate(nSL_start=nSL$START[118], nSL_end=nSL$END[118], nSL_pop=nSL$POP[118]),
    .id="outlier")
genes.ending.in.regions

genes.across.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==nSL$CHROM[1], start<=nSL$START[1] & end>=nSL$END[1]) |> mutate(nSL_start=nSL$START[1], nSL_end=nSL$END[1], nSL_pop=nSL$POP[1]),
    filter(gene.gff3, seqid==nSL$CHROM[2], start<=nSL$START[2] & end>=nSL$END[2]) |> mutate(nSL_start=nSL$START[2], nSL_end=nSL$END[2], nSL_pop=nSL$POP[2]),
    filter(gene.gff3, seqid==nSL$CHROM[3], start<=nSL$START[3] & end>=nSL$END[3]) |> mutate(nSL_start=nSL$START[3], nSL_end=nSL$END[3], nSL_pop=nSL$POP[3]),
    filter(gene.gff3, seqid==nSL$CHROM[4], start<=nSL$START[4] & end>=nSL$END[4]) |> mutate(nSL_start=nSL$START[4], nSL_end=nSL$END[4], nSL_pop=nSL$POP[4]),
    filter(gene.gff3, seqid==nSL$CHROM[5], start<=nSL$START[5] & end>=nSL$END[5]) |> mutate(nSL_start=nSL$START[5], nSL_end=nSL$END[5], nSL_pop=nSL$POP[5]),
    filter(gene.gff3, seqid==nSL$CHROM[6], start<=nSL$START[6] & end>=nSL$END[6]) |> mutate(nSL_start=nSL$START[6], nSL_end=nSL$END[6], nSL_pop=nSL$POP[6]),
    filter(gene.gff3, seqid==nSL$CHROM[7], start<=nSL$START[7] & end>=nSL$END[7]) |> mutate(nSL_start=nSL$START[7], nSL_end=nSL$END[7], nSL_pop=nSL$POP[7]),
    filter(gene.gff3, seqid==nSL$CHROM[8], start<=nSL$START[8] & end>=nSL$END[8]) |> mutate(nSL_start=nSL$START[8], nSL_end=nSL$END[8], nSL_pop=nSL$POP[8]),
    filter(gene.gff3, seqid==nSL$CHROM[9], start<=nSL$START[9] & end>=nSL$END[9]) |> mutate(nSL_start=nSL$START[9], nSL_end=nSL$END[9], nSL_pop=nSL$POP[9]),
    filter(gene.gff3, seqid==nSL$CHROM[10], start<=nSL$START[10] & end>=nSL$END[10]) |> mutate(nSL_start=nSL$START[10], nSL_end=nSL$END[10], nSL_pop=nSL$POP[10]),
    filter(gene.gff3, seqid==nSL$CHROM[11], start<=nSL$START[11] & end>=nSL$END[11]) |> mutate(nSL_start=nSL$START[11], nSL_end=nSL$END[11], nSL_pop=nSL$POP[11]),
    filter(gene.gff3, seqid==nSL$CHROM[12], start<=nSL$START[12] & end>=nSL$END[12]) |> mutate(nSL_start=nSL$START[12], nSL_end=nSL$END[12], nSL_pop=nSL$POP[12]),
    filter(gene.gff3, seqid==nSL$CHROM[13], start<=nSL$START[13] & end>=nSL$END[13]) |> mutate(nSL_start=nSL$START[13], nSL_end=nSL$END[13], nSL_pop=nSL$POP[13]),
    filter(gene.gff3, seqid==nSL$CHROM[14], start<=nSL$START[14] & end>=nSL$END[14]) |> mutate(nSL_start=nSL$START[14], nSL_end=nSL$END[14], nSL_pop=nSL$POP[14]),
    filter(gene.gff3, seqid==nSL$CHROM[15], start<=nSL$START[15] & end>=nSL$END[15]) |> mutate(nSL_start=nSL$START[15], nSL_end=nSL$END[15], nSL_pop=nSL$POP[15]),
    filter(gene.gff3, seqid==nSL$CHROM[16], start<=nSL$START[16] & end>=nSL$END[16]) |> mutate(nSL_start=nSL$START[16], nSL_end=nSL$END[16], nSL_pop=nSL$POP[16]),
    filter(gene.gff3, seqid==nSL$CHROM[17], start<=nSL$START[17] & end>=nSL$END[17]) |> mutate(nSL_start=nSL$START[17], nSL_end=nSL$END[17], nSL_pop=nSL$POP[17]),
    filter(gene.gff3, seqid==nSL$CHROM[18], start<=nSL$START[18] & end>=nSL$END[18]) |> mutate(nSL_start=nSL$START[18], nSL_end=nSL$END[18], nSL_pop=nSL$POP[18]),
    filter(gene.gff3, seqid==nSL$CHROM[19], start<=nSL$START[19] & end>=nSL$END[19]) |> mutate(nSL_start=nSL$START[19], nSL_end=nSL$END[19], nSL_pop=nSL$POP[19]),
    filter(gene.gff3, seqid==nSL$CHROM[20], start<=nSL$START[20] & end>=nSL$END[20]) |> mutate(nSL_start=nSL$START[20], nSL_end=nSL$END[20], nSL_pop=nSL$POP[20]),
    filter(gene.gff3, seqid==nSL$CHROM[21], start<=nSL$START[21] & end>=nSL$END[21]) |> mutate(nSL_start=nSL$START[21], nSL_end=nSL$END[21], nSL_pop=nSL$POP[21]),
    filter(gene.gff3, seqid==nSL$CHROM[22], start<=nSL$START[22] & end>=nSL$END[22]) |> mutate(nSL_start=nSL$START[22], nSL_end=nSL$END[22], nSL_pop=nSL$POP[22]),
    filter(gene.gff3, seqid==nSL$CHROM[23], start<=nSL$START[23] & end>=nSL$END[23]) |> mutate(nSL_start=nSL$START[23], nSL_end=nSL$END[23], nSL_pop=nSL$POP[23]),
    filter(gene.gff3, seqid==nSL$CHROM[24], start<=nSL$START[24] & end>=nSL$END[24]) |> mutate(nSL_start=nSL$START[24], nSL_end=nSL$END[24], nSL_pop=nSL$POP[24]),
    filter(gene.gff3, seqid==nSL$CHROM[25], start<=nSL$START[25] & end>=nSL$END[25]) |> mutate(nSL_start=nSL$START[25], nSL_end=nSL$END[25], nSL_pop=nSL$POP[25]),
    filter(gene.gff3, seqid==nSL$CHROM[26], start<=nSL$START[26] & end>=nSL$END[26]) |> mutate(nSL_start=nSL$START[26], nSL_end=nSL$END[26], nSL_pop=nSL$POP[26]),
    filter(gene.gff3, seqid==nSL$CHROM[27], start<=nSL$START[27] & end>=nSL$END[27]) |> mutate(nSL_start=nSL$START[27], nSL_end=nSL$END[27], nSL_pop=nSL$POP[27]),
    filter(gene.gff3, seqid==nSL$CHROM[28], start<=nSL$START[28] & end>=nSL$END[28]) |> mutate(nSL_start=nSL$START[28], nSL_end=nSL$END[28], nSL_pop=nSL$POP[28]),
    filter(gene.gff3, seqid==nSL$CHROM[29], start<=nSL$START[29] & end>=nSL$END[29]) |> mutate(nSL_start=nSL$START[29], nSL_end=nSL$END[29], nSL_pop=nSL$POP[29]),
    filter(gene.gff3, seqid==nSL$CHROM[30], start<=nSL$START[30] & end>=nSL$END[30]) |> mutate(nSL_start=nSL$START[30], nSL_end=nSL$END[30], nSL_pop=nSL$POP[30]),
    filter(gene.gff3, seqid==nSL$CHROM[31], start<=nSL$START[31] & end>=nSL$END[31]) |> mutate(nSL_start=nSL$START[31], nSL_end=nSL$END[31], nSL_pop=nSL$POP[31]),
    filter(gene.gff3, seqid==nSL$CHROM[32], start<=nSL$START[32] & end>=nSL$END[32]) |> mutate(nSL_start=nSL$START[32], nSL_end=nSL$END[32], nSL_pop=nSL$POP[32]),
    filter(gene.gff3, seqid==nSL$CHROM[33], start<=nSL$START[33] & end>=nSL$END[33]) |> mutate(nSL_start=nSL$START[33], nSL_end=nSL$END[33], nSL_pop=nSL$POP[33]),
    filter(gene.gff3, seqid==nSL$CHROM[34], start<=nSL$START[34] & end>=nSL$END[34]) |> mutate(nSL_start=nSL$START[34], nSL_end=nSL$END[34], nSL_pop=nSL$POP[34]),
    filter(gene.gff3, seqid==nSL$CHROM[35], start<=nSL$START[35] & end>=nSL$END[35]) |> mutate(nSL_start=nSL$START[35], nSL_end=nSL$END[35], nSL_pop=nSL$POP[35]),
    filter(gene.gff3, seqid==nSL$CHROM[36], start<=nSL$START[36] & end>=nSL$END[36]) |> mutate(nSL_start=nSL$START[36], nSL_end=nSL$END[36], nSL_pop=nSL$POP[36]),
    filter(gene.gff3, seqid==nSL$CHROM[37], start<=nSL$START[37] & end>=nSL$END[37]) |> mutate(nSL_start=nSL$START[37], nSL_end=nSL$END[37], nSL_pop=nSL$POP[37]),
    filter(gene.gff3, seqid==nSL$CHROM[38], start<=nSL$START[38] & end>=nSL$END[38]) |> mutate(nSL_start=nSL$START[38], nSL_end=nSL$END[38], nSL_pop=nSL$POP[38]),
    filter(gene.gff3, seqid==nSL$CHROM[39], start<=nSL$START[39] & end>=nSL$END[39]) |> mutate(nSL_start=nSL$START[39], nSL_end=nSL$END[39], nSL_pop=nSL$POP[39]),
    filter(gene.gff3, seqid==nSL$CHROM[40], start<=nSL$START[40] & end>=nSL$END[40]) |> mutate(nSL_start=nSL$START[40], nSL_end=nSL$END[40], nSL_pop=nSL$POP[40]),
    filter(gene.gff3, seqid==nSL$CHROM[41], start<=nSL$START[41] & end>=nSL$END[41]) |> mutate(nSL_start=nSL$START[41], nSL_end=nSL$END[41], nSL_pop=nSL$POP[41]),
    filter(gene.gff3, seqid==nSL$CHROM[42], start<=nSL$START[42] & end>=nSL$END[42]) |> mutate(nSL_start=nSL$START[42], nSL_end=nSL$END[42], nSL_pop=nSL$POP[42]),
    filter(gene.gff3, seqid==nSL$CHROM[43], start<=nSL$START[43] & end>=nSL$END[43]) |> mutate(nSL_start=nSL$START[43], nSL_end=nSL$END[43], nSL_pop=nSL$POP[43]),
    filter(gene.gff3, seqid==nSL$CHROM[44], start<=nSL$START[44] & end>=nSL$END[44]) |> mutate(nSL_start=nSL$START[44], nSL_end=nSL$END[44], nSL_pop=nSL$POP[44]),
    filter(gene.gff3, seqid==nSL$CHROM[45], start<=nSL$START[45] & end>=nSL$END[45]) |> mutate(nSL_start=nSL$START[45], nSL_end=nSL$END[45], nSL_pop=nSL$POP[45]),
    filter(gene.gff3, seqid==nSL$CHROM[46], start<=nSL$START[46] & end>=nSL$END[46]) |> mutate(nSL_start=nSL$START[46], nSL_end=nSL$END[46], nSL_pop=nSL$POP[46]),
    filter(gene.gff3, seqid==nSL$CHROM[47], start<=nSL$START[47] & end>=nSL$END[47]) |> mutate(nSL_start=nSL$START[47], nSL_end=nSL$END[47], nSL_pop=nSL$POP[47]),
    filter(gene.gff3, seqid==nSL$CHROM[48], start<=nSL$START[48] & end>=nSL$END[48]) |> mutate(nSL_start=nSL$START[48], nSL_end=nSL$END[48], nSL_pop=nSL$POP[48]),
    filter(gene.gff3, seqid==nSL$CHROM[49], start<=nSL$START[49] & end>=nSL$END[49]) |> mutate(nSL_start=nSL$START[49], nSL_end=nSL$END[49], nSL_pop=nSL$POP[49]),
    filter(gene.gff3, seqid==nSL$CHROM[50], start<=nSL$START[50] & end>=nSL$END[50]) |> mutate(nSL_start=nSL$START[50], nSL_end=nSL$END[50], nSL_pop=nSL$POP[50]),
    filter(gene.gff3, seqid==nSL$CHROM[51], start<=nSL$START[51] & end>=nSL$END[51]) |> mutate(nSL_start=nSL$START[51], nSL_end=nSL$END[51], nSL_pop=nSL$POP[51]),
    filter(gene.gff3, seqid==nSL$CHROM[52], start<=nSL$START[52] & end>=nSL$END[52]) |> mutate(nSL_start=nSL$START[52], nSL_end=nSL$END[52], nSL_pop=nSL$POP[52]),
    filter(gene.gff3, seqid==nSL$CHROM[53], start<=nSL$START[53] & end>=nSL$END[53]) |> mutate(nSL_start=nSL$START[53], nSL_end=nSL$END[53], nSL_pop=nSL$POP[53]),
    filter(gene.gff3, seqid==nSL$CHROM[54], start<=nSL$START[54] & end>=nSL$END[54]) |> mutate(nSL_start=nSL$START[54], nSL_end=nSL$END[54], nSL_pop=nSL$POP[54]),
    filter(gene.gff3, seqid==nSL$CHROM[55], start<=nSL$START[55] & end>=nSL$END[55]) |> mutate(nSL_start=nSL$START[55], nSL_end=nSL$END[55], nSL_pop=nSL$POP[55]),
    filter(gene.gff3, seqid==nSL$CHROM[56], start<=nSL$START[56] & end>=nSL$END[56]) |> mutate(nSL_start=nSL$START[56], nSL_end=nSL$END[56], nSL_pop=nSL$POP[56]),
    filter(gene.gff3, seqid==nSL$CHROM[57], start<=nSL$START[57] & end>=nSL$END[57]) |> mutate(nSL_start=nSL$START[57], nSL_end=nSL$END[57], nSL_pop=nSL$POP[57]),
    filter(gene.gff3, seqid==nSL$CHROM[58], start<=nSL$START[58] & end>=nSL$END[58]) |> mutate(nSL_start=nSL$START[58], nSL_end=nSL$END[58], nSL_pop=nSL$POP[58]),
    filter(gene.gff3, seqid==nSL$CHROM[59], start<=nSL$START[59] & end>=nSL$END[59]) |> mutate(nSL_start=nSL$START[59], nSL_end=nSL$END[59], nSL_pop=nSL$POP[59]),
    filter(gene.gff3, seqid==nSL$CHROM[60], start<=nSL$START[60] & end>=nSL$END[60]) |> mutate(nSL_start=nSL$START[60], nSL_end=nSL$END[60], nSL_pop=nSL$POP[60]),
    filter(gene.gff3, seqid==nSL$CHROM[61], start<=nSL$START[61] & end>=nSL$END[61]) |> mutate(nSL_start=nSL$START[61], nSL_end=nSL$END[61], nSL_pop=nSL$POP[61]),
    filter(gene.gff3, seqid==nSL$CHROM[62], start<=nSL$START[62] & end>=nSL$END[62]) |> mutate(nSL_start=nSL$START[62], nSL_end=nSL$END[62], nSL_pop=nSL$POP[62]),
    filter(gene.gff3, seqid==nSL$CHROM[63], start<=nSL$START[63] & end>=nSL$END[63]) |> mutate(nSL_start=nSL$START[63], nSL_end=nSL$END[63], nSL_pop=nSL$POP[63]),
    filter(gene.gff3, seqid==nSL$CHROM[64], start<=nSL$START[64] & end>=nSL$END[64]) |> mutate(nSL_start=nSL$START[64], nSL_end=nSL$END[64], nSL_pop=nSL$POP[64]),
    filter(gene.gff3, seqid==nSL$CHROM[65], start<=nSL$START[65] & end>=nSL$END[65]) |> mutate(nSL_start=nSL$START[65], nSL_end=nSL$END[65], nSL_pop=nSL$POP[65]),
    filter(gene.gff3, seqid==nSL$CHROM[66], start<=nSL$START[66] & end>=nSL$END[66]) |> mutate(nSL_start=nSL$START[66], nSL_end=nSL$END[66], nSL_pop=nSL$POP[66]),
    filter(gene.gff3, seqid==nSL$CHROM[67], start<=nSL$START[67] & end>=nSL$END[67]) |> mutate(nSL_start=nSL$START[67], nSL_end=nSL$END[67], nSL_pop=nSL$POP[67]),
    filter(gene.gff3, seqid==nSL$CHROM[68], start<=nSL$START[68] & end>=nSL$END[68]) |> mutate(nSL_start=nSL$START[68], nSL_end=nSL$END[68], nSL_pop=nSL$POP[68]),
    filter(gene.gff3, seqid==nSL$CHROM[69], start<=nSL$START[69] & end>=nSL$END[69]) |> mutate(nSL_start=nSL$START[69], nSL_end=nSL$END[69], nSL_pop=nSL$POP[69]),
    filter(gene.gff3, seqid==nSL$CHROM[70], start<=nSL$START[70] & end>=nSL$END[70]) |> mutate(nSL_start=nSL$START[70], nSL_end=nSL$END[70], nSL_pop=nSL$POP[70]),
    filter(gene.gff3, seqid==nSL$CHROM[71], start<=nSL$START[71] & end>=nSL$END[71]) |> mutate(nSL_start=nSL$START[71], nSL_end=nSL$END[71], nSL_pop=nSL$POP[71]),
    filter(gene.gff3, seqid==nSL$CHROM[72], start<=nSL$START[72] & end>=nSL$END[72]) |> mutate(nSL_start=nSL$START[72], nSL_end=nSL$END[72], nSL_pop=nSL$POP[72]),
    filter(gene.gff3, seqid==nSL$CHROM[73], start<=nSL$START[73] & end>=nSL$END[73]) |> mutate(nSL_start=nSL$START[73], nSL_end=nSL$END[73], nSL_pop=nSL$POP[73]),
    filter(gene.gff3, seqid==nSL$CHROM[74], start<=nSL$START[74] & end>=nSL$END[74]) |> mutate(nSL_start=nSL$START[74], nSL_end=nSL$END[74], nSL_pop=nSL$POP[74]),
    filter(gene.gff3, seqid==nSL$CHROM[75], start<=nSL$START[75] & end>=nSL$END[75]) |> mutate(nSL_start=nSL$START[75], nSL_end=nSL$END[75], nSL_pop=nSL$POP[75]),
    filter(gene.gff3, seqid==nSL$CHROM[76], start<=nSL$START[76] & end>=nSL$END[76]) |> mutate(nSL_start=nSL$START[76], nSL_end=nSL$END[76], nSL_pop=nSL$POP[76]),
    filter(gene.gff3, seqid==nSL$CHROM[77], start<=nSL$START[77] & end>=nSL$END[77]) |> mutate(nSL_start=nSL$START[77], nSL_end=nSL$END[77], nSL_pop=nSL$POP[77]),
    filter(gene.gff3, seqid==nSL$CHROM[78], start<=nSL$START[78] & end>=nSL$END[78]) |> mutate(nSL_start=nSL$START[78], nSL_end=nSL$END[78], nSL_pop=nSL$POP[78]),
    filter(gene.gff3, seqid==nSL$CHROM[79], start<=nSL$START[79] & end>=nSL$END[79]) |> mutate(nSL_start=nSL$START[79], nSL_end=nSL$END[79], nSL_pop=nSL$POP[79]),
    filter(gene.gff3, seqid==nSL$CHROM[80], start<=nSL$START[80] & end>=nSL$END[80]) |> mutate(nSL_start=nSL$START[80], nSL_end=nSL$END[80], nSL_pop=nSL$POP[80]),
    filter(gene.gff3, seqid==nSL$CHROM[81], start<=nSL$START[81] & end>=nSL$END[81]) |> mutate(nSL_start=nSL$START[81], nSL_end=nSL$END[81], nSL_pop=nSL$POP[81]),
    filter(gene.gff3, seqid==nSL$CHROM[82], start<=nSL$START[82] & end>=nSL$END[82]) |> mutate(nSL_start=nSL$START[82], nSL_end=nSL$END[82], nSL_pop=nSL$POP[82]),
    filter(gene.gff3, seqid==nSL$CHROM[83], start<=nSL$START[83] & end>=nSL$END[83]) |> mutate(nSL_start=nSL$START[83], nSL_end=nSL$END[83], nSL_pop=nSL$POP[83]),
    filter(gene.gff3, seqid==nSL$CHROM[84], start<=nSL$START[84] & end>=nSL$END[84]) |> mutate(nSL_start=nSL$START[84], nSL_end=nSL$END[84], nSL_pop=nSL$POP[84]),
    filter(gene.gff3, seqid==nSL$CHROM[85], start<=nSL$START[85] & end>=nSL$END[85]) |> mutate(nSL_start=nSL$START[85], nSL_end=nSL$END[85], nSL_pop=nSL$POP[85]),
    filter(gene.gff3, seqid==nSL$CHROM[86], start<=nSL$START[86] & end>=nSL$END[86]) |> mutate(nSL_start=nSL$START[86], nSL_end=nSL$END[86], nSL_pop=nSL$POP[86]),
    filter(gene.gff3, seqid==nSL$CHROM[87], start<=nSL$START[87] & end>=nSL$END[87]) |> mutate(nSL_start=nSL$START[87], nSL_end=nSL$END[87], nSL_pop=nSL$POP[87]),
    filter(gene.gff3, seqid==nSL$CHROM[88], start<=nSL$START[88] & end>=nSL$END[88]) |> mutate(nSL_start=nSL$START[88], nSL_end=nSL$END[88], nSL_pop=nSL$POP[88]),
    filter(gene.gff3, seqid==nSL$CHROM[89], start<=nSL$START[89] & end>=nSL$END[89]) |> mutate(nSL_start=nSL$START[89], nSL_end=nSL$END[89], nSL_pop=nSL$POP[89]),
    filter(gene.gff3, seqid==nSL$CHROM[90], start<=nSL$START[90] & end>=nSL$END[90]) |> mutate(nSL_start=nSL$START[90], nSL_end=nSL$END[90], nSL_pop=nSL$POP[90]),
    filter(gene.gff3, seqid==nSL$CHROM[91], start<=nSL$START[91] & end>=nSL$END[91]) |> mutate(nSL_start=nSL$START[91], nSL_end=nSL$END[91], nSL_pop=nSL$POP[91]),
    filter(gene.gff3, seqid==nSL$CHROM[92], start<=nSL$START[92] & end>=nSL$END[92]) |> mutate(nSL_start=nSL$START[92], nSL_end=nSL$END[92], nSL_pop=nSL$POP[92]),
    filter(gene.gff3, seqid==nSL$CHROM[93], start<=nSL$START[93] & end>=nSL$END[93]) |> mutate(nSL_start=nSL$START[93], nSL_end=nSL$END[93], nSL_pop=nSL$POP[93]),
    filter(gene.gff3, seqid==nSL$CHROM[94], start<=nSL$START[94] & end>=nSL$END[94]) |> mutate(nSL_start=nSL$START[94], nSL_end=nSL$END[94], nSL_pop=nSL$POP[94]),
    filter(gene.gff3, seqid==nSL$CHROM[95], start<=nSL$START[95] & end>=nSL$END[95]) |> mutate(nSL_start=nSL$START[95], nSL_end=nSL$END[95], nSL_pop=nSL$POP[95]),
    filter(gene.gff3, seqid==nSL$CHROM[96], start<=nSL$START[96] & end>=nSL$END[96]) |> mutate(nSL_start=nSL$START[96], nSL_end=nSL$END[96], nSL_pop=nSL$POP[96]),
    filter(gene.gff3, seqid==nSL$CHROM[97], start<=nSL$START[97] & end>=nSL$END[97]) |> mutate(nSL_start=nSL$START[97], nSL_end=nSL$END[97], nSL_pop=nSL$POP[97]),
    filter(gene.gff3, seqid==nSL$CHROM[98], start<=nSL$START[98] & end>=nSL$END[98]) |> mutate(nSL_start=nSL$START[98], nSL_end=nSL$END[98], nSL_pop=nSL$POP[98]),
    filter(gene.gff3, seqid==nSL$CHROM[99], start<=nSL$START[99] & end>=nSL$END[99]) |> mutate(nSL_start=nSL$START[99], nSL_end=nSL$END[99], nSL_pop=nSL$POP[99]),
    filter(gene.gff3, seqid==nSL$CHROM[100], start<=nSL$START[100] & end>=nSL$END[100]) |> mutate(nSL_start=nSL$START[100], nSL_end=nSL$END[100], nSL_pop=nSL$POP[100]),
    filter(gene.gff3, seqid==nSL$CHROM[101], start<=nSL$START[101] & end>=nSL$END[101]) |> mutate(nSL_start=nSL$START[101], nSL_end=nSL$END[101], nSL_pop=nSL$POP[101]),
    filter(gene.gff3, seqid==nSL$CHROM[102], start<=nSL$START[102] & end>=nSL$END[102]) |> mutate(nSL_start=nSL$START[102], nSL_end=nSL$END[102], nSL_pop=nSL$POP[102]),
    filter(gene.gff3, seqid==nSL$CHROM[103], start<=nSL$START[103] & end>=nSL$END[103]) |> mutate(nSL_start=nSL$START[103], nSL_end=nSL$END[103], nSL_pop=nSL$POP[103]),
    filter(gene.gff3, seqid==nSL$CHROM[104], start<=nSL$START[104] & end>=nSL$END[104]) |> mutate(nSL_start=nSL$START[104], nSL_end=nSL$END[104], nSL_pop=nSL$POP[104]),
    filter(gene.gff3, seqid==nSL$CHROM[105], start<=nSL$START[105] & end>=nSL$END[105]) |> mutate(nSL_start=nSL$START[105], nSL_end=nSL$END[105], nSL_pop=nSL$POP[105]),
    filter(gene.gff3, seqid==nSL$CHROM[106], start<=nSL$START[106] & end>=nSL$END[106]) |> mutate(nSL_start=nSL$START[106], nSL_end=nSL$END[106], nSL_pop=nSL$POP[106]),
    filter(gene.gff3, seqid==nSL$CHROM[107], start<=nSL$START[107] & end>=nSL$END[107]) |> mutate(nSL_start=nSL$START[107], nSL_end=nSL$END[107], nSL_pop=nSL$POP[107]),
    filter(gene.gff3, seqid==nSL$CHROM[108], start<=nSL$START[108] & end>=nSL$END[108]) |> mutate(nSL_start=nSL$START[108], nSL_end=nSL$END[108], nSL_pop=nSL$POP[108]),
    filter(gene.gff3, seqid==nSL$CHROM[109], start<=nSL$START[109] & end>=nSL$END[109]) |> mutate(nSL_start=nSL$START[109], nSL_end=nSL$END[109], nSL_pop=nSL$POP[109]),
    filter(gene.gff3, seqid==nSL$CHROM[110], start<=nSL$START[110] & end>=nSL$END[110]) |> mutate(nSL_start=nSL$START[110], nSL_end=nSL$END[110], nSL_pop=nSL$POP[110]),
    filter(gene.gff3, seqid==nSL$CHROM[111], start<=nSL$START[111] & end>=nSL$END[111]) |> mutate(nSL_start=nSL$START[111], nSL_end=nSL$END[111], nSL_pop=nSL$POP[111]),
    filter(gene.gff3, seqid==nSL$CHROM[112], start<=nSL$START[112] & end>=nSL$END[112]) |> mutate(nSL_start=nSL$START[112], nSL_end=nSL$END[112], nSL_pop=nSL$POP[112]),
    filter(gene.gff3, seqid==nSL$CHROM[113], start<=nSL$START[113] & end>=nSL$END[113]) |> mutate(nSL_start=nSL$START[113], nSL_end=nSL$END[113], nSL_pop=nSL$POP[113]),
    filter(gene.gff3, seqid==nSL$CHROM[114], start<=nSL$START[114] & end>=nSL$END[114]) |> mutate(nSL_start=nSL$START[114], nSL_end=nSL$END[114], nSL_pop=nSL$POP[114]),
    filter(gene.gff3, seqid==nSL$CHROM[115], start<=nSL$START[115] & end>=nSL$END[115]) |> mutate(nSL_start=nSL$START[115], nSL_end=nSL$END[115], nSL_pop=nSL$POP[115]),
    filter(gene.gff3, seqid==nSL$CHROM[116], start<=nSL$START[116] & end>=nSL$END[116]) |> mutate(nSL_start=nSL$START[116], nSL_end=nSL$END[116], nSL_pop=nSL$POP[116]),
    filter(gene.gff3, seqid==nSL$CHROM[117], start<=nSL$START[117] & end>=nSL$END[117]) |> mutate(nSL_start=nSL$START[117], nSL_end=nSL$END[117], nSL_pop=nSL$POP[117]),
    filter(gene.gff3, seqid==nSL$CHROM[118], start<=nSL$START[118] & end>=nSL$END[118]) |> mutate(nSL_start=nSL$START[118], nSL_end=nSL$END[118], nSL_pop=nSL$POP[118]),
    .id="outlier")
genes.across.regions

gene.hits.regions <- 
  bind_rows(genes.within.regions, genes.starting.in.regions, genes.ending.in.regions, genes.across.regions) |> 
  distinct(id, PANTHER_accession, nSL_pop, .keep_all=TRUE)

gene.hits.regions <- 
  rename(gene.hits.regions, region=outlier, chrom=seqid) |>
  arrange(chrom, start, nSL_pop)
  
gene.hits.regions <- mutate(gene.hits.regions, loc=paste0(chrom, ":", start, "–", end))
  
write_tsv(x=gene.hits.regions, file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.2/nSL_PROP_CRIT.gene.hits.regions.tab")

saveRDS(object=gene.hits.regions, file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.2/nSL_PROP_CRIT.gene.hits.regions.RDS")

#
## filter(gene.hits.regions, nSL_pop=="Del Norte-Humboldt") |> 
##   select(id, PANTHER_accession) |> 
##   distinct() |>
##   write_tsv(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.6/nSL2_NorteHumboldt", col_names=FALSE)

## filter(gene.hits.regions, nSL_pop=="Mendocino") |> 
##   select(id, PANTHER_accession) |> 
##   distinct() |>
##   write_tsv(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.6/nSL2_Mendocino", col_names=FALSE)

## filter(gene.hits.regions, nSL_pop=="Santa Barbara") |> 
##   select(id, PANTHER_accession) |> 
##   distinct() |>
##   write_tsv(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.6/nSL2_SantaBarbara", col_names=FALSE)


