library(tidyverse)
library(ggvenn)
library(gridExtra)

gene.gff3 <- readRDS(file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.0/gene.gff3.RDS")
#gene.gff3 <- select(gene.gff3, -start, -end) |> rename(start=prostart, end=proend) |> arrange(seqid, start)

xpclr <- 
  read_tsv(file="/Volumes/Tigrigobius/tgoby/xpclr/redo2/outliers999.tsv") |> 
  rename(CHROM=chr, START=start, END=stop, POP=samplesA, OG=samplesB)

genes.within.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==xpclr$CHROM[1], start>=xpclr$START[1] & end<=xpclr$END[1]) |> mutate(xpclr_start=xpclr$START[1], xpclr_end=xpclr$END[1], xpclr_pop=xpclr$POP[1], xpclr_og=xpclr$OG[1]),
    filter(gene.gff3, seqid==xpclr$CHROM[2], start>=xpclr$START[2] & end<=xpclr$END[2]) |> mutate(xpclr_start=xpclr$START[2], xpclr_end=xpclr$END[2], xpclr_pop=xpclr$POP[2], xpclr_og=xpclr$OG[2]),
    filter(gene.gff3, seqid==xpclr$CHROM[3], start>=xpclr$START[3] & end<=xpclr$END[3]) |> mutate(xpclr_start=xpclr$START[3], xpclr_end=xpclr$END[3], xpclr_pop=xpclr$POP[3], xpclr_og=xpclr$OG[3]),
    filter(gene.gff3, seqid==xpclr$CHROM[4], start>=xpclr$START[4] & end<=xpclr$END[4]) |> mutate(xpclr_start=xpclr$START[4], xpclr_end=xpclr$END[4], xpclr_pop=xpclr$POP[4], xpclr_og=xpclr$OG[4]),
    filter(gene.gff3, seqid==xpclr$CHROM[5], start>=xpclr$START[5] & end<=xpclr$END[5]) |> mutate(xpclr_start=xpclr$START[5], xpclr_end=xpclr$END[5], xpclr_pop=xpclr$POP[5], xpclr_og=xpclr$OG[5]),
    filter(gene.gff3, seqid==xpclr$CHROM[6], start>=xpclr$START[6] & end<=xpclr$END[6]) |> mutate(xpclr_start=xpclr$START[6], xpclr_end=xpclr$END[6], xpclr_pop=xpclr$POP[6], xpclr_og=xpclr$OG[6]),
    filter(gene.gff3, seqid==xpclr$CHROM[7], start>=xpclr$START[7] & end<=xpclr$END[7]) |> mutate(xpclr_start=xpclr$START[7], xpclr_end=xpclr$END[7], xpclr_pop=xpclr$POP[7], xpclr_og=xpclr$OG[7]),
    filter(gene.gff3, seqid==xpclr$CHROM[8], start>=xpclr$START[8] & end<=xpclr$END[8]) |> mutate(xpclr_start=xpclr$START[8], xpclr_end=xpclr$END[8], xpclr_pop=xpclr$POP[8], xpclr_og=xpclr$OG[8]),
    filter(gene.gff3, seqid==xpclr$CHROM[9], start>=xpclr$START[9] & end<=xpclr$END[9]) |> mutate(xpclr_start=xpclr$START[9], xpclr_end=xpclr$END[9], xpclr_pop=xpclr$POP[9], xpclr_og=xpclr$OG[9]),
    filter(gene.gff3, seqid==xpclr$CHROM[10], start>=xpclr$START[10] & end<=xpclr$END[10]) |> mutate(xpclr_start=xpclr$START[10], xpclr_end=xpclr$END[10], xpclr_pop=xpclr$POP[10], xpclr_og=xpclr$OG[10]),
    filter(gene.gff3, seqid==xpclr$CHROM[11], start>=xpclr$START[11] & end<=xpclr$END[11]) |> mutate(xpclr_start=xpclr$START[11], xpclr_end=xpclr$END[11], xpclr_pop=xpclr$POP[11], xpclr_og=xpclr$OG[11]),
    filter(gene.gff3, seqid==xpclr$CHROM[12], start>=xpclr$START[12] & end<=xpclr$END[12]) |> mutate(xpclr_start=xpclr$START[12], xpclr_end=xpclr$END[12], xpclr_pop=xpclr$POP[12], xpclr_og=xpclr$OG[12]),
    filter(gene.gff3, seqid==xpclr$CHROM[13], start>=xpclr$START[13] & end<=xpclr$END[13]) |> mutate(xpclr_start=xpclr$START[13], xpclr_end=xpclr$END[13], xpclr_pop=xpclr$POP[13], xpclr_og=xpclr$OG[13]),
    filter(gene.gff3, seqid==xpclr$CHROM[14], start>=xpclr$START[14] & end<=xpclr$END[14]) |> mutate(xpclr_start=xpclr$START[14], xpclr_end=xpclr$END[14], xpclr_pop=xpclr$POP[14], xpclr_og=xpclr$OG[14]),
    filter(gene.gff3, seqid==xpclr$CHROM[15], start>=xpclr$START[15] & end<=xpclr$END[15]) |> mutate(xpclr_start=xpclr$START[15], xpclr_end=xpclr$END[15], xpclr_pop=xpclr$POP[15], xpclr_og=xpclr$OG[15]),
    filter(gene.gff3, seqid==xpclr$CHROM[16], start>=xpclr$START[16] & end<=xpclr$END[16]) |> mutate(xpclr_start=xpclr$START[16], xpclr_end=xpclr$END[16], xpclr_pop=xpclr$POP[16], xpclr_og=xpclr$OG[16]),
    filter(gene.gff3, seqid==xpclr$CHROM[17], start>=xpclr$START[17] & end<=xpclr$END[17]) |> mutate(xpclr_start=xpclr$START[17], xpclr_end=xpclr$END[17], xpclr_pop=xpclr$POP[17], xpclr_og=xpclr$OG[17]),
    filter(gene.gff3, seqid==xpclr$CHROM[18], start>=xpclr$START[18] & end<=xpclr$END[18]) |> mutate(xpclr_start=xpclr$START[18], xpclr_end=xpclr$END[18], xpclr_pop=xpclr$POP[18], xpclr_og=xpclr$OG[18]),
    filter(gene.gff3, seqid==xpclr$CHROM[19], start>=xpclr$START[19] & end<=xpclr$END[19]) |> mutate(xpclr_start=xpclr$START[19], xpclr_end=xpclr$END[19], xpclr_pop=xpclr$POP[19], xpclr_og=xpclr$OG[19]),
    filter(gene.gff3, seqid==xpclr$CHROM[20], start>=xpclr$START[20] & end<=xpclr$END[20]) |> mutate(xpclr_start=xpclr$START[20], xpclr_end=xpclr$END[20], xpclr_pop=xpclr$POP[20], xpclr_og=xpclr$OG[20]),
    filter(gene.gff3, seqid==xpclr$CHROM[21], start>=xpclr$START[21] & end<=xpclr$END[21]) |> mutate(xpclr_start=xpclr$START[21], xpclr_end=xpclr$END[21], xpclr_pop=xpclr$POP[21], xpclr_og=xpclr$OG[21]),
    filter(gene.gff3, seqid==xpclr$CHROM[22], start>=xpclr$START[22] & end<=xpclr$END[22]) |> mutate(xpclr_start=xpclr$START[22], xpclr_end=xpclr$END[22], xpclr_pop=xpclr$POP[22], xpclr_og=xpclr$OG[22]),
    filter(gene.gff3, seqid==xpclr$CHROM[23], start>=xpclr$START[23] & end<=xpclr$END[23]) |> mutate(xpclr_start=xpclr$START[23], xpclr_end=xpclr$END[23], xpclr_pop=xpclr$POP[23], xpclr_og=xpclr$OG[23]),
    filter(gene.gff3, seqid==xpclr$CHROM[24], start>=xpclr$START[24] & end<=xpclr$END[24]) |> mutate(xpclr_start=xpclr$START[24], xpclr_end=xpclr$END[24], xpclr_pop=xpclr$POP[24], xpclr_og=xpclr$OG[24]),
    filter(gene.gff3, seqid==xpclr$CHROM[25], start>=xpclr$START[25] & end<=xpclr$END[25]) |> mutate(xpclr_start=xpclr$START[25], xpclr_end=xpclr$END[25], xpclr_pop=xpclr$POP[25], xpclr_og=xpclr$OG[25]),
    filter(gene.gff3, seqid==xpclr$CHROM[26], start>=xpclr$START[26] & end<=xpclr$END[26]) |> mutate(xpclr_start=xpclr$START[26], xpclr_end=xpclr$END[26], xpclr_pop=xpclr$POP[26], xpclr_og=xpclr$OG[26]),
    filter(gene.gff3, seqid==xpclr$CHROM[27], start>=xpclr$START[27] & end<=xpclr$END[27]) |> mutate(xpclr_start=xpclr$START[27], xpclr_end=xpclr$END[27], xpclr_pop=xpclr$POP[27], xpclr_og=xpclr$OG[27]),
    filter(gene.gff3, seqid==xpclr$CHROM[28], start>=xpclr$START[28] & end<=xpclr$END[28]) |> mutate(xpclr_start=xpclr$START[28], xpclr_end=xpclr$END[28], xpclr_pop=xpclr$POP[28], xpclr_og=xpclr$OG[28]),
    filter(gene.gff3, seqid==xpclr$CHROM[29], start>=xpclr$START[29] & end<=xpclr$END[29]) |> mutate(xpclr_start=xpclr$START[29], xpclr_end=xpclr$END[29], xpclr_pop=xpclr$POP[29], xpclr_og=xpclr$OG[29]),
    filter(gene.gff3, seqid==xpclr$CHROM[30], start>=xpclr$START[30] & end<=xpclr$END[30]) |> mutate(xpclr_start=xpclr$START[30], xpclr_end=xpclr$END[30], xpclr_pop=xpclr$POP[30], xpclr_og=xpclr$OG[30]),
    filter(gene.gff3, seqid==xpclr$CHROM[31], start>=xpclr$START[31] & end<=xpclr$END[31]) |> mutate(xpclr_start=xpclr$START[31], xpclr_end=xpclr$END[31], xpclr_pop=xpclr$POP[31], xpclr_og=xpclr$OG[31]),
    filter(gene.gff3, seqid==xpclr$CHROM[32], start>=xpclr$START[32] & end<=xpclr$END[32]) |> mutate(xpclr_start=xpclr$START[32], xpclr_end=xpclr$END[32], xpclr_pop=xpclr$POP[32], xpclr_og=xpclr$OG[32]),
    filter(gene.gff3, seqid==xpclr$CHROM[33], start>=xpclr$START[33] & end<=xpclr$END[33]) |> mutate(xpclr_start=xpclr$START[33], xpclr_end=xpclr$END[33], xpclr_pop=xpclr$POP[33], xpclr_og=xpclr$OG[33]),
    filter(gene.gff3, seqid==xpclr$CHROM[34], start>=xpclr$START[34] & end<=xpclr$END[34]) |> mutate(xpclr_start=xpclr$START[34], xpclr_end=xpclr$END[34], xpclr_pop=xpclr$POP[34], xpclr_og=xpclr$OG[34]),
    filter(gene.gff3, seqid==xpclr$CHROM[35], start>=xpclr$START[35] & end<=xpclr$END[35]) |> mutate(xpclr_start=xpclr$START[35], xpclr_end=xpclr$END[35], xpclr_pop=xpclr$POP[35], xpclr_og=xpclr$OG[35]),
    filter(gene.gff3, seqid==xpclr$CHROM[36], start>=xpclr$START[36] & end<=xpclr$END[36]) |> mutate(xpclr_start=xpclr$START[36], xpclr_end=xpclr$END[36], xpclr_pop=xpclr$POP[36], xpclr_og=xpclr$OG[36]),
    filter(gene.gff3, seqid==xpclr$CHROM[37], start>=xpclr$START[37] & end<=xpclr$END[37]) |> mutate(xpclr_start=xpclr$START[37], xpclr_end=xpclr$END[37], xpclr_pop=xpclr$POP[37], xpclr_og=xpclr$OG[37]),
    filter(gene.gff3, seqid==xpclr$CHROM[38], start>=xpclr$START[38] & end<=xpclr$END[38]) |> mutate(xpclr_start=xpclr$START[38], xpclr_end=xpclr$END[38], xpclr_pop=xpclr$POP[38], xpclr_og=xpclr$OG[38]),
    filter(gene.gff3, seqid==xpclr$CHROM[39], start>=xpclr$START[39] & end<=xpclr$END[39]) |> mutate(xpclr_start=xpclr$START[39], xpclr_end=xpclr$END[39], xpclr_pop=xpclr$POP[39], xpclr_og=xpclr$OG[39]),
    filter(gene.gff3, seqid==xpclr$CHROM[40], start>=xpclr$START[40] & end<=xpclr$END[40]) |> mutate(xpclr_start=xpclr$START[40], xpclr_end=xpclr$END[40], xpclr_pop=xpclr$POP[40], xpclr_og=xpclr$OG[40]),
    filter(gene.gff3, seqid==xpclr$CHROM[41], start>=xpclr$START[41] & end<=xpclr$END[41]) |> mutate(xpclr_start=xpclr$START[41], xpclr_end=xpclr$END[41], xpclr_pop=xpclr$POP[41], xpclr_og=xpclr$OG[41]),
    filter(gene.gff3, seqid==xpclr$CHROM[42], start>=xpclr$START[42] & end<=xpclr$END[42]) |> mutate(xpclr_start=xpclr$START[42], xpclr_end=xpclr$END[42], xpclr_pop=xpclr$POP[42], xpclr_og=xpclr$OG[42]),
    filter(gene.gff3, seqid==xpclr$CHROM[43], start>=xpclr$START[43] & end<=xpclr$END[43]) |> mutate(xpclr_start=xpclr$START[43], xpclr_end=xpclr$END[43], xpclr_pop=xpclr$POP[43], xpclr_og=xpclr$OG[43]),
    filter(gene.gff3, seqid==xpclr$CHROM[44], start>=xpclr$START[44] & end<=xpclr$END[44]) |> mutate(xpclr_start=xpclr$START[44], xpclr_end=xpclr$END[44], xpclr_pop=xpclr$POP[44], xpclr_og=xpclr$OG[44]),
    filter(gene.gff3, seqid==xpclr$CHROM[45], start>=xpclr$START[45] & end<=xpclr$END[45]) |> mutate(xpclr_start=xpclr$START[45], xpclr_end=xpclr$END[45], xpclr_pop=xpclr$POP[45], xpclr_og=xpclr$OG[45]),
    filter(gene.gff3, seqid==xpclr$CHROM[46], start>=xpclr$START[46] & end<=xpclr$END[46]) |> mutate(xpclr_start=xpclr$START[46], xpclr_end=xpclr$END[46], xpclr_pop=xpclr$POP[46], xpclr_og=xpclr$OG[46]),
    filter(gene.gff3, seqid==xpclr$CHROM[47], start>=xpclr$START[47] & end<=xpclr$END[47]) |> mutate(xpclr_start=xpclr$START[47], xpclr_end=xpclr$END[47], xpclr_pop=xpclr$POP[47], xpclr_og=xpclr$OG[47]),
    filter(gene.gff3, seqid==xpclr$CHROM[48], start>=xpclr$START[48] & end<=xpclr$END[48]) |> mutate(xpclr_start=xpclr$START[48], xpclr_end=xpclr$END[48], xpclr_pop=xpclr$POP[48], xpclr_og=xpclr$OG[48]),
    filter(gene.gff3, seqid==xpclr$CHROM[49], start>=xpclr$START[49] & end<=xpclr$END[49]) |> mutate(xpclr_start=xpclr$START[49], xpclr_end=xpclr$END[49], xpclr_pop=xpclr$POP[49], xpclr_og=xpclr$OG[49]),
    filter(gene.gff3, seqid==xpclr$CHROM[50], start>=xpclr$START[50] & end<=xpclr$END[50]) |> mutate(xpclr_start=xpclr$START[50], xpclr_end=xpclr$END[50], xpclr_pop=xpclr$POP[50], xpclr_og=xpclr$OG[50]),
    filter(gene.gff3, seqid==xpclr$CHROM[51], start>=xpclr$START[51] & end<=xpclr$END[51]) |> mutate(xpclr_start=xpclr$START[51], xpclr_end=xpclr$END[51], xpclr_pop=xpclr$POP[51], xpclr_og=xpclr$OG[51]),
    filter(gene.gff3, seqid==xpclr$CHROM[52], start>=xpclr$START[52] & end<=xpclr$END[52]) |> mutate(xpclr_start=xpclr$START[52], xpclr_end=xpclr$END[52], xpclr_pop=xpclr$POP[52], xpclr_og=xpclr$OG[52]),
    filter(gene.gff3, seqid==xpclr$CHROM[53], start>=xpclr$START[53] & end<=xpclr$END[53]) |> mutate(xpclr_start=xpclr$START[53], xpclr_end=xpclr$END[53], xpclr_pop=xpclr$POP[53], xpclr_og=xpclr$OG[53]),
    filter(gene.gff3, seqid==xpclr$CHROM[54], start>=xpclr$START[54] & end<=xpclr$END[54]) |> mutate(xpclr_start=xpclr$START[54], xpclr_end=xpclr$END[54], xpclr_pop=xpclr$POP[54], xpclr_og=xpclr$OG[54]),
    .id="outlier")
genes.within.regions


genes.starting.in.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==xpclr$CHROM[1], between(start, left=xpclr$START[1], right=xpclr$END[1])) |> mutate(xpclr_start=xpclr$START[1], xpclr_end=xpclr$END[1], xpclr_pop=xpclr$POP[1], xpclr_og=xpclr$OG[1]),
    filter(gene.gff3, seqid==xpclr$CHROM[2], between(start, left=xpclr$START[2], right=xpclr$END[2])) |> mutate(xpclr_start=xpclr$START[2], xpclr_end=xpclr$END[2], xpclr_pop=xpclr$POP[2], xpclr_og=xpclr$OG[2]),
    filter(gene.gff3, seqid==xpclr$CHROM[3], between(start, left=xpclr$START[3], right=xpclr$END[3])) |> mutate(xpclr_start=xpclr$START[3], xpclr_end=xpclr$END[3], xpclr_pop=xpclr$POP[3], xpclr_og=xpclr$OG[3]),
    filter(gene.gff3, seqid==xpclr$CHROM[4], between(start, left=xpclr$START[4], right=xpclr$END[4])) |> mutate(xpclr_start=xpclr$START[4], xpclr_end=xpclr$END[4], xpclr_pop=xpclr$POP[4], xpclr_og=xpclr$OG[4]),
    filter(gene.gff3, seqid==xpclr$CHROM[5], between(start, left=xpclr$START[5], right=xpclr$END[5])) |> mutate(xpclr_start=xpclr$START[5], xpclr_end=xpclr$END[5], xpclr_pop=xpclr$POP[5], xpclr_og=xpclr$OG[5]),
    filter(gene.gff3, seqid==xpclr$CHROM[6], between(start, left=xpclr$START[6], right=xpclr$END[6])) |> mutate(xpclr_start=xpclr$START[6], xpclr_end=xpclr$END[6], xpclr_pop=xpclr$POP[6], xpclr_og=xpclr$OG[6]),
    filter(gene.gff3, seqid==xpclr$CHROM[7], between(start, left=xpclr$START[7], right=xpclr$END[7])) |> mutate(xpclr_start=xpclr$START[7], xpclr_end=xpclr$END[7], xpclr_pop=xpclr$POP[7], xpclr_og=xpclr$OG[7]),
    filter(gene.gff3, seqid==xpclr$CHROM[8], between(start, left=xpclr$START[8], right=xpclr$END[8])) |> mutate(xpclr_start=xpclr$START[8], xpclr_end=xpclr$END[8], xpclr_pop=xpclr$POP[8], xpclr_og=xpclr$OG[8]),
    filter(gene.gff3, seqid==xpclr$CHROM[9], between(start, left=xpclr$START[9], right=xpclr$END[9])) |> mutate(xpclr_start=xpclr$START[9], xpclr_end=xpclr$END[9], xpclr_pop=xpclr$POP[9], xpclr_og=xpclr$OG[9]),
    filter(gene.gff3, seqid==xpclr$CHROM[10], between(start, left=xpclr$START[10], right=xpclr$END[10])) |> mutate(xpclr_start=xpclr$START[10], xpclr_end=xpclr$END[10], xpclr_pop=xpclr$POP[10], xpclr_og=xpclr$OG[10]),
    filter(gene.gff3, seqid==xpclr$CHROM[11], between(start, left=xpclr$START[11], right=xpclr$END[11])) |> mutate(xpclr_start=xpclr$START[11], xpclr_end=xpclr$END[11], xpclr_pop=xpclr$POP[11], xpclr_og=xpclr$OG[11]),
    filter(gene.gff3, seqid==xpclr$CHROM[12], between(start, left=xpclr$START[12], right=xpclr$END[12])) |> mutate(xpclr_start=xpclr$START[12], xpclr_end=xpclr$END[12], xpclr_pop=xpclr$POP[12], xpclr_og=xpclr$OG[12]),
    filter(gene.gff3, seqid==xpclr$CHROM[13], between(start, left=xpclr$START[13], right=xpclr$END[13])) |> mutate(xpclr_start=xpclr$START[13], xpclr_end=xpclr$END[13], xpclr_pop=xpclr$POP[13], xpclr_og=xpclr$OG[13]),
    filter(gene.gff3, seqid==xpclr$CHROM[14], between(start, left=xpclr$START[14], right=xpclr$END[14])) |> mutate(xpclr_start=xpclr$START[14], xpclr_end=xpclr$END[14], xpclr_pop=xpclr$POP[14], xpclr_og=xpclr$OG[14]),
    filter(gene.gff3, seqid==xpclr$CHROM[15], between(start, left=xpclr$START[15], right=xpclr$END[15])) |> mutate(xpclr_start=xpclr$START[15], xpclr_end=xpclr$END[15], xpclr_pop=xpclr$POP[15], xpclr_og=xpclr$OG[15]),
    filter(gene.gff3, seqid==xpclr$CHROM[16], between(start, left=xpclr$START[16], right=xpclr$END[16])) |> mutate(xpclr_start=xpclr$START[16], xpclr_end=xpclr$END[16], xpclr_pop=xpclr$POP[16], xpclr_og=xpclr$OG[16]),
    filter(gene.gff3, seqid==xpclr$CHROM[17], between(start, left=xpclr$START[17], right=xpclr$END[17])) |> mutate(xpclr_start=xpclr$START[17], xpclr_end=xpclr$END[17], xpclr_pop=xpclr$POP[17], xpclr_og=xpclr$OG[17]),
    filter(gene.gff3, seqid==xpclr$CHROM[18], between(start, left=xpclr$START[18], right=xpclr$END[18])) |> mutate(xpclr_start=xpclr$START[18], xpclr_end=xpclr$END[18], xpclr_pop=xpclr$POP[18], xpclr_og=xpclr$OG[18]),
    filter(gene.gff3, seqid==xpclr$CHROM[19], between(start, left=xpclr$START[19], right=xpclr$END[19])) |> mutate(xpclr_start=xpclr$START[19], xpclr_end=xpclr$END[19], xpclr_pop=xpclr$POP[19], xpclr_og=xpclr$OG[19]),
    filter(gene.gff3, seqid==xpclr$CHROM[20], between(start, left=xpclr$START[20], right=xpclr$END[20])) |> mutate(xpclr_start=xpclr$START[20], xpclr_end=xpclr$END[20], xpclr_pop=xpclr$POP[20], xpclr_og=xpclr$OG[20]),
    filter(gene.gff3, seqid==xpclr$CHROM[21], between(start, left=xpclr$START[21], right=xpclr$END[21])) |> mutate(xpclr_start=xpclr$START[21], xpclr_end=xpclr$END[21], xpclr_pop=xpclr$POP[21], xpclr_og=xpclr$OG[21]),
    filter(gene.gff3, seqid==xpclr$CHROM[22], between(start, left=xpclr$START[22], right=xpclr$END[22])) |> mutate(xpclr_start=xpclr$START[22], xpclr_end=xpclr$END[22], xpclr_pop=xpclr$POP[22], xpclr_og=xpclr$OG[22]),
    filter(gene.gff3, seqid==xpclr$CHROM[23], between(start, left=xpclr$START[23], right=xpclr$END[23])) |> mutate(xpclr_start=xpclr$START[23], xpclr_end=xpclr$END[23], xpclr_pop=xpclr$POP[23], xpclr_og=xpclr$OG[23]),
    filter(gene.gff3, seqid==xpclr$CHROM[24], between(start, left=xpclr$START[24], right=xpclr$END[24])) |> mutate(xpclr_start=xpclr$START[24], xpclr_end=xpclr$END[24], xpclr_pop=xpclr$POP[24], xpclr_og=xpclr$OG[24]),
    filter(gene.gff3, seqid==xpclr$CHROM[25], between(start, left=xpclr$START[25], right=xpclr$END[25])) |> mutate(xpclr_start=xpclr$START[25], xpclr_end=xpclr$END[25], xpclr_pop=xpclr$POP[25], xpclr_og=xpclr$OG[25]),
    filter(gene.gff3, seqid==xpclr$CHROM[26], between(start, left=xpclr$START[26], right=xpclr$END[26])) |> mutate(xpclr_start=xpclr$START[26], xpclr_end=xpclr$END[26], xpclr_pop=xpclr$POP[26], xpclr_og=xpclr$OG[26]),
    filter(gene.gff3, seqid==xpclr$CHROM[27], between(start, left=xpclr$START[27], right=xpclr$END[27])) |> mutate(xpclr_start=xpclr$START[27], xpclr_end=xpclr$END[27], xpclr_pop=xpclr$POP[27], xpclr_og=xpclr$OG[27]),
    filter(gene.gff3, seqid==xpclr$CHROM[28], between(start, left=xpclr$START[28], right=xpclr$END[28])) |> mutate(xpclr_start=xpclr$START[28], xpclr_end=xpclr$END[28], xpclr_pop=xpclr$POP[28], xpclr_og=xpclr$OG[28]),
    filter(gene.gff3, seqid==xpclr$CHROM[29], between(start, left=xpclr$START[29], right=xpclr$END[29])) |> mutate(xpclr_start=xpclr$START[29], xpclr_end=xpclr$END[29], xpclr_pop=xpclr$POP[29], xpclr_og=xpclr$OG[29]),
    filter(gene.gff3, seqid==xpclr$CHROM[30], between(start, left=xpclr$START[30], right=xpclr$END[30])) |> mutate(xpclr_start=xpclr$START[30], xpclr_end=xpclr$END[30], xpclr_pop=xpclr$POP[30], xpclr_og=xpclr$OG[30]),
    filter(gene.gff3, seqid==xpclr$CHROM[31], between(start, left=xpclr$START[31], right=xpclr$END[31])) |> mutate(xpclr_start=xpclr$START[31], xpclr_end=xpclr$END[31], xpclr_pop=xpclr$POP[31], xpclr_og=xpclr$OG[31]),
    filter(gene.gff3, seqid==xpclr$CHROM[32], between(start, left=xpclr$START[32], right=xpclr$END[32])) |> mutate(xpclr_start=xpclr$START[32], xpclr_end=xpclr$END[32], xpclr_pop=xpclr$POP[32], xpclr_og=xpclr$OG[32]),
    filter(gene.gff3, seqid==xpclr$CHROM[33], between(start, left=xpclr$START[33], right=xpclr$END[33])) |> mutate(xpclr_start=xpclr$START[33], xpclr_end=xpclr$END[33], xpclr_pop=xpclr$POP[33], xpclr_og=xpclr$OG[33]),
    filter(gene.gff3, seqid==xpclr$CHROM[34], between(start, left=xpclr$START[34], right=xpclr$END[34])) |> mutate(xpclr_start=xpclr$START[34], xpclr_end=xpclr$END[34], xpclr_pop=xpclr$POP[34], xpclr_og=xpclr$OG[34]),
    filter(gene.gff3, seqid==xpclr$CHROM[35], between(start, left=xpclr$START[35], right=xpclr$END[35])) |> mutate(xpclr_start=xpclr$START[35], xpclr_end=xpclr$END[35], xpclr_pop=xpclr$POP[35], xpclr_og=xpclr$OG[35]),
    filter(gene.gff3, seqid==xpclr$CHROM[36], between(start, left=xpclr$START[36], right=xpclr$END[36])) |> mutate(xpclr_start=xpclr$START[36], xpclr_end=xpclr$END[36], xpclr_pop=xpclr$POP[36], xpclr_og=xpclr$OG[36]),
    filter(gene.gff3, seqid==xpclr$CHROM[37], between(start, left=xpclr$START[37], right=xpclr$END[37])) |> mutate(xpclr_start=xpclr$START[37], xpclr_end=xpclr$END[37], xpclr_pop=xpclr$POP[37], xpclr_og=xpclr$OG[37]),
    filter(gene.gff3, seqid==xpclr$CHROM[38], between(start, left=xpclr$START[38], right=xpclr$END[38])) |> mutate(xpclr_start=xpclr$START[38], xpclr_end=xpclr$END[38], xpclr_pop=xpclr$POP[38], xpclr_og=xpclr$OG[38]),
    filter(gene.gff3, seqid==xpclr$CHROM[39], between(start, left=xpclr$START[39], right=xpclr$END[39])) |> mutate(xpclr_start=xpclr$START[39], xpclr_end=xpclr$END[39], xpclr_pop=xpclr$POP[39], xpclr_og=xpclr$OG[39]),
    filter(gene.gff3, seqid==xpclr$CHROM[40], between(start, left=xpclr$START[40], right=xpclr$END[40])) |> mutate(xpclr_start=xpclr$START[40], xpclr_end=xpclr$END[40], xpclr_pop=xpclr$POP[40], xpclr_og=xpclr$OG[40]),
    filter(gene.gff3, seqid==xpclr$CHROM[41], between(start, left=xpclr$START[41], right=xpclr$END[41])) |> mutate(xpclr_start=xpclr$START[41], xpclr_end=xpclr$END[41], xpclr_pop=xpclr$POP[41], xpclr_og=xpclr$OG[41]),
    filter(gene.gff3, seqid==xpclr$CHROM[42], between(start, left=xpclr$START[42], right=xpclr$END[42])) |> mutate(xpclr_start=xpclr$START[42], xpclr_end=xpclr$END[42], xpclr_pop=xpclr$POP[42], xpclr_og=xpclr$OG[42]),
    filter(gene.gff3, seqid==xpclr$CHROM[43], between(start, left=xpclr$START[43], right=xpclr$END[43])) |> mutate(xpclr_start=xpclr$START[43], xpclr_end=xpclr$END[43], xpclr_pop=xpclr$POP[43], xpclr_og=xpclr$OG[43]),
    filter(gene.gff3, seqid==xpclr$CHROM[44], between(start, left=xpclr$START[44], right=xpclr$END[44])) |> mutate(xpclr_start=xpclr$START[44], xpclr_end=xpclr$END[44], xpclr_pop=xpclr$POP[44], xpclr_og=xpclr$OG[44]),
    filter(gene.gff3, seqid==xpclr$CHROM[45], between(start, left=xpclr$START[45], right=xpclr$END[45])) |> mutate(xpclr_start=xpclr$START[45], xpclr_end=xpclr$END[45], xpclr_pop=xpclr$POP[45], xpclr_og=xpclr$OG[45]),
    filter(gene.gff3, seqid==xpclr$CHROM[46], between(start, left=xpclr$START[46], right=xpclr$END[46])) |> mutate(xpclr_start=xpclr$START[46], xpclr_end=xpclr$END[46], xpclr_pop=xpclr$POP[46], xpclr_og=xpclr$OG[46]),
    filter(gene.gff3, seqid==xpclr$CHROM[47], between(start, left=xpclr$START[47], right=xpclr$END[47])) |> mutate(xpclr_start=xpclr$START[47], xpclr_end=xpclr$END[47], xpclr_pop=xpclr$POP[47], xpclr_og=xpclr$OG[47]),
    filter(gene.gff3, seqid==xpclr$CHROM[48], between(start, left=xpclr$START[48], right=xpclr$END[48])) |> mutate(xpclr_start=xpclr$START[48], xpclr_end=xpclr$END[48], xpclr_pop=xpclr$POP[48], xpclr_og=xpclr$OG[48]),
    filter(gene.gff3, seqid==xpclr$CHROM[49], between(start, left=xpclr$START[49], right=xpclr$END[49])) |> mutate(xpclr_start=xpclr$START[49], xpclr_end=xpclr$END[49], xpclr_pop=xpclr$POP[49], xpclr_og=xpclr$OG[49]),
    filter(gene.gff3, seqid==xpclr$CHROM[50], between(start, left=xpclr$START[50], right=xpclr$END[50])) |> mutate(xpclr_start=xpclr$START[50], xpclr_end=xpclr$END[50], xpclr_pop=xpclr$POP[50], xpclr_og=xpclr$OG[50]),
    filter(gene.gff3, seqid==xpclr$CHROM[51], between(start, left=xpclr$START[51], right=xpclr$END[51])) |> mutate(xpclr_start=xpclr$START[51], xpclr_end=xpclr$END[51], xpclr_pop=xpclr$POP[51], xpclr_og=xpclr$OG[51]),
    filter(gene.gff3, seqid==xpclr$CHROM[52], between(start, left=xpclr$START[52], right=xpclr$END[52])) |> mutate(xpclr_start=xpclr$START[52], xpclr_end=xpclr$END[52], xpclr_pop=xpclr$POP[52], xpclr_og=xpclr$OG[52]),
    filter(gene.gff3, seqid==xpclr$CHROM[53], between(start, left=xpclr$START[53], right=xpclr$END[53])) |> mutate(xpclr_start=xpclr$START[53], xpclr_end=xpclr$END[53], xpclr_pop=xpclr$POP[53], xpclr_og=xpclr$OG[53]),
    filter(gene.gff3, seqid==xpclr$CHROM[54], between(start, left=xpclr$START[54], right=xpclr$END[54])) |> mutate(xpclr_start=xpclr$START[54], xpclr_end=xpclr$END[54], xpclr_pop=xpclr$POP[54], xpclr_og=xpclr$OG[54]),
    .id="outlier")
genes.starting.in.regions

genes.ending.in.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==xpclr$CHROM[1], between(end, left=xpclr$START[1], right=xpclr$END[1])) |> mutate(xpclr_start=xpclr$START[1], xpclr_end=xpclr$END[1], xpclr_pop=xpclr$POP[1], xpclr_og=xpclr$OG[1]),
    filter(gene.gff3, seqid==xpclr$CHROM[2], between(end, left=xpclr$START[2], right=xpclr$END[2])) |> mutate(xpclr_start=xpclr$START[2], xpclr_end=xpclr$END[2], xpclr_pop=xpclr$POP[2], xpclr_og=xpclr$OG[2]),
    filter(gene.gff3, seqid==xpclr$CHROM[3], between(end, left=xpclr$START[3], right=xpclr$END[3])) |> mutate(xpclr_start=xpclr$START[3], xpclr_end=xpclr$END[3], xpclr_pop=xpclr$POP[3], xpclr_og=xpclr$OG[3]),
    filter(gene.gff3, seqid==xpclr$CHROM[4], between(end, left=xpclr$START[4], right=xpclr$END[4])) |> mutate(xpclr_start=xpclr$START[4], xpclr_end=xpclr$END[4], xpclr_pop=xpclr$POP[4], xpclr_og=xpclr$OG[4]),
    filter(gene.gff3, seqid==xpclr$CHROM[5], between(end, left=xpclr$START[5], right=xpclr$END[5])) |> mutate(xpclr_start=xpclr$START[5], xpclr_end=xpclr$END[5], xpclr_pop=xpclr$POP[5], xpclr_og=xpclr$OG[5]),
    filter(gene.gff3, seqid==xpclr$CHROM[6], between(end, left=xpclr$START[6], right=xpclr$END[6])) |> mutate(xpclr_start=xpclr$START[6], xpclr_end=xpclr$END[6], xpclr_pop=xpclr$POP[6], xpclr_og=xpclr$OG[6]),
    filter(gene.gff3, seqid==xpclr$CHROM[7], between(end, left=xpclr$START[7], right=xpclr$END[7])) |> mutate(xpclr_start=xpclr$START[7], xpclr_end=xpclr$END[7], xpclr_pop=xpclr$POP[7], xpclr_og=xpclr$OG[7]),
    filter(gene.gff3, seqid==xpclr$CHROM[8], between(end, left=xpclr$START[8], right=xpclr$END[8])) |> mutate(xpclr_start=xpclr$START[8], xpclr_end=xpclr$END[8], xpclr_pop=xpclr$POP[8], xpclr_og=xpclr$OG[8]),
    filter(gene.gff3, seqid==xpclr$CHROM[9], between(end, left=xpclr$START[9], right=xpclr$END[9])) |> mutate(xpclr_start=xpclr$START[9], xpclr_end=xpclr$END[9], xpclr_pop=xpclr$POP[9], xpclr_og=xpclr$OG[9]),
    filter(gene.gff3, seqid==xpclr$CHROM[10], between(end, left=xpclr$START[10], right=xpclr$END[10])) |> mutate(xpclr_start=xpclr$START[10], xpclr_end=xpclr$END[10], xpclr_pop=xpclr$POP[10], xpclr_og=xpclr$OG[10]),
    filter(gene.gff3, seqid==xpclr$CHROM[11], between(end, left=xpclr$START[11], right=xpclr$END[11])) |> mutate(xpclr_start=xpclr$START[11], xpclr_end=xpclr$END[11], xpclr_pop=xpclr$POP[11], xpclr_og=xpclr$OG[11]),
    filter(gene.gff3, seqid==xpclr$CHROM[12], between(end, left=xpclr$START[12], right=xpclr$END[12])) |> mutate(xpclr_start=xpclr$START[12], xpclr_end=xpclr$END[12], xpclr_pop=xpclr$POP[12], xpclr_og=xpclr$OG[12]),
    filter(gene.gff3, seqid==xpclr$CHROM[13], between(end, left=xpclr$START[13], right=xpclr$END[13])) |> mutate(xpclr_start=xpclr$START[13], xpclr_end=xpclr$END[13], xpclr_pop=xpclr$POP[13], xpclr_og=xpclr$OG[13]),
    filter(gene.gff3, seqid==xpclr$CHROM[14], between(end, left=xpclr$START[14], right=xpclr$END[14])) |> mutate(xpclr_start=xpclr$START[14], xpclr_end=xpclr$END[14], xpclr_pop=xpclr$POP[14], xpclr_og=xpclr$OG[14]),
    filter(gene.gff3, seqid==xpclr$CHROM[15], between(end, left=xpclr$START[15], right=xpclr$END[15])) |> mutate(xpclr_start=xpclr$START[15], xpclr_end=xpclr$END[15], xpclr_pop=xpclr$POP[15], xpclr_og=xpclr$OG[15]),
    filter(gene.gff3, seqid==xpclr$CHROM[16], between(end, left=xpclr$START[16], right=xpclr$END[16])) |> mutate(xpclr_start=xpclr$START[16], xpclr_end=xpclr$END[16], xpclr_pop=xpclr$POP[16], xpclr_og=xpclr$OG[16]),
    filter(gene.gff3, seqid==xpclr$CHROM[17], between(end, left=xpclr$START[17], right=xpclr$END[17])) |> mutate(xpclr_start=xpclr$START[17], xpclr_end=xpclr$END[17], xpclr_pop=xpclr$POP[17], xpclr_og=xpclr$OG[17]),
    filter(gene.gff3, seqid==xpclr$CHROM[18], between(end, left=xpclr$START[18], right=xpclr$END[18])) |> mutate(xpclr_start=xpclr$START[18], xpclr_end=xpclr$END[18], xpclr_pop=xpclr$POP[18], xpclr_og=xpclr$OG[18]),
    filter(gene.gff3, seqid==xpclr$CHROM[19], between(end, left=xpclr$START[19], right=xpclr$END[19])) |> mutate(xpclr_start=xpclr$START[19], xpclr_end=xpclr$END[19], xpclr_pop=xpclr$POP[19], xpclr_og=xpclr$OG[19]),
    filter(gene.gff3, seqid==xpclr$CHROM[20], between(end, left=xpclr$START[20], right=xpclr$END[20])) |> mutate(xpclr_start=xpclr$START[20], xpclr_end=xpclr$END[20], xpclr_pop=xpclr$POP[20], xpclr_og=xpclr$OG[20]),
    filter(gene.gff3, seqid==xpclr$CHROM[21], between(end, left=xpclr$START[21], right=xpclr$END[21])) |> mutate(xpclr_start=xpclr$START[21], xpclr_end=xpclr$END[21], xpclr_pop=xpclr$POP[21], xpclr_og=xpclr$OG[21]),
    filter(gene.gff3, seqid==xpclr$CHROM[22], between(end, left=xpclr$START[22], right=xpclr$END[22])) |> mutate(xpclr_start=xpclr$START[22], xpclr_end=xpclr$END[22], xpclr_pop=xpclr$POP[22], xpclr_og=xpclr$OG[22]),
    filter(gene.gff3, seqid==xpclr$CHROM[23], between(end, left=xpclr$START[23], right=xpclr$END[23])) |> mutate(xpclr_start=xpclr$START[23], xpclr_end=xpclr$END[23], xpclr_pop=xpclr$POP[23], xpclr_og=xpclr$OG[23]),
    filter(gene.gff3, seqid==xpclr$CHROM[24], between(end, left=xpclr$START[24], right=xpclr$END[24])) |> mutate(xpclr_start=xpclr$START[24], xpclr_end=xpclr$END[24], xpclr_pop=xpclr$POP[24], xpclr_og=xpclr$OG[24]),
    filter(gene.gff3, seqid==xpclr$CHROM[25], between(end, left=xpclr$START[25], right=xpclr$END[25])) |> mutate(xpclr_start=xpclr$START[25], xpclr_end=xpclr$END[25], xpclr_pop=xpclr$POP[25], xpclr_og=xpclr$OG[25]),
    filter(gene.gff3, seqid==xpclr$CHROM[26], between(end, left=xpclr$START[26], right=xpclr$END[26])) |> mutate(xpclr_start=xpclr$START[26], xpclr_end=xpclr$END[26], xpclr_pop=xpclr$POP[26], xpclr_og=xpclr$OG[26]),
    filter(gene.gff3, seqid==xpclr$CHROM[27], between(end, left=xpclr$START[27], right=xpclr$END[27])) |> mutate(xpclr_start=xpclr$START[27], xpclr_end=xpclr$END[27], xpclr_pop=xpclr$POP[27], xpclr_og=xpclr$OG[27]),
    filter(gene.gff3, seqid==xpclr$CHROM[28], between(end, left=xpclr$START[28], right=xpclr$END[28])) |> mutate(xpclr_start=xpclr$START[28], xpclr_end=xpclr$END[28], xpclr_pop=xpclr$POP[28], xpclr_og=xpclr$OG[28]),
    filter(gene.gff3, seqid==xpclr$CHROM[29], between(end, left=xpclr$START[29], right=xpclr$END[29])) |> mutate(xpclr_start=xpclr$START[29], xpclr_end=xpclr$END[29], xpclr_pop=xpclr$POP[29], xpclr_og=xpclr$OG[29]),
    filter(gene.gff3, seqid==xpclr$CHROM[30], between(end, left=xpclr$START[30], right=xpclr$END[30])) |> mutate(xpclr_start=xpclr$START[30], xpclr_end=xpclr$END[30], xpclr_pop=xpclr$POP[30], xpclr_og=xpclr$OG[30]),
    filter(gene.gff3, seqid==xpclr$CHROM[31], between(end, left=xpclr$START[31], right=xpclr$END[31])) |> mutate(xpclr_start=xpclr$START[31], xpclr_end=xpclr$END[31], xpclr_pop=xpclr$POP[31], xpclr_og=xpclr$OG[31]),
    filter(gene.gff3, seqid==xpclr$CHROM[32], between(end, left=xpclr$START[32], right=xpclr$END[32])) |> mutate(xpclr_start=xpclr$START[32], xpclr_end=xpclr$END[32], xpclr_pop=xpclr$POP[32], xpclr_og=xpclr$OG[32]),
    filter(gene.gff3, seqid==xpclr$CHROM[33], between(end, left=xpclr$START[33], right=xpclr$END[33])) |> mutate(xpclr_start=xpclr$START[33], xpclr_end=xpclr$END[33], xpclr_pop=xpclr$POP[33], xpclr_og=xpclr$OG[33]),
    filter(gene.gff3, seqid==xpclr$CHROM[34], between(end, left=xpclr$START[34], right=xpclr$END[34])) |> mutate(xpclr_start=xpclr$START[34], xpclr_end=xpclr$END[34], xpclr_pop=xpclr$POP[34], xpclr_og=xpclr$OG[34]),
    filter(gene.gff3, seqid==xpclr$CHROM[35], between(end, left=xpclr$START[35], right=xpclr$END[35])) |> mutate(xpclr_start=xpclr$START[35], xpclr_end=xpclr$END[35], xpclr_pop=xpclr$POP[35], xpclr_og=xpclr$OG[35]),
    filter(gene.gff3, seqid==xpclr$CHROM[36], between(end, left=xpclr$START[36], right=xpclr$END[36])) |> mutate(xpclr_start=xpclr$START[36], xpclr_end=xpclr$END[36], xpclr_pop=xpclr$POP[36], xpclr_og=xpclr$OG[36]),
    filter(gene.gff3, seqid==xpclr$CHROM[37], between(end, left=xpclr$START[37], right=xpclr$END[37])) |> mutate(xpclr_start=xpclr$START[37], xpclr_end=xpclr$END[37], xpclr_pop=xpclr$POP[37], xpclr_og=xpclr$OG[37]),
    filter(gene.gff3, seqid==xpclr$CHROM[38], between(end, left=xpclr$START[38], right=xpclr$END[38])) |> mutate(xpclr_start=xpclr$START[38], xpclr_end=xpclr$END[38], xpclr_pop=xpclr$POP[38], xpclr_og=xpclr$OG[38]),
    filter(gene.gff3, seqid==xpclr$CHROM[39], between(end, left=xpclr$START[39], right=xpclr$END[39])) |> mutate(xpclr_start=xpclr$START[39], xpclr_end=xpclr$END[39], xpclr_pop=xpclr$POP[39], xpclr_og=xpclr$OG[39]),
    filter(gene.gff3, seqid==xpclr$CHROM[40], between(end, left=xpclr$START[40], right=xpclr$END[40])) |> mutate(xpclr_start=xpclr$START[40], xpclr_end=xpclr$END[40], xpclr_pop=xpclr$POP[40], xpclr_og=xpclr$OG[40]),
    filter(gene.gff3, seqid==xpclr$CHROM[41], between(end, left=xpclr$START[41], right=xpclr$END[41])) |> mutate(xpclr_start=xpclr$START[41], xpclr_end=xpclr$END[41], xpclr_pop=xpclr$POP[41], xpclr_og=xpclr$OG[41]),
    filter(gene.gff3, seqid==xpclr$CHROM[42], between(end, left=xpclr$START[42], right=xpclr$END[42])) |> mutate(xpclr_start=xpclr$START[42], xpclr_end=xpclr$END[42], xpclr_pop=xpclr$POP[42], xpclr_og=xpclr$OG[42]),
    filter(gene.gff3, seqid==xpclr$CHROM[43], between(end, left=xpclr$START[43], right=xpclr$END[43])) |> mutate(xpclr_start=xpclr$START[43], xpclr_end=xpclr$END[43], xpclr_pop=xpclr$POP[43], xpclr_og=xpclr$OG[43]),
    filter(gene.gff3, seqid==xpclr$CHROM[44], between(end, left=xpclr$START[44], right=xpclr$END[44])) |> mutate(xpclr_start=xpclr$START[44], xpclr_end=xpclr$END[44], xpclr_pop=xpclr$POP[44], xpclr_og=xpclr$OG[44]),
    filter(gene.gff3, seqid==xpclr$CHROM[45], between(end, left=xpclr$START[45], right=xpclr$END[45])) |> mutate(xpclr_start=xpclr$START[45], xpclr_end=xpclr$END[45], xpclr_pop=xpclr$POP[45], xpclr_og=xpclr$OG[45]),
    filter(gene.gff3, seqid==xpclr$CHROM[46], between(end, left=xpclr$START[46], right=xpclr$END[46])) |> mutate(xpclr_start=xpclr$START[46], xpclr_end=xpclr$END[46], xpclr_pop=xpclr$POP[46], xpclr_og=xpclr$OG[46]),
    filter(gene.gff3, seqid==xpclr$CHROM[47], between(end, left=xpclr$START[47], right=xpclr$END[47])) |> mutate(xpclr_start=xpclr$START[47], xpclr_end=xpclr$END[47], xpclr_pop=xpclr$POP[47], xpclr_og=xpclr$OG[47]),
    filter(gene.gff3, seqid==xpclr$CHROM[48], between(end, left=xpclr$START[48], right=xpclr$END[48])) |> mutate(xpclr_start=xpclr$START[48], xpclr_end=xpclr$END[48], xpclr_pop=xpclr$POP[48], xpclr_og=xpclr$OG[48]),
    filter(gene.gff3, seqid==xpclr$CHROM[49], between(end, left=xpclr$START[49], right=xpclr$END[49])) |> mutate(xpclr_start=xpclr$START[49], xpclr_end=xpclr$END[49], xpclr_pop=xpclr$POP[49], xpclr_og=xpclr$OG[49]),
    filter(gene.gff3, seqid==xpclr$CHROM[50], between(end, left=xpclr$START[50], right=xpclr$END[50])) |> mutate(xpclr_start=xpclr$START[50], xpclr_end=xpclr$END[50], xpclr_pop=xpclr$POP[50], xpclr_og=xpclr$OG[50]),
    filter(gene.gff3, seqid==xpclr$CHROM[51], between(end, left=xpclr$START[51], right=xpclr$END[51])) |> mutate(xpclr_start=xpclr$START[51], xpclr_end=xpclr$END[51], xpclr_pop=xpclr$POP[51], xpclr_og=xpclr$OG[51]),
    filter(gene.gff3, seqid==xpclr$CHROM[52], between(end, left=xpclr$START[52], right=xpclr$END[52])) |> mutate(xpclr_start=xpclr$START[52], xpclr_end=xpclr$END[52], xpclr_pop=xpclr$POP[52], xpclr_og=xpclr$OG[52]),
    filter(gene.gff3, seqid==xpclr$CHROM[53], between(end, left=xpclr$START[53], right=xpclr$END[53])) |> mutate(xpclr_start=xpclr$START[53], xpclr_end=xpclr$END[53], xpclr_pop=xpclr$POP[53], xpclr_og=xpclr$OG[53]),
    filter(gene.gff3, seqid==xpclr$CHROM[54], between(end, left=xpclr$START[54], right=xpclr$END[54])) |> mutate(xpclr_start=xpclr$START[54], xpclr_end=xpclr$END[54], xpclr_pop=xpclr$POP[54], xpclr_og=xpclr$OG[54]),
    .id="outlier")
genes.ending.in.regions

genes.across.regions <- 
  bind_rows(
    filter(gene.gff3, seqid==xpclr$CHROM[1], start<=xpclr$START[1] & end>=xpclr$END[1]) |> mutate(xpclr_start=xpclr$START[1], xpclr_end=xpclr$END[1], xpclr_pop=xpclr$POP[1], xpclr_og=xpclr$OG[1]),
    filter(gene.gff3, seqid==xpclr$CHROM[2], start<=xpclr$START[2] & end>=xpclr$END[2]) |> mutate(xpclr_start=xpclr$START[2], xpclr_end=xpclr$END[2], xpclr_pop=xpclr$POP[2], xpclr_og=xpclr$OG[2]),
    filter(gene.gff3, seqid==xpclr$CHROM[3], start<=xpclr$START[3] & end>=xpclr$END[3]) |> mutate(xpclr_start=xpclr$START[3], xpclr_end=xpclr$END[3], xpclr_pop=xpclr$POP[3], xpclr_og=xpclr$OG[3]),
    filter(gene.gff3, seqid==xpclr$CHROM[4], start<=xpclr$START[4] & end>=xpclr$END[4]) |> mutate(xpclr_start=xpclr$START[4], xpclr_end=xpclr$END[4], xpclr_pop=xpclr$POP[4], xpclr_og=xpclr$OG[4]),
    filter(gene.gff3, seqid==xpclr$CHROM[5], start<=xpclr$START[5] & end>=xpclr$END[5]) |> mutate(xpclr_start=xpclr$START[5], xpclr_end=xpclr$END[5], xpclr_pop=xpclr$POP[5], xpclr_og=xpclr$OG[5]),
    filter(gene.gff3, seqid==xpclr$CHROM[6], start<=xpclr$START[6] & end>=xpclr$END[6]) |> mutate(xpclr_start=xpclr$START[6], xpclr_end=xpclr$END[6], xpclr_pop=xpclr$POP[6], xpclr_og=xpclr$OG[6]),
    filter(gene.gff3, seqid==xpclr$CHROM[7], start<=xpclr$START[7] & end>=xpclr$END[7]) |> mutate(xpclr_start=xpclr$START[7], xpclr_end=xpclr$END[7], xpclr_pop=xpclr$POP[7], xpclr_og=xpclr$OG[7]),
    filter(gene.gff3, seqid==xpclr$CHROM[8], start<=xpclr$START[8] & end>=xpclr$END[8]) |> mutate(xpclr_start=xpclr$START[8], xpclr_end=xpclr$END[8], xpclr_pop=xpclr$POP[8], xpclr_og=xpclr$OG[8]),
    filter(gene.gff3, seqid==xpclr$CHROM[9], start<=xpclr$START[9] & end>=xpclr$END[9]) |> mutate(xpclr_start=xpclr$START[9], xpclr_end=xpclr$END[9], xpclr_pop=xpclr$POP[9], xpclr_og=xpclr$OG[9]),
    filter(gene.gff3, seqid==xpclr$CHROM[10], start<=xpclr$START[10] & end>=xpclr$END[10]) |> mutate(xpclr_start=xpclr$START[10], xpclr_end=xpclr$END[10], xpclr_pop=xpclr$POP[10], xpclr_og=xpclr$OG[10]),
    filter(gene.gff3, seqid==xpclr$CHROM[11], start<=xpclr$START[11] & end>=xpclr$END[11]) |> mutate(xpclr_start=xpclr$START[11], xpclr_end=xpclr$END[11], xpclr_pop=xpclr$POP[11], xpclr_og=xpclr$OG[11]),
    filter(gene.gff3, seqid==xpclr$CHROM[12], start<=xpclr$START[12] & end>=xpclr$END[12]) |> mutate(xpclr_start=xpclr$START[12], xpclr_end=xpclr$END[12], xpclr_pop=xpclr$POP[12], xpclr_og=xpclr$OG[12]),
    filter(gene.gff3, seqid==xpclr$CHROM[13], start<=xpclr$START[13] & end>=xpclr$END[13]) |> mutate(xpclr_start=xpclr$START[13], xpclr_end=xpclr$END[13], xpclr_pop=xpclr$POP[13], xpclr_og=xpclr$OG[13]),
    filter(gene.gff3, seqid==xpclr$CHROM[14], start<=xpclr$START[14] & end>=xpclr$END[14]) |> mutate(xpclr_start=xpclr$START[14], xpclr_end=xpclr$END[14], xpclr_pop=xpclr$POP[14], xpclr_og=xpclr$OG[14]),
    filter(gene.gff3, seqid==xpclr$CHROM[15], start<=xpclr$START[15] & end>=xpclr$END[15]) |> mutate(xpclr_start=xpclr$START[15], xpclr_end=xpclr$END[15], xpclr_pop=xpclr$POP[15], xpclr_og=xpclr$OG[15]),
    filter(gene.gff3, seqid==xpclr$CHROM[16], start<=xpclr$START[16] & end>=xpclr$END[16]) |> mutate(xpclr_start=xpclr$START[16], xpclr_end=xpclr$END[16], xpclr_pop=xpclr$POP[16], xpclr_og=xpclr$OG[16]),
    filter(gene.gff3, seqid==xpclr$CHROM[17], start<=xpclr$START[17] & end>=xpclr$END[17]) |> mutate(xpclr_start=xpclr$START[17], xpclr_end=xpclr$END[17], xpclr_pop=xpclr$POP[17], xpclr_og=xpclr$OG[17]),
    filter(gene.gff3, seqid==xpclr$CHROM[18], start<=xpclr$START[18] & end>=xpclr$END[18]) |> mutate(xpclr_start=xpclr$START[18], xpclr_end=xpclr$END[18], xpclr_pop=xpclr$POP[18], xpclr_og=xpclr$OG[18]),
    filter(gene.gff3, seqid==xpclr$CHROM[19], start<=xpclr$START[19] & end>=xpclr$END[19]) |> mutate(xpclr_start=xpclr$START[19], xpclr_end=xpclr$END[19], xpclr_pop=xpclr$POP[19], xpclr_og=xpclr$OG[19]),
    filter(gene.gff3, seqid==xpclr$CHROM[20], start<=xpclr$START[20] & end>=xpclr$END[20]) |> mutate(xpclr_start=xpclr$START[20], xpclr_end=xpclr$END[20], xpclr_pop=xpclr$POP[20], xpclr_og=xpclr$OG[20]),
    filter(gene.gff3, seqid==xpclr$CHROM[21], start<=xpclr$START[21] & end>=xpclr$END[21]) |> mutate(xpclr_start=xpclr$START[21], xpclr_end=xpclr$END[21], xpclr_pop=xpclr$POP[21], xpclr_og=xpclr$OG[21]),
    filter(gene.gff3, seqid==xpclr$CHROM[22], start<=xpclr$START[22] & end>=xpclr$END[22]) |> mutate(xpclr_start=xpclr$START[22], xpclr_end=xpclr$END[22], xpclr_pop=xpclr$POP[22], xpclr_og=xpclr$OG[22]),
    filter(gene.gff3, seqid==xpclr$CHROM[23], start<=xpclr$START[23] & end>=xpclr$END[23]) |> mutate(xpclr_start=xpclr$START[23], xpclr_end=xpclr$END[23], xpclr_pop=xpclr$POP[23], xpclr_og=xpclr$OG[23]),
    filter(gene.gff3, seqid==xpclr$CHROM[24], start<=xpclr$START[24] & end>=xpclr$END[24]) |> mutate(xpclr_start=xpclr$START[24], xpclr_end=xpclr$END[24], xpclr_pop=xpclr$POP[24], xpclr_og=xpclr$OG[24]),
    filter(gene.gff3, seqid==xpclr$CHROM[25], start<=xpclr$START[25] & end>=xpclr$END[25]) |> mutate(xpclr_start=xpclr$START[25], xpclr_end=xpclr$END[25], xpclr_pop=xpclr$POP[25], xpclr_og=xpclr$OG[25]),
    filter(gene.gff3, seqid==xpclr$CHROM[26], start<=xpclr$START[26] & end>=xpclr$END[26]) |> mutate(xpclr_start=xpclr$START[26], xpclr_end=xpclr$END[26], xpclr_pop=xpclr$POP[26], xpclr_og=xpclr$OG[26]),
    filter(gene.gff3, seqid==xpclr$CHROM[27], start<=xpclr$START[27] & end>=xpclr$END[27]) |> mutate(xpclr_start=xpclr$START[27], xpclr_end=xpclr$END[27], xpclr_pop=xpclr$POP[27], xpclr_og=xpclr$OG[27]),
    filter(gene.gff3, seqid==xpclr$CHROM[28], start<=xpclr$START[28] & end>=xpclr$END[28]) |> mutate(xpclr_start=xpclr$START[28], xpclr_end=xpclr$END[28], xpclr_pop=xpclr$POP[28], xpclr_og=xpclr$OG[28]),
    filter(gene.gff3, seqid==xpclr$CHROM[29], start<=xpclr$START[29] & end>=xpclr$END[29]) |> mutate(xpclr_start=xpclr$START[29], xpclr_end=xpclr$END[29], xpclr_pop=xpclr$POP[29], xpclr_og=xpclr$OG[29]),
    filter(gene.gff3, seqid==xpclr$CHROM[30], start<=xpclr$START[30] & end>=xpclr$END[30]) |> mutate(xpclr_start=xpclr$START[30], xpclr_end=xpclr$END[30], xpclr_pop=xpclr$POP[30], xpclr_og=xpclr$OG[30]),
    filter(gene.gff3, seqid==xpclr$CHROM[31], start<=xpclr$START[31] & end>=xpclr$END[31]) |> mutate(xpclr_start=xpclr$START[31], xpclr_end=xpclr$END[31], xpclr_pop=xpclr$POP[31], xpclr_og=xpclr$OG[31]),
    filter(gene.gff3, seqid==xpclr$CHROM[32], start<=xpclr$START[32] & end>=xpclr$END[32]) |> mutate(xpclr_start=xpclr$START[32], xpclr_end=xpclr$END[32], xpclr_pop=xpclr$POP[32], xpclr_og=xpclr$OG[32]),
    filter(gene.gff3, seqid==xpclr$CHROM[33], start<=xpclr$START[33] & end>=xpclr$END[33]) |> mutate(xpclr_start=xpclr$START[33], xpclr_end=xpclr$END[33], xpclr_pop=xpclr$POP[33], xpclr_og=xpclr$OG[33]),
    filter(gene.gff3, seqid==xpclr$CHROM[34], start<=xpclr$START[34] & end>=xpclr$END[34]) |> mutate(xpclr_start=xpclr$START[34], xpclr_end=xpclr$END[34], xpclr_pop=xpclr$POP[34], xpclr_og=xpclr$OG[34]),
    filter(gene.gff3, seqid==xpclr$CHROM[35], start<=xpclr$START[35] & end>=xpclr$END[35]) |> mutate(xpclr_start=xpclr$START[35], xpclr_end=xpclr$END[35], xpclr_pop=xpclr$POP[35], xpclr_og=xpclr$OG[35]),
    filter(gene.gff3, seqid==xpclr$CHROM[36], start<=xpclr$START[36] & end>=xpclr$END[36]) |> mutate(xpclr_start=xpclr$START[36], xpclr_end=xpclr$END[36], xpclr_pop=xpclr$POP[36], xpclr_og=xpclr$OG[36]),
    filter(gene.gff3, seqid==xpclr$CHROM[37], start<=xpclr$START[37] & end>=xpclr$END[37]) |> mutate(xpclr_start=xpclr$START[37], xpclr_end=xpclr$END[37], xpclr_pop=xpclr$POP[37], xpclr_og=xpclr$OG[37]),
    filter(gene.gff3, seqid==xpclr$CHROM[38], start<=xpclr$START[38] & end>=xpclr$END[38]) |> mutate(xpclr_start=xpclr$START[38], xpclr_end=xpclr$END[38], xpclr_pop=xpclr$POP[38], xpclr_og=xpclr$OG[38]),
    filter(gene.gff3, seqid==xpclr$CHROM[39], start<=xpclr$START[39] & end>=xpclr$END[39]) |> mutate(xpclr_start=xpclr$START[39], xpclr_end=xpclr$END[39], xpclr_pop=xpclr$POP[39], xpclr_og=xpclr$OG[39]),
    filter(gene.gff3, seqid==xpclr$CHROM[40], start<=xpclr$START[40] & end>=xpclr$END[40]) |> mutate(xpclr_start=xpclr$START[40], xpclr_end=xpclr$END[40], xpclr_pop=xpclr$POP[40], xpclr_og=xpclr$OG[40]),
    filter(gene.gff3, seqid==xpclr$CHROM[41], start<=xpclr$START[41] & end>=xpclr$END[41]) |> mutate(xpclr_start=xpclr$START[41], xpclr_end=xpclr$END[41], xpclr_pop=xpclr$POP[41], xpclr_og=xpclr$OG[41]),
    filter(gene.gff3, seqid==xpclr$CHROM[42], start<=xpclr$START[42] & end>=xpclr$END[42]) |> mutate(xpclr_start=xpclr$START[42], xpclr_end=xpclr$END[42], xpclr_pop=xpclr$POP[42], xpclr_og=xpclr$OG[42]),
    filter(gene.gff3, seqid==xpclr$CHROM[43], start<=xpclr$START[43] & end>=xpclr$END[43]) |> mutate(xpclr_start=xpclr$START[43], xpclr_end=xpclr$END[43], xpclr_pop=xpclr$POP[43], xpclr_og=xpclr$OG[43]),
    filter(gene.gff3, seqid==xpclr$CHROM[44], start<=xpclr$START[44] & end>=xpclr$END[44]) |> mutate(xpclr_start=xpclr$START[44], xpclr_end=xpclr$END[44], xpclr_pop=xpclr$POP[44], xpclr_og=xpclr$OG[44]),
    filter(gene.gff3, seqid==xpclr$CHROM[45], start<=xpclr$START[45] & end>=xpclr$END[45]) |> mutate(xpclr_start=xpclr$START[45], xpclr_end=xpclr$END[45], xpclr_pop=xpclr$POP[45], xpclr_og=xpclr$OG[45]),
    filter(gene.gff3, seqid==xpclr$CHROM[46], start<=xpclr$START[46] & end>=xpclr$END[46]) |> mutate(xpclr_start=xpclr$START[46], xpclr_end=xpclr$END[46], xpclr_pop=xpclr$POP[46], xpclr_og=xpclr$OG[46]),
    filter(gene.gff3, seqid==xpclr$CHROM[47], start<=xpclr$START[47] & end>=xpclr$END[47]) |> mutate(xpclr_start=xpclr$START[47], xpclr_end=xpclr$END[47], xpclr_pop=xpclr$POP[47], xpclr_og=xpclr$OG[47]),
    filter(gene.gff3, seqid==xpclr$CHROM[48], start<=xpclr$START[48] & end>=xpclr$END[48]) |> mutate(xpclr_start=xpclr$START[48], xpclr_end=xpclr$END[48], xpclr_pop=xpclr$POP[48], xpclr_og=xpclr$OG[48]),
    filter(gene.gff3, seqid==xpclr$CHROM[49], start<=xpclr$START[49] & end>=xpclr$END[49]) |> mutate(xpclr_start=xpclr$START[49], xpclr_end=xpclr$END[49], xpclr_pop=xpclr$POP[49], xpclr_og=xpclr$OG[49]),
    filter(gene.gff3, seqid==xpclr$CHROM[50], start<=xpclr$START[50] & end>=xpclr$END[50]) |> mutate(xpclr_start=xpclr$START[50], xpclr_end=xpclr$END[50], xpclr_pop=xpclr$POP[50], xpclr_og=xpclr$OG[50]),
    filter(gene.gff3, seqid==xpclr$CHROM[51], start<=xpclr$START[51] & end>=xpclr$END[51]) |> mutate(xpclr_start=xpclr$START[51], xpclr_end=xpclr$END[51], xpclr_pop=xpclr$POP[51], xpclr_og=xpclr$OG[51]),
    filter(gene.gff3, seqid==xpclr$CHROM[52], start<=xpclr$START[52] & end>=xpclr$END[52]) |> mutate(xpclr_start=xpclr$START[52], xpclr_end=xpclr$END[52], xpclr_pop=xpclr$POP[52], xpclr_og=xpclr$OG[52]),
    filter(gene.gff3, seqid==xpclr$CHROM[53], start<=xpclr$START[53] & end>=xpclr$END[53]) |> mutate(xpclr_start=xpclr$START[53], xpclr_end=xpclr$END[53], xpclr_pop=xpclr$POP[53], xpclr_og=xpclr$OG[53]),
    filter(gene.gff3, seqid==xpclr$CHROM[54], start<=xpclr$START[54] & end>=xpclr$END[54]) |> mutate(xpclr_start=xpclr$START[54], xpclr_end=xpclr$END[54], xpclr_pop=xpclr$POP[54], xpclr_og=xpclr$OG[54]),
    .id="outlier")
genes.across.regions

gene.hits.regions <- 
  bind_rows(genes.within.regions, genes.starting.in.regions, genes.ending.in.regions, genes.across.regions) |> 
  distinct(id, PANTHER_accession, xpclr_pop, xpclr_og, .keep_all=TRUE)

gene.hits.regions <- 
  rename(gene.hits.regions, region=outlier, chrom=seqid) |>
  arrange(chrom, start, xpclr_pop, xpclr_og)
  
gene.hits.regions <- mutate(gene.hits.regions, loc=paste0(chrom, ":", start, "–", end))
  
write_tsv(x=gene.hits.regions, file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.999/XP-CLR.maf.gene.hits.regions.tab")

saveRDS(object=gene.hits.regions, file="/Volumes/Tigrigobius/tgoby/genes/PANTHER.999/XP-CLR.maf.gene.hits.regions.RDS")

